#!/usr/bin/env node
/**
 * Regenerate references/component-catalog.md from the canonical source at
 * server/src/server/protocol/catalog.ts.
 *
 * Run via:
 *   npx tsx .claude/skills/build-moumantai-app/scripts/sync-catalog.ts
 *
 * This keeps the reference doc from drifting when components are added.
 * CI should fail if the generated output differs from the committed file.
 */

import { readFileSync, writeFileSync, existsSync } from 'fs'
import { dirname, join, resolve } from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const SKILL_DIR = resolve(__dirname, '..')
const REPO_ROOT = resolve(SKILL_DIR, '..', '..', '..')
const CATALOG_SRC = join(REPO_ROOT, 'server', 'src', 'server', 'protocol', 'catalog.ts')
const OUT = join(SKILL_DIR, 'references', 'component-catalog.md')

if (!existsSync(CATALOG_SRC)) {
  console.error(`catalog source not found at ${CATALOG_SRC}`)
  process.exit(2)
}

const src = readFileSync(CATALOG_SRC, 'utf8')

interface Entry {
  type: string
  category: string
  builder: string
  signature: string
  supportedDevices: string[]
  description: string
  smallScreenNotes?: string
}

// Match each `{ type: 'X', category: 'Y', builder: 'Z', signature: '...', supportedDevices: [...], description: '...', smallScreenNotes?: '...' }`
const ENTRY_RE =
  /\{\s*type:\s*'([^']+)',\s*category:\s*'([^']+)',\s*builder:\s*'([^']+)',\s*signature:\s*'([^']+)',\s*supportedDevices:\s*\[([^\]]+)\],\s*description:\s*'([^']*)'(?:,\s*smallScreenNotes:\s*'([^']*)')?\s*\}/g

const entries: Entry[] = []
let m: RegExpExecArray | null
while ((m = ENTRY_RE.exec(src)) !== null) {
  const devices = m[5]!
    .split(',')
    .map((s) => s.trim().replace(/['"]/g, ''))
    .filter(Boolean)
  entries.push({
    type: m[1]!,
    category: m[2]!,
    builder: m[3]!,
    signature: m[4]!,
    supportedDevices: devices,
    description: m[6]!,
    smallScreenNotes: m[7] || undefined,
  })
}

if (entries.length === 0) {
  console.error('no entries parsed from catalog.ts; has the file format changed?')
  process.exit(1)
}

// Render
const byCategory = new Map<string, Entry[]>()
for (const e of entries) {
  const list = byCategory.get(e.category) ?? []
  list.push(e)
  byCategory.set(e.category, list)
}

const CATEGORIES = ['atoms', 'layout', 'chrome', 'actions', 'input', 'data', 'feedback'] as const

const lines: string[] = []
lines.push('# Component catalog (generated)')
lines.push('')
lines.push('> Generated by `scripts/sync-catalog.ts` from `server/src/server/protocol/catalog.ts`.')
lines.push('> Do NOT edit by hand — changes will be overwritten. Update `catalog.ts` and rerun:')
lines.push('>')
lines.push('> ```bash')
lines.push('> npx tsx .claude/skills/build-moumantai-app/scripts/sync-catalog.ts')
lines.push('> ```')
lines.push('')
lines.push(
  'All builders are imported from `moumantai/ui`. Use `pathRef` for data binding (see `faces.md` for the two forms).',
)
lines.push('')
lines.push(
  'Compact-first rule: the default face variant (no suffix) must render on watch (192dp) and iot-small (240dp). Watch auto-skips `TopBar` and wraps `Row>2` to `Column`.',
)
lines.push('')

for (const cat of CATEGORIES) {
  const items = byCategory.get(cat) ?? []
  if (items.length === 0) continue
  lines.push(`## ${cat[0]!.toUpperCase() + cat.slice(1)}`)
  lines.push('')
  lines.push('| Builder | Signature | Devices | Description |')
  lines.push('|---|---|---|---|')
  for (const e of items) {
    const devs = e.supportedDevices.join(', ')
    lines.push(`| \`${e.builder}\` | \`${e.signature}\` | ${devs} | ${e.description} |`)
  }
  const notes = items.filter((e) => e.smallScreenNotes)
  if (notes.length > 0) {
    lines.push('')
    lines.push('**Small-screen notes:**')
    for (const e of notes) {
      lines.push(`- \`${e.builder}\` — ${e.smallScreenNotes}`)
    }
  }
  lines.push('')
}

lines.push('---')
lines.push('')
lines.push(
  `Total components: ${entries.length}. Builders are always called with an \`id: string\` as the first argument.`,
)
lines.push('')

const content = lines.join('\n')
writeFileSync(OUT, content)
console.log(`wrote ${OUT} (${entries.length} entries, ${content.length} bytes)`)
