// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.AppVariant in moumantai/v1/enums.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int
import kotlin.Suppress

/**
 * ---------------------------------------------------------------------------
 * App / face variant (live vs. draft preview)
 * ---------------------------------------------------------------------------
 * Live vs. in-progress draft variant. Draft frames are sent only to opted-in
 * dev clients. Unset == LIVE.
 */
public enum class AppVariant(
  override val `value`: Int,
) : WireEnum {
  APP_VARIANT_UNSPECIFIED(0),
  APP_VARIANT_LIVE(1),
  APP_VARIANT_DRAFT(2),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<AppVariant> = object : EnumAdapter<AppVariant>(
      AppVariant::class, 
      PROTO_3, 
      AppVariant.APP_VARIANT_UNSPECIFIED
    ) {
      override fun fromValue(`value`: Int): AppVariant? = AppVariant.fromValue(`value`)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): AppVariant? = when (`value`) {
      0 -> APP_VARIANT_UNSPECIFIED
      1 -> APP_VARIANT_LIVE
      2 -> APP_VARIANT_DRAFT
      else -> null
    }
  }
}
