// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.BodyKind in moumantai/v1/enums.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int
import kotlin.Suppress

/**
 * ---------------------------------------------------------------------------
 * Component layout (structural, framework-controlled — not LLM-authored)
 * ---------------------------------------------------------------------------
 * Body-slot layout for Scaffold. Framework-controlled (closed set).
 * LIST: body is the platform-native lazy/scrollable container; each top-level
 * child is one item. CANVAS: bounded centered Column, no scroll (glance faces).
 * Default LIST.
 */
public enum class BodyKind(
  override val `value`: Int,
) : WireEnum {
  BODY_KIND_UNSPECIFIED(0),
  BODY_KIND_LIST(1),
  BODY_KIND_CANVAS(2),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<BodyKind> = object : EnumAdapter<BodyKind>(
      BodyKind::class, 
      PROTO_3, 
      BodyKind.BODY_KIND_UNSPECIFIED
    ) {
      override fun fromValue(`value`: Int): BodyKind? = BodyKind.fromValue(`value`)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): BodyKind? = when (`value`) {
      0 -> BODY_KIND_UNSPECIFIED
      1 -> BODY_KIND_LIST
      2 -> BODY_KIND_CANVAS
      else -> null
    }
  }
}
