// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.BoxComponent in moumantai/v1/components.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

/**
 * Z-stack overlay container. Children are layered along the z-axis, each
 * anchored to a position within the box's bounds. Canonical use: badge-on-card.
 *
 * Convention: index 0 is the BACKGROUND (defines intrinsic size, may fill
 * width); subsequent children are OVERLAYS painted on top. Renderers flag
 * overlay children so width-filling primitives (Card) skip fillMaxWidth.
 * See `with_box.json` for the canonical fixture.
 *
 * Alignment vocabulary is free-form string (design-system catalog
 * `alignments.values`): topStart, topCenter, topEnd, centerStart, center,
 * centerEnd, bottomStart, bottomCenter, bottomEnd. Default `topStart`.
 */
public class BoxComponent(
  children: List<String> = emptyList(),
  /**
   * Default alignment applied to every child unless overridden by
   * `child_alignment\[i\]` at the same index.
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    jsonName = "contentAlignment",
    schemaIndex = 1,
  )
  public val content_alignment: String? = null,
  child_alignment: List<String> = emptyList(),
  @field:WireField(
    tag = 200,
    adapter = "com.moumantai.protocol.v1.Modifier#ADAPTER",
    schemaIndex = 3,
  )
  public val modifier: Modifier? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<BoxComponent, Nothing>(ADAPTER, unknownFields) {
  /**
   * Children (component ids in order; later entries paint on top).
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    schemaIndex = 0,
  )
  public val children: List<String> = immutableCopyOf("children", children)

  /**
   * Per-child alignment override, parallel to `children` by index. Empty
   * / missing entries fall back to `content_alignment`. Indices outside
   * the array also fall back.
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    jsonName = "childAlignment",
    schemaIndex = 2,
  )
  public val child_alignment: List<String> = immutableCopyOf("child_alignment", child_alignment)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is BoxComponent) return false
    if (unknownFields != other.unknownFields) return false
    if (children != other.children) return false
    if (content_alignment != other.content_alignment) return false
    if (child_alignment != other.child_alignment) return false
    if (modifier != other.modifier) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + children.hashCode()
      result = result * 37 + (content_alignment?.hashCode() ?: 0)
      result = result * 37 + child_alignment.hashCode()
      result = result * 37 + (modifier?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (children.isNotEmpty()) result += """children=${sanitize(children)}"""
    if (content_alignment != null) result += """content_alignment=${sanitize(content_alignment)}"""
    if (child_alignment.isNotEmpty()) result += """child_alignment=${sanitize(child_alignment)}"""
    if (modifier != null) result += """modifier=$modifier"""
    return result.joinToString(prefix = "BoxComponent{", separator = ", ", postfix = "}")
  }

  public fun copy(
    children: List<String> = this.children,
    content_alignment: String? = this.content_alignment,
    child_alignment: List<String> = this.child_alignment,
    modifier: Modifier? = this.modifier,
    unknownFields: ByteString = this.unknownFields,
  ): BoxComponent = BoxComponent(children, content_alignment, child_alignment, modifier,
      unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<BoxComponent> = object : ProtoAdapter<BoxComponent>(
      FieldEncoding.LENGTH_DELIMITED, 
      BoxComponent::class, 
      "type.googleapis.com/moumantai.v1.BoxComponent", 
      PROTO_3, 
      null, 
      "moumantai/v1/components.proto"
    ) {
      override fun encodedSize(`value`: BoxComponent): Int {
        var size = value.unknownFields.size
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(1, value.children)
        size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.content_alignment)
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(3, value.child_alignment)
        size += Modifier.ADAPTER.encodedSizeWithTag(200, value.modifier)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: BoxComponent) {
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 1, value.children)
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.content_alignment)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 3, value.child_alignment)
        Modifier.ADAPTER.encodeWithTag(writer, 200, value.modifier)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: BoxComponent) {
        writer.writeBytes(value.unknownFields)
        Modifier.ADAPTER.encodeWithTag(writer, 200, value.modifier)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 3, value.child_alignment)
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.content_alignment)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 1, value.children)
      }

      override fun decode(reader: ProtoReader): BoxComponent {
        val children = mutableListOf<String>()
        var content_alignment: String? = null
        val child_alignment = mutableListOf<String>()
        var modifier: Modifier? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> children.add(ProtoAdapter.STRING.decode(reader))
            2 -> content_alignment = ProtoAdapter.STRING.decode(reader)
            3 -> child_alignment.add(ProtoAdapter.STRING.decode(reader))
            200 -> modifier = Modifier.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return BoxComponent(
          children = children,
          content_alignment = content_alignment,
          child_alignment = child_alignment,
          modifier = modifier,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: BoxComponent): BoxComponent = value.copy(
        modifier = value.modifier?.let(Modifier.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<BoxComponent> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
