// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.CardComponent in moumantai/v1/components.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

/**
 * Container that holds child components with visual emphasis.
 *
 * Intent axes:
 *   - `emphasis`: 'standard' (default, filled with surface-container-highest)
 *     or 'elevated' (with shadow, for hero / standout content).
 *   - `tone`: 'default' (neutral surface) or 'accent' / 'warning' / 'error' /
 *     'info' (semantic color-container family).
 *
 * State: when `action` is set the card becomes interactive (state-layer on
 * hover / focus / press); when absent the card is decorative.
 */
public class CardComponent(
  children: List<String> = emptyList(),
  /**
   * Optional click action.
   */
  @field:WireField(
    tag = 3,
    adapter = "com.moumantai.protocol.v1.Action#ADAPTER",
    schemaIndex = 1,
  )
  public val action: Action? = null,
  /**
   * Visual weight: 'standard' (default) | 'elevated'.
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 2,
  )
  public val emphasis: String? = null,
  /**
   * Semantic color role: 'default' (neutral) | 'accent' | 'warning' | 'error' | 'info'.
   */
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 3,
  )
  public val tone: String? = null,
  @field:WireField(
    tag = 200,
    adapter = "com.moumantai.protocol.v1.Modifier#ADAPTER",
    schemaIndex = 4,
  )
  public val modifier: Modifier? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<CardComponent, Nothing>(ADAPTER, unknownFields) {
  /**
   * Children (component ids in order).
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    schemaIndex = 0,
  )
  public val children: List<String> = immutableCopyOf("children", children)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is CardComponent) return false
    if (unknownFields != other.unknownFields) return false
    if (children != other.children) return false
    if (action != other.action) return false
    if (emphasis != other.emphasis) return false
    if (tone != other.tone) return false
    if (modifier != other.modifier) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + children.hashCode()
      result = result * 37 + (action?.hashCode() ?: 0)
      result = result * 37 + (emphasis?.hashCode() ?: 0)
      result = result * 37 + (tone?.hashCode() ?: 0)
      result = result * 37 + (modifier?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (children.isNotEmpty()) result += """children=${sanitize(children)}"""
    if (action != null) result += """action=$action"""
    if (emphasis != null) result += """emphasis=${sanitize(emphasis)}"""
    if (tone != null) result += """tone=${sanitize(tone)}"""
    if (modifier != null) result += """modifier=$modifier"""
    return result.joinToString(prefix = "CardComponent{", separator = ", ", postfix = "}")
  }

  public fun copy(
    children: List<String> = this.children,
    action: Action? = this.action,
    emphasis: String? = this.emphasis,
    tone: String? = this.tone,
    modifier: Modifier? = this.modifier,
    unknownFields: ByteString = this.unknownFields,
  ): CardComponent = CardComponent(children, action, emphasis, tone, modifier, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<CardComponent> = object : ProtoAdapter<CardComponent>(
      FieldEncoding.LENGTH_DELIMITED, 
      CardComponent::class, 
      "type.googleapis.com/moumantai.v1.CardComponent", 
      PROTO_3, 
      null, 
      "moumantai/v1/components.proto"
    ) {
      override fun encodedSize(`value`: CardComponent): Int {
        var size = value.unknownFields.size
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(1, value.children)
        size += Action.ADAPTER.encodedSizeWithTag(3, value.action)
        size += ProtoAdapter.STRING.encodedSizeWithTag(4, value.emphasis)
        size += ProtoAdapter.STRING.encodedSizeWithTag(5, value.tone)
        size += Modifier.ADAPTER.encodedSizeWithTag(200, value.modifier)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: CardComponent) {
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 1, value.children)
        Action.ADAPTER.encodeWithTag(writer, 3, value.action)
        ProtoAdapter.STRING.encodeWithTag(writer, 4, value.emphasis)
        ProtoAdapter.STRING.encodeWithTag(writer, 5, value.tone)
        Modifier.ADAPTER.encodeWithTag(writer, 200, value.modifier)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: CardComponent) {
        writer.writeBytes(value.unknownFields)
        Modifier.ADAPTER.encodeWithTag(writer, 200, value.modifier)
        ProtoAdapter.STRING.encodeWithTag(writer, 5, value.tone)
        ProtoAdapter.STRING.encodeWithTag(writer, 4, value.emphasis)
        Action.ADAPTER.encodeWithTag(writer, 3, value.action)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 1, value.children)
      }

      override fun decode(reader: ProtoReader): CardComponent {
        val children = mutableListOf<String>()
        var action: Action? = null
        var emphasis: String? = null
        var tone: String? = null
        var modifier: Modifier? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> children.add(ProtoAdapter.STRING.decode(reader))
            3 -> action = Action.ADAPTER.decode(reader)
            4 -> emphasis = ProtoAdapter.STRING.decode(reader)
            5 -> tone = ProtoAdapter.STRING.decode(reader)
            200 -> modifier = Modifier.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return CardComponent(
          children = children,
          action = action,
          emphasis = emphasis,
          tone = tone,
          modifier = modifier,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: CardComponent): CardComponent = value.copy(
        action = value.action?.let(Action.ADAPTER::redact),
        modifier = value.modifier?.let(Modifier.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<CardComponent> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
