// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.ChatWindowMsg in moumantai/v1/chat.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

/**
 * Server → client authoritative snapshot of a scope's active conversation.
 * Sent in response to `ViewingMsg` and after `ResetConversationMsg`.
 * Not durable. Client replaces its chat log wholesale; a changed
 * `conversation_id` signals to drop the prior cache.
 */
public class ChatWindowMsg(
  /**
   * 'home' or 'app:<app_id>'.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val scope: String = "",
  /**
   * Conversation UUID for the entries below.
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "conversationId",
    schemaIndex = 1,
  )
  public val conversation_id: String = "",
  entries: List<ChatWindowEntry> = emptyList(),
  /**
   * Thread kind for this window. Unset == CHAT.
   */
  @field:WireField(
    tag = 4,
    adapter = "com.moumantai.protocol.v1.ChatKind#ADAPTER",
    schemaIndex = 3,
  )
  public val kind: ChatKind? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<ChatWindowMsg, Nothing>(ADAPTER, unknownFields) {
  /**
   * Authoritative log entries.
   */
  @field:WireField(
    tag = 3,
    adapter = "com.moumantai.protocol.v1.ChatWindowEntry#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 2,
  )
  public val entries: List<ChatWindowEntry> = immutableCopyOf("entries", entries)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ChatWindowMsg) return false
    if (unknownFields != other.unknownFields) return false
    if (scope != other.scope) return false
    if (conversation_id != other.conversation_id) return false
    if (entries != other.entries) return false
    if (kind != other.kind) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + scope.hashCode()
      result = result * 37 + conversation_id.hashCode()
      result = result * 37 + entries.hashCode()
      result = result * 37 + (kind?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """scope=${sanitize(scope)}"""
    result += """conversation_id=${sanitize(conversation_id)}"""
    if (entries.isNotEmpty()) result += """entries=$entries"""
    if (kind != null) result += """kind=$kind"""
    return result.joinToString(prefix = "ChatWindowMsg{", separator = ", ", postfix = "}")
  }

  public fun copy(
    scope: String = this.scope,
    conversation_id: String = this.conversation_id,
    entries: List<ChatWindowEntry> = this.entries,
    kind: ChatKind? = this.kind,
    unknownFields: ByteString = this.unknownFields,
  ): ChatWindowMsg = ChatWindowMsg(scope, conversation_id, entries, kind, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ChatWindowMsg> = object : ProtoAdapter<ChatWindowMsg>(
      FieldEncoding.LENGTH_DELIMITED, 
      ChatWindowMsg::class, 
      "type.googleapis.com/moumantai.v1.ChatWindowMsg", 
      PROTO_3, 
      null, 
      "moumantai/v1/chat.proto"
    ) {
      override fun encodedSize(`value`: ChatWindowMsg): Int {
        var size = value.unknownFields.size
        if (value.scope != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.scope)
        }
        if (value.conversation_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.conversation_id)
        }
        size += ChatWindowEntry.ADAPTER.asRepeated().encodedSizeWithTag(3, value.entries)
        size += ChatKind.ADAPTER.encodedSizeWithTag(4, value.kind)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ChatWindowMsg) {
        if (value.scope != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.scope)
        }
        if (value.conversation_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.conversation_id)
        }
        ChatWindowEntry.ADAPTER.asRepeated().encodeWithTag(writer, 3, value.entries)
        ChatKind.ADAPTER.encodeWithTag(writer, 4, value.kind)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ChatWindowMsg) {
        writer.writeBytes(value.unknownFields)
        ChatKind.ADAPTER.encodeWithTag(writer, 4, value.kind)
        ChatWindowEntry.ADAPTER.asRepeated().encodeWithTag(writer, 3, value.entries)
        if (value.conversation_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.conversation_id)
        }
        if (value.scope != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.scope)
        }
      }

      override fun decode(reader: ProtoReader): ChatWindowMsg {
        var scope: String = ""
        var conversation_id: String = ""
        val entries = mutableListOf<ChatWindowEntry>()
        var kind: ChatKind? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> scope = ProtoAdapter.STRING.decode(reader)
            2 -> conversation_id = ProtoAdapter.STRING.decode(reader)
            3 -> entries.add(ChatWindowEntry.ADAPTER.decode(reader))
            4 -> try {
              kind = ChatKind.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            else -> reader.readUnknownField(tag)
          }
        }
        return ChatWindowMsg(
          scope = scope,
          conversation_id = conversation_id,
          entries = entries,
          kind = kind,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ChatWindowMsg): ChatWindowMsg = value.copy(
        entries = value.entries.redactElements(ChatWindowEntry.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<ChatWindowMsg> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
