// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.ChatMessage in moumantai/v1/chat.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

/**
 * ---------------------------------------------------------------------------
 * Server → client chat
 * ---------------------------------------------------------------------------
 * A chat message delivered from the server (user echo or assistant reply).
 */
public class ChatMessage(
  /**
   * Unique message UUID.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val id: String = "",
  /**
   * Conversation scope: 'home' or 'app:<app_id>'.
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val scope: String = "",
  /**
   * Conversation UUID. Clients comparing across frames detect resets via a
   * changed conversation_id.
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "conversationId",
    schemaIndex = 2,
  )
  public val conversation_id: String = "",
  /**
   * Speaker role.
   */
  @field:WireField(
    tag = 4,
    adapter = "com.moumantai.protocol.v1.ChatRole#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val role: ChatRole = ChatRole.CHAT_ROLE_UNSPECIFIED,
  /**
   * Message body.
   */
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 4,
  )
  public val text: String = "",
  /**
   * ISO-8601 timestamp.
   */
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 5,
  )
  public val timestamp: String = "",
  /**
   * Client-generated UUID echoed back for optimistic-UI reconciliation. Set
   * on frames whose originator supplied a `client_msg_id` on `chatInput`.
   */
  @field:WireField(
    tag = 7,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    jsonName = "clientMsgId",
    schemaIndex = 6,
  )
  public val client_msg_id: String? = null,
  /**
   * Turn lifecycle status. Only meaningful for user rows; assistant/system
   * rows are always TURN_STATUS_COMPLETED.
   */
  @field:WireField(
    tag = 8,
    adapter = "com.moumantai.protocol.v1.TurnStatus#ADAPTER",
    schemaIndex = 7,
  )
  public val status: TurnStatus? = null,
  /**
   * Short tag populated alongside terminal failure statuses.
   */
  @field:WireField(
    tag = 9,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    jsonName = "failureReason",
    schemaIndex = 8,
  )
  public val failure_reason: String? = null,
  /**
   * URL for pre-rendered TTS audio.
   */
  @field:WireField(
    tag = 10,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    jsonName = "audioUrl",
    schemaIndex = 9,
  )
  public val audio_url: String? = null,
  ui_blocks: List<ComponentDef> = emptyList(),
  /**
   * Stable deviceId of the originating device. Set on user rows only —
   * assistant/system rows omit it.
   */
  @field:WireField(
    tag = 12,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    jsonName = "originDeviceId",
    schemaIndex = 11,
  )
  public val origin_device_id: String? = null,
  /**
   * Thread kind. Unset == CHAT.
   */
  @field:WireField(
    tag = 13,
    adapter = "com.moumantai.protocol.v1.ChatKind#ADAPTER",
    schemaIndex = 12,
  )
  public val kind: ChatKind? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<ChatMessage, Nothing>(ADAPTER, unknownFields) {
  /**
   * Inline Moumantai UI components rendered alongside the text.
   */
  @field:WireField(
    tag = 11,
    adapter = "com.moumantai.protocol.v1.ComponentDef#ADAPTER",
    label = WireField.Label.REPEATED,
    jsonName = "uiBlocks",
    schemaIndex = 10,
  )
  public val ui_blocks: List<ComponentDef> = immutableCopyOf("ui_blocks", ui_blocks)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ChatMessage) return false
    if (unknownFields != other.unknownFields) return false
    if (id != other.id) return false
    if (scope != other.scope) return false
    if (conversation_id != other.conversation_id) return false
    if (role != other.role) return false
    if (text != other.text) return false
    if (timestamp != other.timestamp) return false
    if (client_msg_id != other.client_msg_id) return false
    if (status != other.status) return false
    if (failure_reason != other.failure_reason) return false
    if (audio_url != other.audio_url) return false
    if (ui_blocks != other.ui_blocks) return false
    if (origin_device_id != other.origin_device_id) return false
    if (kind != other.kind) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + id.hashCode()
      result = result * 37 + scope.hashCode()
      result = result * 37 + conversation_id.hashCode()
      result = result * 37 + role.hashCode()
      result = result * 37 + text.hashCode()
      result = result * 37 + timestamp.hashCode()
      result = result * 37 + (client_msg_id?.hashCode() ?: 0)
      result = result * 37 + (status?.hashCode() ?: 0)
      result = result * 37 + (failure_reason?.hashCode() ?: 0)
      result = result * 37 + (audio_url?.hashCode() ?: 0)
      result = result * 37 + ui_blocks.hashCode()
      result = result * 37 + (origin_device_id?.hashCode() ?: 0)
      result = result * 37 + (kind?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """id=${sanitize(id)}"""
    result += """scope=${sanitize(scope)}"""
    result += """conversation_id=${sanitize(conversation_id)}"""
    result += """role=$role"""
    result += """text=${sanitize(text)}"""
    result += """timestamp=${sanitize(timestamp)}"""
    if (client_msg_id != null) result += """client_msg_id=${sanitize(client_msg_id)}"""
    if (status != null) result += """status=$status"""
    if (failure_reason != null) result += """failure_reason=${sanitize(failure_reason)}"""
    if (audio_url != null) result += """audio_url=${sanitize(audio_url)}"""
    if (ui_blocks.isNotEmpty()) result += """ui_blocks=$ui_blocks"""
    if (origin_device_id != null) result += """origin_device_id=${sanitize(origin_device_id)}"""
    if (kind != null) result += """kind=$kind"""
    return result.joinToString(prefix = "ChatMessage{", separator = ", ", postfix = "}")
  }

  public fun copy(
    id: String = this.id,
    scope: String = this.scope,
    conversation_id: String = this.conversation_id,
    role: ChatRole = this.role,
    text: String = this.text,
    timestamp: String = this.timestamp,
    client_msg_id: String? = this.client_msg_id,
    status: TurnStatus? = this.status,
    failure_reason: String? = this.failure_reason,
    audio_url: String? = this.audio_url,
    ui_blocks: List<ComponentDef> = this.ui_blocks,
    origin_device_id: String? = this.origin_device_id,
    kind: ChatKind? = this.kind,
    unknownFields: ByteString = this.unknownFields,
  ): ChatMessage = ChatMessage(id, scope, conversation_id, role, text, timestamp, client_msg_id,
      status, failure_reason, audio_url, ui_blocks, origin_device_id, kind, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ChatMessage> = object : ProtoAdapter<ChatMessage>(
      FieldEncoding.LENGTH_DELIMITED, 
      ChatMessage::class, 
      "type.googleapis.com/moumantai.v1.ChatMessage", 
      PROTO_3, 
      null, 
      "moumantai/v1/chat.proto"
    ) {
      override fun encodedSize(`value`: ChatMessage): Int {
        var size = value.unknownFields.size
        if (value.id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.id)
        }
        if (value.scope != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.scope)
        }
        if (value.conversation_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.conversation_id)
        }
        if (value.role != com.moumantai.protocol.v1.ChatRole.CHAT_ROLE_UNSPECIFIED) {
          size += ChatRole.ADAPTER.encodedSizeWithTag(4, value.role)
        }
        if (value.text != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(5, value.text)
        }
        if (value.timestamp != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(6, value.timestamp)
        }
        size += ProtoAdapter.STRING.encodedSizeWithTag(7, value.client_msg_id)
        size += TurnStatus.ADAPTER.encodedSizeWithTag(8, value.status)
        size += ProtoAdapter.STRING.encodedSizeWithTag(9, value.failure_reason)
        size += ProtoAdapter.STRING.encodedSizeWithTag(10, value.audio_url)
        size += ComponentDef.ADAPTER.asRepeated().encodedSizeWithTag(11, value.ui_blocks)
        size += ProtoAdapter.STRING.encodedSizeWithTag(12, value.origin_device_id)
        size += ChatKind.ADAPTER.encodedSizeWithTag(13, value.kind)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ChatMessage) {
        if (value.id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.id)
        }
        if (value.scope != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.scope)
        }
        if (value.conversation_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.conversation_id)
        }
        if (value.role != com.moumantai.protocol.v1.ChatRole.CHAT_ROLE_UNSPECIFIED) {
          ChatRole.ADAPTER.encodeWithTag(writer, 4, value.role)
        }
        if (value.text != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 5, value.text)
        }
        if (value.timestamp != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 6, value.timestamp)
        }
        ProtoAdapter.STRING.encodeWithTag(writer, 7, value.client_msg_id)
        TurnStatus.ADAPTER.encodeWithTag(writer, 8, value.status)
        ProtoAdapter.STRING.encodeWithTag(writer, 9, value.failure_reason)
        ProtoAdapter.STRING.encodeWithTag(writer, 10, value.audio_url)
        ComponentDef.ADAPTER.asRepeated().encodeWithTag(writer, 11, value.ui_blocks)
        ProtoAdapter.STRING.encodeWithTag(writer, 12, value.origin_device_id)
        ChatKind.ADAPTER.encodeWithTag(writer, 13, value.kind)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ChatMessage) {
        writer.writeBytes(value.unknownFields)
        ChatKind.ADAPTER.encodeWithTag(writer, 13, value.kind)
        ProtoAdapter.STRING.encodeWithTag(writer, 12, value.origin_device_id)
        ComponentDef.ADAPTER.asRepeated().encodeWithTag(writer, 11, value.ui_blocks)
        ProtoAdapter.STRING.encodeWithTag(writer, 10, value.audio_url)
        ProtoAdapter.STRING.encodeWithTag(writer, 9, value.failure_reason)
        TurnStatus.ADAPTER.encodeWithTag(writer, 8, value.status)
        ProtoAdapter.STRING.encodeWithTag(writer, 7, value.client_msg_id)
        if (value.timestamp != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 6, value.timestamp)
        }
        if (value.text != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 5, value.text)
        }
        if (value.role != com.moumantai.protocol.v1.ChatRole.CHAT_ROLE_UNSPECIFIED) {
          ChatRole.ADAPTER.encodeWithTag(writer, 4, value.role)
        }
        if (value.conversation_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.conversation_id)
        }
        if (value.scope != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.scope)
        }
        if (value.id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.id)
        }
      }

      override fun decode(reader: ProtoReader): ChatMessage {
        var id: String = ""
        var scope: String = ""
        var conversation_id: String = ""
        var role: ChatRole = ChatRole.CHAT_ROLE_UNSPECIFIED
        var text: String = ""
        var timestamp: String = ""
        var client_msg_id: String? = null
        var status: TurnStatus? = null
        var failure_reason: String? = null
        var audio_url: String? = null
        val ui_blocks = mutableListOf<ComponentDef>()
        var origin_device_id: String? = null
        var kind: ChatKind? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> id = ProtoAdapter.STRING.decode(reader)
            2 -> scope = ProtoAdapter.STRING.decode(reader)
            3 -> conversation_id = ProtoAdapter.STRING.decode(reader)
            4 -> try {
              role = ChatRole.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            5 -> text = ProtoAdapter.STRING.decode(reader)
            6 -> timestamp = ProtoAdapter.STRING.decode(reader)
            7 -> client_msg_id = ProtoAdapter.STRING.decode(reader)
            8 -> try {
              status = TurnStatus.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            9 -> failure_reason = ProtoAdapter.STRING.decode(reader)
            10 -> audio_url = ProtoAdapter.STRING.decode(reader)
            11 -> ui_blocks.add(ComponentDef.ADAPTER.decode(reader))
            12 -> origin_device_id = ProtoAdapter.STRING.decode(reader)
            13 -> try {
              kind = ChatKind.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            else -> reader.readUnknownField(tag)
          }
        }
        return ChatMessage(
          id = id,
          scope = scope,
          conversation_id = conversation_id,
          role = role,
          text = text,
          timestamp = timestamp,
          client_msg_id = client_msg_id,
          status = status,
          failure_reason = failure_reason,
          audio_url = audio_url,
          ui_blocks = ui_blocks,
          origin_device_id = origin_device_id,
          kind = kind,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ChatMessage): ChatMessage = value.copy(
        ui_blocks = value.ui_blocks.redactElements(ComponentDef.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<ChatMessage> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
