// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.ChatRole in moumantai/v1/enums.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int
import kotlin.Suppress

/**
 * Speaker role on a chat row.
 */
public enum class ChatRole(
  override val `value`: Int,
) : WireEnum {
  CHAT_ROLE_UNSPECIFIED(0),
  CHAT_ROLE_USER(1),
  CHAT_ROLE_ASSISTANT(2),
  CHAT_ROLE_SYSTEM(3),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ChatRole> = object : EnumAdapter<ChatRole>(
      ChatRole::class, 
      PROTO_3, 
      ChatRole.CHAT_ROLE_UNSPECIFIED
    ) {
      override fun fromValue(`value`: Int): ChatRole? = ChatRole.fromValue(`value`)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): ChatRole? = when (`value`) {
      0 -> CHAT_ROLE_UNSPECIFIED
      1 -> CHAT_ROLE_USER
      2 -> CHAT_ROLE_ASSISTANT
      3 -> CHAT_ROLE_SYSTEM
      else -> null
    }
  }
}
