// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.ChipComponent in moumantai/v1/components.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Compact selectable element. Behavior is data-driven:
 *   - `selected` bound → filter chip (secondary-container fill when selected).
 *   - `action` only (no `selected`) → assist chip (neutral outlined).
 *
 * `tone`: 'default' | 'accent' | 'warning' | 'error'.
 */
public class ChipComponent(
  /**
   * Chip label (may be path-resolved).
   */
  @field:WireField(
    tag = 1,
    adapter = "com.moumantai.protocol.v1.DynamicString#ADAPTER",
    schemaIndex = 0,
  )
  public val label: DynamicString? = null,
  /**
   * Optional leading icon.
   */
  @field:WireField(
    tag = 2,
    adapter = "com.moumantai.protocol.v1.DynamicString#ADAPTER",
    schemaIndex = 1,
  )
  public val icon: DynamicString? = null,
  /**
   * Selected state — presence implies filter-chip behavior.
   */
  @field:WireField(
    tag = 3,
    adapter = "com.moumantai.protocol.v1.DynamicBool#ADAPTER",
    schemaIndex = 2,
  )
  public val selected: DynamicBool? = null,
  /**
   * Click action.
   */
  @field:WireField(
    tag = 5,
    adapter = "com.moumantai.protocol.v1.Action#ADAPTER",
    schemaIndex = 3,
  )
  public val action: Action? = null,
  /**
   * Semantic color role: 'default' (neutral) | 'accent' | 'warning' | 'error'.
   */
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 4,
  )
  public val tone: String? = null,
  @field:WireField(
    tag = 200,
    adapter = "com.moumantai.protocol.v1.Modifier#ADAPTER",
    schemaIndex = 5,
  )
  public val modifier: Modifier? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<ChipComponent, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ChipComponent) return false
    if (unknownFields != other.unknownFields) return false
    if (label != other.label) return false
    if (icon != other.icon) return false
    if (selected != other.selected) return false
    if (action != other.action) return false
    if (tone != other.tone) return false
    if (modifier != other.modifier) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (label?.hashCode() ?: 0)
      result = result * 37 + (icon?.hashCode() ?: 0)
      result = result * 37 + (selected?.hashCode() ?: 0)
      result = result * 37 + (action?.hashCode() ?: 0)
      result = result * 37 + (tone?.hashCode() ?: 0)
      result = result * 37 + (modifier?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (label != null) result += """label=$label"""
    if (icon != null) result += """icon=$icon"""
    if (selected != null) result += """selected=$selected"""
    if (action != null) result += """action=$action"""
    if (tone != null) result += """tone=${sanitize(tone)}"""
    if (modifier != null) result += """modifier=$modifier"""
    return result.joinToString(prefix = "ChipComponent{", separator = ", ", postfix = "}")
  }

  public fun copy(
    label: DynamicString? = this.label,
    icon: DynamicString? = this.icon,
    selected: DynamicBool? = this.selected,
    action: Action? = this.action,
    tone: String? = this.tone,
    modifier: Modifier? = this.modifier,
    unknownFields: ByteString = this.unknownFields,
  ): ChipComponent = ChipComponent(label, icon, selected, action, tone, modifier, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ChipComponent> = object : ProtoAdapter<ChipComponent>(
      FieldEncoding.LENGTH_DELIMITED, 
      ChipComponent::class, 
      "type.googleapis.com/moumantai.v1.ChipComponent", 
      PROTO_3, 
      null, 
      "moumantai/v1/components.proto"
    ) {
      override fun encodedSize(`value`: ChipComponent): Int {
        var size = value.unknownFields.size
        size += DynamicString.ADAPTER.encodedSizeWithTag(1, value.label)
        size += DynamicString.ADAPTER.encodedSizeWithTag(2, value.icon)
        size += DynamicBool.ADAPTER.encodedSizeWithTag(3, value.selected)
        size += Action.ADAPTER.encodedSizeWithTag(5, value.action)
        size += ProtoAdapter.STRING.encodedSizeWithTag(6, value.tone)
        size += Modifier.ADAPTER.encodedSizeWithTag(200, value.modifier)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ChipComponent) {
        DynamicString.ADAPTER.encodeWithTag(writer, 1, value.label)
        DynamicString.ADAPTER.encodeWithTag(writer, 2, value.icon)
        DynamicBool.ADAPTER.encodeWithTag(writer, 3, value.selected)
        Action.ADAPTER.encodeWithTag(writer, 5, value.action)
        ProtoAdapter.STRING.encodeWithTag(writer, 6, value.tone)
        Modifier.ADAPTER.encodeWithTag(writer, 200, value.modifier)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ChipComponent) {
        writer.writeBytes(value.unknownFields)
        Modifier.ADAPTER.encodeWithTag(writer, 200, value.modifier)
        ProtoAdapter.STRING.encodeWithTag(writer, 6, value.tone)
        Action.ADAPTER.encodeWithTag(writer, 5, value.action)
        DynamicBool.ADAPTER.encodeWithTag(writer, 3, value.selected)
        DynamicString.ADAPTER.encodeWithTag(writer, 2, value.icon)
        DynamicString.ADAPTER.encodeWithTag(writer, 1, value.label)
      }

      override fun decode(reader: ProtoReader): ChipComponent {
        var label: DynamicString? = null
        var icon: DynamicString? = null
        var selected: DynamicBool? = null
        var action: Action? = null
        var tone: String? = null
        var modifier: Modifier? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> label = DynamicString.ADAPTER.decode(reader)
            2 -> icon = DynamicString.ADAPTER.decode(reader)
            3 -> selected = DynamicBool.ADAPTER.decode(reader)
            5 -> action = Action.ADAPTER.decode(reader)
            6 -> tone = ProtoAdapter.STRING.decode(reader)
            200 -> modifier = Modifier.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ChipComponent(
          label = label,
          icon = icon,
          selected = selected,
          action = action,
          tone = tone,
          modifier = modifier,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ChipComponent): ChipComponent = value.copy(
        label = value.label?.let(DynamicString.ADAPTER::redact),
        icon = value.icon?.let(DynamicString.ADAPTER::redact),
        selected = value.selected?.let(DynamicBool.ADAPTER::redact),
        action = value.action?.let(Action.ADAPTER::redact),
        modifier = value.modifier?.let(Modifier.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<ChipComponent> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
