// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.Dimension in moumantai/v1/components.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.countNonNull
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Dimension scalar: fixed dp value, sizing keyword, or per-edge padding.
 */
public class Dimension(
  /**
   * Fixed dp value (≥ 0).
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    oneofName = "kind",
    schemaIndex = 0,
  )
  public val dp: Int? = null,
  /**
   * Sizing keyword: 'fill', 'wrap', 'grow'. Free-form to allow future
   * additions without a wire-breaking enum.
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    oneofName = "kind",
    schemaIndex = 1,
  )
  public val keyword: String? = null,
  /**
   * Per-edge padding (only valid for `padding` slots).
   */
  @field:WireField(
    tag = 3,
    adapter = "com.moumantai.protocol.v1.PaddingEdges#ADAPTER",
    oneofName = "kind",
    schemaIndex = 2,
  )
  public val edges: PaddingEdges? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<Dimension, Nothing>(ADAPTER, unknownFields) {
  init {
    require(countNonNull(dp, keyword, edges) <= 1) {
      "At most one of dp, keyword, edges may be non-null"
    }
  }

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is Dimension) return false
    if (unknownFields != other.unknownFields) return false
    if (dp != other.dp) return false
    if (keyword != other.keyword) return false
    if (edges != other.edges) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (dp?.hashCode() ?: 0)
      result = result * 37 + (keyword?.hashCode() ?: 0)
      result = result * 37 + (edges?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (dp != null) result += """dp=$dp"""
    if (keyword != null) result += """keyword=${sanitize(keyword)}"""
    if (edges != null) result += """edges=$edges"""
    return result.joinToString(prefix = "Dimension{", separator = ", ", postfix = "}")
  }

  public fun copy(
    dp: Int? = this.dp,
    keyword: String? = this.keyword,
    edges: PaddingEdges? = this.edges,
    unknownFields: ByteString = this.unknownFields,
  ): Dimension = Dimension(dp, keyword, edges, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<Dimension> = object : ProtoAdapter<Dimension>(
      FieldEncoding.LENGTH_DELIMITED, 
      Dimension::class, 
      "type.googleapis.com/moumantai.v1.Dimension", 
      PROTO_3, 
      null, 
      "moumantai/v1/components.proto"
    ) {
      override fun encodedSize(`value`: Dimension): Int {
        var size = value.unknownFields.size
        size += ProtoAdapter.INT32.encodedSizeWithTag(1, value.dp)
        size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.keyword)
        size += PaddingEdges.ADAPTER.encodedSizeWithTag(3, value.edges)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: Dimension) {
        ProtoAdapter.INT32.encodeWithTag(writer, 1, value.dp)
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.keyword)
        PaddingEdges.ADAPTER.encodeWithTag(writer, 3, value.edges)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: Dimension) {
        writer.writeBytes(value.unknownFields)
        PaddingEdges.ADAPTER.encodeWithTag(writer, 3, value.edges)
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.keyword)
        ProtoAdapter.INT32.encodeWithTag(writer, 1, value.dp)
      }

      override fun decode(reader: ProtoReader): Dimension {
        var dp: Int? = null
        var keyword: String? = null
        var edges: PaddingEdges? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> dp = ProtoAdapter.INT32.decode(reader)
            2 -> keyword = ProtoAdapter.STRING.decode(reader)
            3 -> edges = PaddingEdges.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return Dimension(
          dp = dp,
          keyword = keyword,
          edges = edges,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: Dimension): Dimension = value.copy(
        edges = value.edges?.let(PaddingEdges.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<Dimension> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
