// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.DraftSummary in moumantai/v1/drafts.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * ---------------------------------------------------------------------------
 * Draft descriptor
 * ---------------------------------------------------------------------------
 * Full snapshot of a draft's server-side state. Always a complete snapshot —
 * client replaces its `drafts` map entry on receipt.
 */
public class DraftSummary(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "draftId",
    schemaIndex = 0,
  )
  public val draft_id: String = "",
  /**
   * For new-app drafts, initially the draft_id; updated to the agent-chosen
   * manifest.id after the first Reload post-scaffold.
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "appId",
    schemaIndex = 1,
  )
  public val app_id: String = "",
  @field:WireField(
    tag = 3,
    adapter = "com.moumantai.protocol.v1.DraftKind#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val kind: DraftKind = DraftKind.DRAFT_KIND_UNSPECIFIED,
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "createdAtMs",
    schemaIndex = 3,
  )
  public val created_at_ms: Long = 0L,
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "messageCount",
    schemaIndex = 4,
  )
  public val message_count: Int = 0,
  /**
   * Agent ran all validators and recommends promoting. Cleared on every new
   * dev-chat message. Hint only — does NOT gate Promote (that's `previewable`).
   */
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "readyForReview",
    schemaIndex = 5,
  )
  public val ready_for_review: Boolean = false,
  /**
   * Agent's one-paragraph summary, rendered in the Ready panel.
   */
  @field:WireField(
    tag = 7,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 6,
  )
  public val summary: String? = null,
  /**
   * True when the draft has a booted, renderable app — this is the Promote
   * gate. Recomputed from the registry on reconnect (unlike `ready_for_review`
   * which the agent must re-assert each turn).
   */
  @field:WireField(
    tag = 8,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 7,
  )
  public val previewable: Boolean = false,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<DraftSummary, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is DraftSummary) return false
    if (unknownFields != other.unknownFields) return false
    if (draft_id != other.draft_id) return false
    if (app_id != other.app_id) return false
    if (kind != other.kind) return false
    if (created_at_ms != other.created_at_ms) return false
    if (message_count != other.message_count) return false
    if (ready_for_review != other.ready_for_review) return false
    if (summary != other.summary) return false
    if (previewable != other.previewable) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + draft_id.hashCode()
      result = result * 37 + app_id.hashCode()
      result = result * 37 + kind.hashCode()
      result = result * 37 + created_at_ms.hashCode()
      result = result * 37 + message_count.hashCode()
      result = result * 37 + ready_for_review.hashCode()
      result = result * 37 + (summary?.hashCode() ?: 0)
      result = result * 37 + previewable.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """draft_id=${sanitize(draft_id)}"""
    result += """app_id=${sanitize(app_id)}"""
    result += """kind=$kind"""
    result += """created_at_ms=$created_at_ms"""
    result += """message_count=$message_count"""
    result += """ready_for_review=$ready_for_review"""
    if (summary != null) result += """summary=${sanitize(summary)}"""
    result += """previewable=$previewable"""
    return result.joinToString(prefix = "DraftSummary{", separator = ", ", postfix = "}")
  }

  public fun copy(
    draft_id: String = this.draft_id,
    app_id: String = this.app_id,
    kind: DraftKind = this.kind,
    created_at_ms: Long = this.created_at_ms,
    message_count: Int = this.message_count,
    ready_for_review: Boolean = this.ready_for_review,
    summary: String? = this.summary,
    previewable: Boolean = this.previewable,
    unknownFields: ByteString = this.unknownFields,
  ): DraftSummary = DraftSummary(draft_id, app_id, kind, created_at_ms, message_count,
      ready_for_review, summary, previewable, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<DraftSummary> = object : ProtoAdapter<DraftSummary>(
      FieldEncoding.LENGTH_DELIMITED, 
      DraftSummary::class, 
      "type.googleapis.com/moumantai.v1.DraftSummary", 
      PROTO_3, 
      null, 
      "moumantai/v1/drafts.proto"
    ) {
      override fun encodedSize(`value`: DraftSummary): Int {
        var size = value.unknownFields.size
        if (value.draft_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.draft_id)
        }
        if (value.app_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.app_id)
        }
        if (value.kind != com.moumantai.protocol.v1.DraftKind.DRAFT_KIND_UNSPECIFIED) {
          size += DraftKind.ADAPTER.encodedSizeWithTag(3, value.kind)
        }
        if (value.created_at_ms != 0L) {
          size += ProtoAdapter.INT64.encodedSizeWithTag(4, value.created_at_ms)
        }
        if (value.message_count != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(5, value.message_count)
        }
        if (value.ready_for_review != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(6, value.ready_for_review)
        }
        size += ProtoAdapter.STRING.encodedSizeWithTag(7, value.summary)
        if (value.previewable != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(8, value.previewable)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: DraftSummary) {
        if (value.draft_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.draft_id)
        }
        if (value.app_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.app_id)
        }
        if (value.kind != com.moumantai.protocol.v1.DraftKind.DRAFT_KIND_UNSPECIFIED) {
          DraftKind.ADAPTER.encodeWithTag(writer, 3, value.kind)
        }
        if (value.created_at_ms != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 4, value.created_at_ms)
        }
        if (value.message_count != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 5, value.message_count)
        }
        if (value.ready_for_review != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 6, value.ready_for_review)
        }
        ProtoAdapter.STRING.encodeWithTag(writer, 7, value.summary)
        if (value.previewable != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 8, value.previewable)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: DraftSummary) {
        writer.writeBytes(value.unknownFields)
        if (value.previewable != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 8, value.previewable)
        }
        ProtoAdapter.STRING.encodeWithTag(writer, 7, value.summary)
        if (value.ready_for_review != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 6, value.ready_for_review)
        }
        if (value.message_count != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 5, value.message_count)
        }
        if (value.created_at_ms != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 4, value.created_at_ms)
        }
        if (value.kind != com.moumantai.protocol.v1.DraftKind.DRAFT_KIND_UNSPECIFIED) {
          DraftKind.ADAPTER.encodeWithTag(writer, 3, value.kind)
        }
        if (value.app_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.app_id)
        }
        if (value.draft_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.draft_id)
        }
      }

      override fun decode(reader: ProtoReader): DraftSummary {
        var draft_id: String = ""
        var app_id: String = ""
        var kind: DraftKind = DraftKind.DRAFT_KIND_UNSPECIFIED
        var created_at_ms: Long = 0L
        var message_count: Int = 0
        var ready_for_review: Boolean = false
        var summary: String? = null
        var previewable: Boolean = false
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> draft_id = ProtoAdapter.STRING.decode(reader)
            2 -> app_id = ProtoAdapter.STRING.decode(reader)
            3 -> try {
              kind = DraftKind.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            4 -> created_at_ms = ProtoAdapter.INT64.decode(reader)
            5 -> message_count = ProtoAdapter.INT32.decode(reader)
            6 -> ready_for_review = ProtoAdapter.BOOL.decode(reader)
            7 -> summary = ProtoAdapter.STRING.decode(reader)
            8 -> previewable = ProtoAdapter.BOOL.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return DraftSummary(
          draft_id = draft_id,
          app_id = app_id,
          kind = kind,
          created_at_ms = created_at_ms,
          message_count = message_count,
          ready_for_review = ready_for_review,
          summary = summary,
          previewable = previewable,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: DraftSummary): DraftSummary = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<DraftSummary> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
