// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.DraftKind in moumantai/v1/drafts.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int
import kotlin.Suppress

/**
 * ---------------------------------------------------------------------------
 * Enums (used only here)
 * ---------------------------------------------------------------------------
 * Whether a draft edits an existing app or scaffolds a new one.
 */
public enum class DraftKind(
  override val `value`: Int,
) : WireEnum {
  DRAFT_KIND_UNSPECIFIED(0),
  DRAFT_KIND_EDIT(1),
  DRAFT_KIND_NEW_APP(2),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<DraftKind> = object : EnumAdapter<DraftKind>(
      DraftKind::class, 
      PROTO_3, 
      DraftKind.DRAFT_KIND_UNSPECIFIED
    ) {
      override fun fromValue(`value`: Int): DraftKind? = DraftKind.fromValue(`value`)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): DraftKind? = when (`value`) {
      0 -> DRAFT_KIND_UNSPECIFIED
      1 -> DRAFT_KIND_EDIT
      2 -> DRAFT_KIND_NEW_APP
      else -> null
    }
  }
}
