// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.DraftReloadRequest in moumantai/v1/drafts.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Reload preview: run reloadAppModule + broadcast face update to opted-in clients.
 */
public class DraftReloadRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "draftId",
    schemaIndex = 0,
  )
  public val draft_id: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<DraftReloadRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is DraftReloadRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (draft_id != other.draft_id) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + draft_id.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """draft_id=${sanitize(draft_id)}"""
    return result.joinToString(prefix = "DraftReloadRequest{", separator = ", ", postfix = "}")
  }

  public fun copy(draft_id: String = this.draft_id, unknownFields: ByteString = this.unknownFields):
      DraftReloadRequest = DraftReloadRequest(draft_id, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<DraftReloadRequest> = object :
        ProtoAdapter<DraftReloadRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      DraftReloadRequest::class, 
      "type.googleapis.com/moumantai.v1.DraftReloadRequest", 
      PROTO_3, 
      null, 
      "moumantai/v1/drafts.proto"
    ) {
      override fun encodedSize(`value`: DraftReloadRequest): Int {
        var size = value.unknownFields.size
        if (value.draft_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.draft_id)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: DraftReloadRequest) {
        if (value.draft_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.draft_id)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: DraftReloadRequest) {
        writer.writeBytes(value.unknownFields)
        if (value.draft_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.draft_id)
        }
      }

      override fun decode(reader: ProtoReader): DraftReloadRequest {
        var draft_id: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> draft_id = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return DraftReloadRequest(
          draft_id = draft_id,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: DraftReloadRequest): DraftReloadRequest = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<DraftReloadRequest> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
