// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.ErrorMessage in moumantai/v1/lifecycle.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * ---------------------------------------------------------------------------
 * Errors
 * ---------------------------------------------------------------------------
 * Structured error delivered on the control channel.
 */
public class ErrorMessage(
  /**
   * Defined error code; clients switch on this and drive recovery.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.moumantai.protocol.v1.ProtocolErrorCode#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val code: ProtocolErrorCode = ProtocolErrorCode.PROTOCOL_ERROR_CODE_UNSPECIFIED,
  /**
   * Human-readable detail for logs / UI surfacing. Never secrets.
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val message: String = "",
  /**
   * If set, client should retry after this many milliseconds (used with
   * `rate_limited`, `session_busy`).
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    jsonName = "retryAfterMs",
    schemaIndex = 2,
  )
  public val retry_after_ms: Int? = null,
  /**
   * The `client_msg_id` of the offending input, if applicable. Populated on
   * `stale_conversation` so the client can correlate the error back to a
   * specific offline-queue item.
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    jsonName = "clientMsgId",
    schemaIndex = 3,
  )
  public val client_msg_id: String? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<ErrorMessage, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ErrorMessage) return false
    if (unknownFields != other.unknownFields) return false
    if (code != other.code) return false
    if (message != other.message) return false
    if (retry_after_ms != other.retry_after_ms) return false
    if (client_msg_id != other.client_msg_id) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + code.hashCode()
      result = result * 37 + message.hashCode()
      result = result * 37 + (retry_after_ms?.hashCode() ?: 0)
      result = result * 37 + (client_msg_id?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """code=$code"""
    result += """message=${sanitize(message)}"""
    if (retry_after_ms != null) result += """retry_after_ms=$retry_after_ms"""
    if (client_msg_id != null) result += """client_msg_id=${sanitize(client_msg_id)}"""
    return result.joinToString(prefix = "ErrorMessage{", separator = ", ", postfix = "}")
  }

  public fun copy(
    code: ProtocolErrorCode = this.code,
    message: String = this.message,
    retry_after_ms: Int? = this.retry_after_ms,
    client_msg_id: String? = this.client_msg_id,
    unknownFields: ByteString = this.unknownFields,
  ): ErrorMessage = ErrorMessage(code, message, retry_after_ms, client_msg_id, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ErrorMessage> = object : ProtoAdapter<ErrorMessage>(
      FieldEncoding.LENGTH_DELIMITED, 
      ErrorMessage::class, 
      "type.googleapis.com/moumantai.v1.ErrorMessage", 
      PROTO_3, 
      null, 
      "moumantai/v1/lifecycle.proto"
    ) {
      override fun encodedSize(`value`: ErrorMessage): Int {
        var size = value.unknownFields.size
        if (value.code !=
            com.moumantai.protocol.v1.ProtocolErrorCode.PROTOCOL_ERROR_CODE_UNSPECIFIED) {
          size += ProtocolErrorCode.ADAPTER.encodedSizeWithTag(1, value.code)
        }
        if (value.message != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.message)
        }
        size += ProtoAdapter.INT32.encodedSizeWithTag(3, value.retry_after_ms)
        size += ProtoAdapter.STRING.encodedSizeWithTag(4, value.client_msg_id)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ErrorMessage) {
        if (value.code !=
            com.moumantai.protocol.v1.ProtocolErrorCode.PROTOCOL_ERROR_CODE_UNSPECIFIED) {
          ProtocolErrorCode.ADAPTER.encodeWithTag(writer, 1, value.code)
        }
        if (value.message != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.message)
        }
        ProtoAdapter.INT32.encodeWithTag(writer, 3, value.retry_after_ms)
        ProtoAdapter.STRING.encodeWithTag(writer, 4, value.client_msg_id)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ErrorMessage) {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.STRING.encodeWithTag(writer, 4, value.client_msg_id)
        ProtoAdapter.INT32.encodeWithTag(writer, 3, value.retry_after_ms)
        if (value.message != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.message)
        }
        if (value.code !=
            com.moumantai.protocol.v1.ProtocolErrorCode.PROTOCOL_ERROR_CODE_UNSPECIFIED) {
          ProtocolErrorCode.ADAPTER.encodeWithTag(writer, 1, value.code)
        }
      }

      override fun decode(reader: ProtoReader): ErrorMessage {
        var code: ProtocolErrorCode = ProtocolErrorCode.PROTOCOL_ERROR_CODE_UNSPECIFIED
        var message: String = ""
        var retry_after_ms: Int? = null
        var client_msg_id: String? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> try {
              code = ProtocolErrorCode.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            2 -> message = ProtoAdapter.STRING.decode(reader)
            3 -> retry_after_ms = ProtoAdapter.INT32.decode(reader)
            4 -> client_msg_id = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ErrorMessage(
          code = code,
          message = message,
          retry_after_ms = retry_after_ms,
          client_msg_id = client_msg_id,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ErrorMessage): ErrorMessage = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<ErrorMessage> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
