// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.FaceUpdateMsg in moumantai/v1/apps.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.immutableCopyOfStruct
import com.squareup.wire.`internal`.redactElements
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import kotlin.collections.Map
import okio.ByteString

/**
 * ---------------------------------------------------------------------------
 * Face render payload
 * ---------------------------------------------------------------------------
 * Atomic face render payload — components + resolved data.
 * `scope` gates broadcast fan-out: 'home' or 'app:<app_id>'.
 */
public class FaceUpdateMsg(
  /**
   * 'home' or 'app:<app_id>' — scope gate for broadcast fan-out.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val scope: String = "",
  /**
   * Owning app id.
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "appId",
    schemaIndex = 1,
  )
  public val app_id: String = "",
  /**
   * Face id within the app.
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "faceId",
    schemaIndex = 2,
  )
  public val face_id: String = "",
  components: List<ComponentDef> = emptyList(),
  data_: Map<String, *>? = null,
  /**
   * Live vs. draft variant. Unset == LIVE. DRAFT face updates are sent only to
   * clients previewing this app's draft (per-client broadcast routing).
   */
  @field:WireField(
    tag = 6,
    adapter = "com.moumantai.protocol.v1.AppVariant#ADAPTER",
    schemaIndex = 5,
  )
  public val variant: AppVariant? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<FaceUpdateMsg, Nothing>(ADAPTER, unknownFields) {
  /**
   * Component definitions (flat list; the `scaffold` with id="root" is the
   * entry point).
   */
  @field:WireField(
    tag = 4,
    adapter = "com.moumantai.protocol.v1.ComponentDef#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 3,
  )
  public val components: List<ComponentDef> = immutableCopyOf("components", components)

  /**
   * Nested face data model. Components bind via JSON-Pointer (`pathRef`).
   */
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#STRUCT_MAP",
    label = WireField.Label.OMIT_IDENTITY,
    declaredName = "data",
    schemaIndex = 4,
  )
  public val data_: Map<String, *>? = immutableCopyOfStruct("data_", data_)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is FaceUpdateMsg) return false
    if (unknownFields != other.unknownFields) return false
    if (scope != other.scope) return false
    if (app_id != other.app_id) return false
    if (face_id != other.face_id) return false
    if (components != other.components) return false
    if (data_ != other.data_) return false
    if (variant != other.variant) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + scope.hashCode()
      result = result * 37 + app_id.hashCode()
      result = result * 37 + face_id.hashCode()
      result = result * 37 + components.hashCode()
      result = result * 37 + (data_?.hashCode() ?: 0)
      result = result * 37 + (variant?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """scope=${sanitize(scope)}"""
    result += """app_id=${sanitize(app_id)}"""
    result += """face_id=${sanitize(face_id)}"""
    if (components.isNotEmpty()) result += """components=$components"""
    if (data_ != null) result += """data_=$data_"""
    if (variant != null) result += """variant=$variant"""
    return result.joinToString(prefix = "FaceUpdateMsg{", separator = ", ", postfix = "}")
  }

  public fun copy(
    scope: String = this.scope,
    app_id: String = this.app_id,
    face_id: String = this.face_id,
    components: List<ComponentDef> = this.components,
    data_: Map<String, *>? = this.data_,
    variant: AppVariant? = this.variant,
    unknownFields: ByteString = this.unknownFields,
  ): FaceUpdateMsg = FaceUpdateMsg(scope, app_id, face_id, components, data_, variant,
      unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<FaceUpdateMsg> = object : ProtoAdapter<FaceUpdateMsg>(
      FieldEncoding.LENGTH_DELIMITED, 
      FaceUpdateMsg::class, 
      "type.googleapis.com/moumantai.v1.FaceUpdateMsg", 
      PROTO_3, 
      null, 
      "moumantai/v1/apps.proto"
    ) {
      override fun encodedSize(`value`: FaceUpdateMsg): Int {
        var size = value.unknownFields.size
        if (value.scope != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.scope)
        }
        if (value.app_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.app_id)
        }
        if (value.face_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.face_id)
        }
        size += ComponentDef.ADAPTER.asRepeated().encodedSizeWithTag(4, value.components)
        if (value.data_ != null) {
          size += ProtoAdapter.STRUCT_MAP.encodedSizeWithTag(5, value.data_)
        }
        size += AppVariant.ADAPTER.encodedSizeWithTag(6, value.variant)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: FaceUpdateMsg) {
        if (value.scope != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.scope)
        }
        if (value.app_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.app_id)
        }
        if (value.face_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.face_id)
        }
        ComponentDef.ADAPTER.asRepeated().encodeWithTag(writer, 4, value.components)
        if (value.data_ != null) {
          ProtoAdapter.STRUCT_MAP.encodeWithTag(writer, 5, value.data_)
        }
        AppVariant.ADAPTER.encodeWithTag(writer, 6, value.variant)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: FaceUpdateMsg) {
        writer.writeBytes(value.unknownFields)
        AppVariant.ADAPTER.encodeWithTag(writer, 6, value.variant)
        if (value.data_ != null) {
          ProtoAdapter.STRUCT_MAP.encodeWithTag(writer, 5, value.data_)
        }
        ComponentDef.ADAPTER.asRepeated().encodeWithTag(writer, 4, value.components)
        if (value.face_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.face_id)
        }
        if (value.app_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.app_id)
        }
        if (value.scope != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.scope)
        }
      }

      override fun decode(reader: ProtoReader): FaceUpdateMsg {
        var scope: String = ""
        var app_id: String = ""
        var face_id: String = ""
        val components = mutableListOf<ComponentDef>()
        var data_: Map<String, *>? = null
        var variant: AppVariant? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> scope = ProtoAdapter.STRING.decode(reader)
            2 -> app_id = ProtoAdapter.STRING.decode(reader)
            3 -> face_id = ProtoAdapter.STRING.decode(reader)
            4 -> components.add(ComponentDef.ADAPTER.decode(reader))
            5 -> data_ = ProtoAdapter.STRUCT_MAP.decode(reader)
            6 -> try {
              variant = AppVariant.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            else -> reader.readUnknownField(tag)
          }
        }
        return FaceUpdateMsg(
          scope = scope,
          app_id = app_id,
          face_id = face_id,
          components = components,
          data_ = data_,
          variant = variant,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: FaceUpdateMsg): FaceUpdateMsg = value.copy(
        components = value.components.redactElements(ComponentDef.ADAPTER),
        data_ = value.data_?.let(ProtoAdapter.STRUCT_MAP::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<FaceUpdateMsg> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
