// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.FaceListMsg in moumantai/v1/apps.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

/**
 * Server sends the face list when client enters an app or faces change.
 */
public class FaceListMsg(
  /**
   * Owning app id.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "appId",
    schemaIndex = 0,
  )
  public val app_id: String = "",
  faces: List<FaceInfo> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<FaceListMsg, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 2,
    adapter = "com.moumantai.protocol.v1.FaceInfo#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 1,
  )
  public val faces: List<FaceInfo> = immutableCopyOf("faces", faces)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is FaceListMsg) return false
    if (unknownFields != other.unknownFields) return false
    if (app_id != other.app_id) return false
    if (faces != other.faces) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + app_id.hashCode()
      result = result * 37 + faces.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """app_id=${sanitize(app_id)}"""
    if (faces.isNotEmpty()) result += """faces=$faces"""
    return result.joinToString(prefix = "FaceListMsg{", separator = ", ", postfix = "}")
  }

  public fun copy(
    app_id: String = this.app_id,
    faces: List<FaceInfo> = this.faces,
    unknownFields: ByteString = this.unknownFields,
  ): FaceListMsg = FaceListMsg(app_id, faces, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<FaceListMsg> = object : ProtoAdapter<FaceListMsg>(
      FieldEncoding.LENGTH_DELIMITED, 
      FaceListMsg::class, 
      "type.googleapis.com/moumantai.v1.FaceListMsg", 
      PROTO_3, 
      null, 
      "moumantai/v1/apps.proto"
    ) {
      override fun encodedSize(`value`: FaceListMsg): Int {
        var size = value.unknownFields.size
        if (value.app_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.app_id)
        }
        size += FaceInfo.ADAPTER.asRepeated().encodedSizeWithTag(2, value.faces)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: FaceListMsg) {
        if (value.app_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.app_id)
        }
        FaceInfo.ADAPTER.asRepeated().encodeWithTag(writer, 2, value.faces)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: FaceListMsg) {
        writer.writeBytes(value.unknownFields)
        FaceInfo.ADAPTER.asRepeated().encodeWithTag(writer, 2, value.faces)
        if (value.app_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.app_id)
        }
      }

      override fun decode(reader: ProtoReader): FaceListMsg {
        var app_id: String = ""
        val faces = mutableListOf<FaceInfo>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> app_id = ProtoAdapter.STRING.decode(reader)
            2 -> faces.add(FaceInfo.ADAPTER.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return FaceListMsg(
          app_id = app_id,
          faces = faces,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: FaceListMsg): FaceListMsg = value.copy(
        faces = value.faces.redactElements(FaceInfo.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<FaceListMsg> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
