// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.ImageChunkHeader in moumantai/v1/chat.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Per-image metadata in the header of an Image binary frame;
 * payload bytes follow immediately after.
 */
public class ImageChunkHeader(
  /**
   * 'home' or 'app:<app_id>'.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val scope: String = "",
  /**
   * MIME type of the upload — free-form string, e.g. "image/jpeg",
   * "image/png", "image/webp". Empty / unset is treated as unknown.
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "mimeType",
    schemaIndex = 1,
  )
  public val mime_type: String = "",
  /**
   * Client-generated UUID for idempotent retries.
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    jsonName = "clientMsgId",
    schemaIndex = 2,
  )
  public val client_msg_id: String? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<ImageChunkHeader, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ImageChunkHeader) return false
    if (unknownFields != other.unknownFields) return false
    if (scope != other.scope) return false
    if (mime_type != other.mime_type) return false
    if (client_msg_id != other.client_msg_id) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + scope.hashCode()
      result = result * 37 + mime_type.hashCode()
      result = result * 37 + (client_msg_id?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """scope=${sanitize(scope)}"""
    result += """mime_type=${sanitize(mime_type)}"""
    if (client_msg_id != null) result += """client_msg_id=${sanitize(client_msg_id)}"""
    return result.joinToString(prefix = "ImageChunkHeader{", separator = ", ", postfix = "}")
  }

  public fun copy(
    scope: String = this.scope,
    mime_type: String = this.mime_type,
    client_msg_id: String? = this.client_msg_id,
    unknownFields: ByteString = this.unknownFields,
  ): ImageChunkHeader = ImageChunkHeader(scope, mime_type, client_msg_id, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ImageChunkHeader> = object : ProtoAdapter<ImageChunkHeader>(
      FieldEncoding.LENGTH_DELIMITED, 
      ImageChunkHeader::class, 
      "type.googleapis.com/moumantai.v1.ImageChunkHeader", 
      PROTO_3, 
      null, 
      "moumantai/v1/chat.proto"
    ) {
      override fun encodedSize(`value`: ImageChunkHeader): Int {
        var size = value.unknownFields.size
        if (value.scope != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.scope)
        }
        if (value.mime_type != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.mime_type)
        }
        size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.client_msg_id)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ImageChunkHeader) {
        if (value.scope != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.scope)
        }
        if (value.mime_type != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.mime_type)
        }
        ProtoAdapter.STRING.encodeWithTag(writer, 3, value.client_msg_id)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ImageChunkHeader) {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.STRING.encodeWithTag(writer, 3, value.client_msg_id)
        if (value.mime_type != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.mime_type)
        }
        if (value.scope != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.scope)
        }
      }

      override fun decode(reader: ProtoReader): ImageChunkHeader {
        var scope: String = ""
        var mime_type: String = ""
        var client_msg_id: String? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> scope = ProtoAdapter.STRING.decode(reader)
            2 -> mime_type = ProtoAdapter.STRING.decode(reader)
            3 -> client_msg_id = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ImageChunkHeader(
          scope = scope,
          mime_type = mime_type,
          client_msg_id = client_msg_id,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ImageChunkHeader): ImageChunkHeader = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<ImageChunkHeader> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
