// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.ListComponent in moumantai/v1/components.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Scrollable data-driven list. Each row clones the template against one array element.
 */
public class ListComponent(
  /**
   * Children binding.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.moumantai.protocol.v1.ListChildren#ADAPTER",
    schemaIndex = 0,
  )
  public val children: ListChildren? = null,
  @field:WireField(
    tag = 200,
    adapter = "com.moumantai.protocol.v1.Modifier#ADAPTER",
    schemaIndex = 1,
  )
  public val modifier: Modifier? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<ListComponent, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ListComponent) return false
    if (unknownFields != other.unknownFields) return false
    if (children != other.children) return false
    if (modifier != other.modifier) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (children?.hashCode() ?: 0)
      result = result * 37 + (modifier?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (children != null) result += """children=$children"""
    if (modifier != null) result += """modifier=$modifier"""
    return result.joinToString(prefix = "ListComponent{", separator = ", ", postfix = "}")
  }

  public fun copy(
    children: ListChildren? = this.children,
    modifier: Modifier? = this.modifier,
    unknownFields: ByteString = this.unknownFields,
  ): ListComponent = ListComponent(children, modifier, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ListComponent> = object : ProtoAdapter<ListComponent>(
      FieldEncoding.LENGTH_DELIMITED, 
      ListComponent::class, 
      "type.googleapis.com/moumantai.v1.ListComponent", 
      PROTO_3, 
      null, 
      "moumantai/v1/components.proto"
    ) {
      override fun encodedSize(`value`: ListComponent): Int {
        var size = value.unknownFields.size
        size += ListChildren.ADAPTER.encodedSizeWithTag(1, value.children)
        size += Modifier.ADAPTER.encodedSizeWithTag(200, value.modifier)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ListComponent) {
        ListChildren.ADAPTER.encodeWithTag(writer, 1, value.children)
        Modifier.ADAPTER.encodeWithTag(writer, 200, value.modifier)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ListComponent) {
        writer.writeBytes(value.unknownFields)
        Modifier.ADAPTER.encodeWithTag(writer, 200, value.modifier)
        ListChildren.ADAPTER.encodeWithTag(writer, 1, value.children)
      }

      override fun decode(reader: ProtoReader): ListComponent {
        var children: ListChildren? = null
        var modifier: Modifier? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> children = ListChildren.ADAPTER.decode(reader)
            200 -> modifier = Modifier.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ListComponent(
          children = children,
          modifier = modifier,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ListComponent): ListComponent = value.copy(
        children = value.children?.let(ListChildren.ADAPTER::redact),
        modifier = value.modifier?.let(Modifier.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<ListComponent> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
