// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.ListItemComponent in moumantai/v1/components.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * One row in a List.
 */
public class ListItemComponent(
  /**
   * Primary headline (may be path-resolved).
   */
  @field:WireField(
    tag = 1,
    adapter = "com.moumantai.protocol.v1.DynamicString#ADAPTER",
    schemaIndex = 0,
  )
  public val headline: DynamicString? = null,
  /**
   * Supporting line below the headline.
   */
  @field:WireField(
    tag = 2,
    adapter = "com.moumantai.protocol.v1.DynamicString#ADAPTER",
    schemaIndex = 1,
  )
  public val supporting: DynamicString? = null,
  /**
   * Leading icon name.
   */
  @field:WireField(
    tag = 3,
    adapter = "com.moumantai.protocol.v1.DynamicString#ADAPTER",
    jsonName = "leadingIcon",
    schemaIndex = 2,
  )
  public val leading_icon: DynamicString? = null,
  /**
   * Component id rendered as the trailing slot (e.g. a Switch or a Button).
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    jsonName = "trailingContent",
    schemaIndex = 3,
  )
  public val trailing_content: String? = null,
  /**
   * Tap action.
   */
  @field:WireField(
    tag = 5,
    adapter = "com.moumantai.protocol.v1.Action#ADAPTER",
    schemaIndex = 4,
  )
  public val action: Action? = null,
  @field:WireField(
    tag = 200,
    adapter = "com.moumantai.protocol.v1.Modifier#ADAPTER",
    schemaIndex = 5,
  )
  public val modifier: Modifier? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<ListItemComponent, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ListItemComponent) return false
    if (unknownFields != other.unknownFields) return false
    if (headline != other.headline) return false
    if (supporting != other.supporting) return false
    if (leading_icon != other.leading_icon) return false
    if (trailing_content != other.trailing_content) return false
    if (action != other.action) return false
    if (modifier != other.modifier) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (headline?.hashCode() ?: 0)
      result = result * 37 + (supporting?.hashCode() ?: 0)
      result = result * 37 + (leading_icon?.hashCode() ?: 0)
      result = result * 37 + (trailing_content?.hashCode() ?: 0)
      result = result * 37 + (action?.hashCode() ?: 0)
      result = result * 37 + (modifier?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (headline != null) result += """headline=$headline"""
    if (supporting != null) result += """supporting=$supporting"""
    if (leading_icon != null) result += """leading_icon=$leading_icon"""
    if (trailing_content != null) result += """trailing_content=${sanitize(trailing_content)}"""
    if (action != null) result += """action=$action"""
    if (modifier != null) result += """modifier=$modifier"""
    return result.joinToString(prefix = "ListItemComponent{", separator = ", ", postfix = "}")
  }

  public fun copy(
    headline: DynamicString? = this.headline,
    supporting: DynamicString? = this.supporting,
    leading_icon: DynamicString? = this.leading_icon,
    trailing_content: String? = this.trailing_content,
    action: Action? = this.action,
    modifier: Modifier? = this.modifier,
    unknownFields: ByteString = this.unknownFields,
  ): ListItemComponent = ListItemComponent(headline, supporting, leading_icon, trailing_content,
      action, modifier, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ListItemComponent> = object : ProtoAdapter<ListItemComponent>(
      FieldEncoding.LENGTH_DELIMITED, 
      ListItemComponent::class, 
      "type.googleapis.com/moumantai.v1.ListItemComponent", 
      PROTO_3, 
      null, 
      "moumantai/v1/components.proto"
    ) {
      override fun encodedSize(`value`: ListItemComponent): Int {
        var size = value.unknownFields.size
        size += DynamicString.ADAPTER.encodedSizeWithTag(1, value.headline)
        size += DynamicString.ADAPTER.encodedSizeWithTag(2, value.supporting)
        size += DynamicString.ADAPTER.encodedSizeWithTag(3, value.leading_icon)
        size += ProtoAdapter.STRING.encodedSizeWithTag(4, value.trailing_content)
        size += Action.ADAPTER.encodedSizeWithTag(5, value.action)
        size += Modifier.ADAPTER.encodedSizeWithTag(200, value.modifier)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ListItemComponent) {
        DynamicString.ADAPTER.encodeWithTag(writer, 1, value.headline)
        DynamicString.ADAPTER.encodeWithTag(writer, 2, value.supporting)
        DynamicString.ADAPTER.encodeWithTag(writer, 3, value.leading_icon)
        ProtoAdapter.STRING.encodeWithTag(writer, 4, value.trailing_content)
        Action.ADAPTER.encodeWithTag(writer, 5, value.action)
        Modifier.ADAPTER.encodeWithTag(writer, 200, value.modifier)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ListItemComponent) {
        writer.writeBytes(value.unknownFields)
        Modifier.ADAPTER.encodeWithTag(writer, 200, value.modifier)
        Action.ADAPTER.encodeWithTag(writer, 5, value.action)
        ProtoAdapter.STRING.encodeWithTag(writer, 4, value.trailing_content)
        DynamicString.ADAPTER.encodeWithTag(writer, 3, value.leading_icon)
        DynamicString.ADAPTER.encodeWithTag(writer, 2, value.supporting)
        DynamicString.ADAPTER.encodeWithTag(writer, 1, value.headline)
      }

      override fun decode(reader: ProtoReader): ListItemComponent {
        var headline: DynamicString? = null
        var supporting: DynamicString? = null
        var leading_icon: DynamicString? = null
        var trailing_content: String? = null
        var action: Action? = null
        var modifier: Modifier? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> headline = DynamicString.ADAPTER.decode(reader)
            2 -> supporting = DynamicString.ADAPTER.decode(reader)
            3 -> leading_icon = DynamicString.ADAPTER.decode(reader)
            4 -> trailing_content = ProtoAdapter.STRING.decode(reader)
            5 -> action = Action.ADAPTER.decode(reader)
            200 -> modifier = Modifier.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ListItemComponent(
          headline = headline,
          supporting = supporting,
          leading_icon = leading_icon,
          trailing_content = trailing_content,
          action = action,
          modifier = modifier,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ListItemComponent): ListItemComponent = value.copy(
        headline = value.headline?.let(DynamicString.ADAPTER::redact),
        supporting = value.supporting?.let(DynamicString.ADAPTER::redact),
        leading_icon = value.leading_icon?.let(DynamicString.ADAPTER::redact),
        action = value.action?.let(Action.ADAPTER::redact),
        modifier = value.modifier?.let(Modifier.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<ListItemComponent> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
