// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.ListChildren in moumantai/v1/components.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * ---------------------------------------------------------------------------
 * Data
 * ---------------------------------------------------------------------------
 * Binds a data-model array path to a per-item template component.
 */
public class ListChildren(
  /**
   * JSON-Pointer path into the face data model resolving to an array.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val path: String = "",
  /**
   * Component id of the per-item template; the renderer instantiates one
   * copy per array element with the element scoped under the template's
   * `pathRef('$.field')` lookups.
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "componentId",
    schemaIndex = 1,
  )
  public val component_id: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<ListChildren, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ListChildren) return false
    if (unknownFields != other.unknownFields) return false
    if (path != other.path) return false
    if (component_id != other.component_id) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + path.hashCode()
      result = result * 37 + component_id.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """path=${sanitize(path)}"""
    result += """component_id=${sanitize(component_id)}"""
    return result.joinToString(prefix = "ListChildren{", separator = ", ", postfix = "}")
  }

  public fun copy(
    path: String = this.path,
    component_id: String = this.component_id,
    unknownFields: ByteString = this.unknownFields,
  ): ListChildren = ListChildren(path, component_id, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ListChildren> = object : ProtoAdapter<ListChildren>(
      FieldEncoding.LENGTH_DELIMITED, 
      ListChildren::class, 
      "type.googleapis.com/moumantai.v1.ListChildren", 
      PROTO_3, 
      null, 
      "moumantai/v1/components.proto"
    ) {
      override fun encodedSize(`value`: ListChildren): Int {
        var size = value.unknownFields.size
        if (value.path != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.path)
        }
        if (value.component_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.component_id)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ListChildren) {
        if (value.path != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.path)
        }
        if (value.component_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.component_id)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ListChildren) {
        writer.writeBytes(value.unknownFields)
        if (value.component_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.component_id)
        }
        if (value.path != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.path)
        }
      }

      override fun decode(reader: ProtoReader): ListChildren {
        var path: String = ""
        var component_id: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> path = ProtoAdapter.STRING.decode(reader)
            2 -> component_id = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ListChildren(
          path = path,
          component_id = component_id,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ListChildren): ListChildren = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<ListChildren> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
