// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.PreviewOptInRequest in moumantai/v1/drafts.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * ---------------------------------------------------------------------------
 * Client → server
 * ---------------------------------------------------------------------------
 * Opt this client into / out of previewing a draft.
 */
public class PreviewOptInRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "draftId",
    schemaIndex = 0,
  )
  public val draft_id: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "optIn",
    schemaIndex = 1,
  )
  public val opt_in: Boolean = false,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<PreviewOptInRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is PreviewOptInRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (draft_id != other.draft_id) return false
    if (opt_in != other.opt_in) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + draft_id.hashCode()
      result = result * 37 + opt_in.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """draft_id=${sanitize(draft_id)}"""
    result += """opt_in=$opt_in"""
    return result.joinToString(prefix = "PreviewOptInRequest{", separator = ", ", postfix = "}")
  }

  public fun copy(
    draft_id: String = this.draft_id,
    opt_in: Boolean = this.opt_in,
    unknownFields: ByteString = this.unknownFields,
  ): PreviewOptInRequest = PreviewOptInRequest(draft_id, opt_in, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<PreviewOptInRequest> = object :
        ProtoAdapter<PreviewOptInRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      PreviewOptInRequest::class, 
      "type.googleapis.com/moumantai.v1.PreviewOptInRequest", 
      PROTO_3, 
      null, 
      "moumantai/v1/drafts.proto"
    ) {
      override fun encodedSize(`value`: PreviewOptInRequest): Int {
        var size = value.unknownFields.size
        if (value.draft_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.draft_id)
        }
        if (value.opt_in != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(2, value.opt_in)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: PreviewOptInRequest) {
        if (value.draft_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.draft_id)
        }
        if (value.opt_in != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 2, value.opt_in)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: PreviewOptInRequest) {
        writer.writeBytes(value.unknownFields)
        if (value.opt_in != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 2, value.opt_in)
        }
        if (value.draft_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.draft_id)
        }
      }

      override fun decode(reader: ProtoReader): PreviewOptInRequest {
        var draft_id: String = ""
        var opt_in: Boolean = false
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> draft_id = ProtoAdapter.STRING.decode(reader)
            2 -> opt_in = ProtoAdapter.BOOL.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return PreviewOptInRequest(
          draft_id = draft_id,
          opt_in = opt_in,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: PreviewOptInRequest): PreviewOptInRequest = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<PreviewOptInRequest> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
