// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.ProtocolErrorCode in moumantai/v1/enums.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int
import kotlin.Suppress

/**
 * ---------------------------------------------------------------------------
 * Errors
 * ---------------------------------------------------------------------------
 * Defined protocol error codes. Every code has a matching close code in `CloseCode`.
 */
public enum class ProtocolErrorCode(
  override val `value`: Int,
) : WireEnum {
  PROTOCOL_ERROR_CODE_UNSPECIFIED(0),
  /**
   * Client sent a non-hello frame for a sessionId the server doesn't know.
   */
  PROTOCOL_ERROR_CODE_UNKNOWN_SESSION(1),
  /**
   * A second socket tried to bind the same sessionId.
   */
  PROTOCOL_ERROR_CODE_SESSION_IN_USE(2),
  /**
   * Inbound audio exceeded per-session size or rate limits.
   */
  PROTOCOL_ERROR_CODE_AUDIO_OVERFLOW(3),
  /**
   * Too many user turns / binary frames per unit time.
   */
  PROTOCOL_ERROR_CODE_RATE_LIMITED(4),
  /**
   * Server is currently processing the maximum queued turns for this session.
   */
  PROTOCOL_ERROR_CODE_SESSION_BUSY(5),
  /**
   * Frame size / component count exceeded server caps.
   */
  PROTOCOL_ERROR_CODE_FRAME_TOO_LARGE(6),
  /**
   * `originConversationId` no longer matches the server's active conversation.
   */
  PROTOCOL_ERROR_CODE_STALE_CONVERSATION(7),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ProtocolErrorCode> = object : EnumAdapter<ProtocolErrorCode>(
      ProtocolErrorCode::class, 
      PROTO_3, 
      ProtocolErrorCode.PROTOCOL_ERROR_CODE_UNSPECIFIED
    ) {
      override fun fromValue(`value`: Int): ProtocolErrorCode? =
          ProtocolErrorCode.fromValue(`value`)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): ProtocolErrorCode? = when (`value`) {
      0 -> PROTOCOL_ERROR_CODE_UNSPECIFIED
      1 -> PROTOCOL_ERROR_CODE_UNKNOWN_SESSION
      2 -> PROTOCOL_ERROR_CODE_SESSION_IN_USE
      3 -> PROTOCOL_ERROR_CODE_AUDIO_OVERFLOW
      4 -> PROTOCOL_ERROR_CODE_RATE_LIMITED
      5 -> PROTOCOL_ERROR_CODE_SESSION_BUSY
      6 -> PROTOCOL_ERROR_CODE_FRAME_TOO_LARGE
      7 -> PROTOCOL_ERROR_CODE_STALE_CONVERSATION
      else -> null
    }
  }
}
