// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.SelectOptionList in moumantai/v1/components.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

public class SelectOptionList(
  options: List<SelectOption> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<SelectOptionList, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 1,
    adapter = "com.moumantai.protocol.v1.SelectOption#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 0,
  )
  public val options: List<SelectOption> = immutableCopyOf("options", options)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is SelectOptionList) return false
    if (unknownFields != other.unknownFields) return false
    if (options != other.options) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + options.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (options.isNotEmpty()) result += """options=$options"""
    return result.joinToString(prefix = "SelectOptionList{", separator = ", ", postfix = "}")
  }

  public fun copy(options: List<SelectOption> = this.options, unknownFields: ByteString =
      this.unknownFields): SelectOptionList = SelectOptionList(options, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<SelectOptionList> = object : ProtoAdapter<SelectOptionList>(
      FieldEncoding.LENGTH_DELIMITED, 
      SelectOptionList::class, 
      "type.googleapis.com/moumantai.v1.SelectOptionList", 
      PROTO_3, 
      null, 
      "moumantai/v1/components.proto"
    ) {
      override fun encodedSize(`value`: SelectOptionList): Int {
        var size = value.unknownFields.size
        size += SelectOption.ADAPTER.asRepeated().encodedSizeWithTag(1, value.options)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: SelectOptionList) {
        SelectOption.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.options)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: SelectOptionList) {
        writer.writeBytes(value.unknownFields)
        SelectOption.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.options)
      }

      override fun decode(reader: ProtoReader): SelectOptionList {
        val options = mutableListOf<SelectOption>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> options.add(SelectOption.ADAPTER.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return SelectOptionList(
          options = options,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: SelectOptionList): SelectOptionList = value.copy(
        options = value.options.redactElements(SelectOption.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<SelectOptionList> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
