// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.SelectComponent in moumantai/v1/components.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Pick one option from a list.
 */
public class SelectComponent(
  /**
   * Currently-selected value (path-resolved).
   */
  @field:WireField(
    tag = 1,
    adapter = "com.moumantai.protocol.v1.DynamicString#ADAPTER",
    declaredName = "value",
    schemaIndex = 0,
  )
  public val value_: DynamicString? = null,
  /**
   * Floating label.
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 1,
  )
  public val label: String? = null,
  /**
   * Either an inline list of options or a path to one in the data model.
   */
  @field:WireField(
    tag = 3,
    adapter = "com.moumantai.protocol.v1.SelectOptions#ADAPTER",
    schemaIndex = 2,
  )
  public val options: SelectOptions? = null,
  /**
   * Selection-change action.
   */
  @field:WireField(
    tag = 4,
    adapter = "com.moumantai.protocol.v1.Action#ADAPTER",
    schemaIndex = 3,
  )
  public val action: Action? = null,
  @field:WireField(
    tag = 200,
    adapter = "com.moumantai.protocol.v1.Modifier#ADAPTER",
    schemaIndex = 4,
  )
  public val modifier: Modifier? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<SelectComponent, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is SelectComponent) return false
    if (unknownFields != other.unknownFields) return false
    if (value_ != other.value_) return false
    if (label != other.label) return false
    if (options != other.options) return false
    if (action != other.action) return false
    if (modifier != other.modifier) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (value_?.hashCode() ?: 0)
      result = result * 37 + (label?.hashCode() ?: 0)
      result = result * 37 + (options?.hashCode() ?: 0)
      result = result * 37 + (action?.hashCode() ?: 0)
      result = result * 37 + (modifier?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (value_ != null) result += """value_=$value_"""
    if (label != null) result += """label=${sanitize(label)}"""
    if (options != null) result += """options=$options"""
    if (action != null) result += """action=$action"""
    if (modifier != null) result += """modifier=$modifier"""
    return result.joinToString(prefix = "SelectComponent{", separator = ", ", postfix = "}")
  }

  public fun copy(
    value_: DynamicString? = this.value_,
    label: String? = this.label,
    options: SelectOptions? = this.options,
    action: Action? = this.action,
    modifier: Modifier? = this.modifier,
    unknownFields: ByteString = this.unknownFields,
  ): SelectComponent = SelectComponent(value_, label, options, action, modifier, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<SelectComponent> = object : ProtoAdapter<SelectComponent>(
      FieldEncoding.LENGTH_DELIMITED, 
      SelectComponent::class, 
      "type.googleapis.com/moumantai.v1.SelectComponent", 
      PROTO_3, 
      null, 
      "moumantai/v1/components.proto"
    ) {
      override fun encodedSize(`value`: SelectComponent): Int {
        var size = value.unknownFields.size
        size += DynamicString.ADAPTER.encodedSizeWithTag(1, value.value_)
        size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.label)
        size += SelectOptions.ADAPTER.encodedSizeWithTag(3, value.options)
        size += Action.ADAPTER.encodedSizeWithTag(4, value.action)
        size += Modifier.ADAPTER.encodedSizeWithTag(200, value.modifier)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: SelectComponent) {
        DynamicString.ADAPTER.encodeWithTag(writer, 1, value.value_)
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.label)
        SelectOptions.ADAPTER.encodeWithTag(writer, 3, value.options)
        Action.ADAPTER.encodeWithTag(writer, 4, value.action)
        Modifier.ADAPTER.encodeWithTag(writer, 200, value.modifier)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: SelectComponent) {
        writer.writeBytes(value.unknownFields)
        Modifier.ADAPTER.encodeWithTag(writer, 200, value.modifier)
        Action.ADAPTER.encodeWithTag(writer, 4, value.action)
        SelectOptions.ADAPTER.encodeWithTag(writer, 3, value.options)
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.label)
        DynamicString.ADAPTER.encodeWithTag(writer, 1, value.value_)
      }

      override fun decode(reader: ProtoReader): SelectComponent {
        var value_: DynamicString? = null
        var label: String? = null
        var options: SelectOptions? = null
        var action: Action? = null
        var modifier: Modifier? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> value_ = DynamicString.ADAPTER.decode(reader)
            2 -> label = ProtoAdapter.STRING.decode(reader)
            3 -> options = SelectOptions.ADAPTER.decode(reader)
            4 -> action = Action.ADAPTER.decode(reader)
            200 -> modifier = Modifier.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return SelectComponent(
          value_ = value_,
          label = label,
          options = options,
          action = action,
          modifier = modifier,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: SelectComponent): SelectComponent = value.copy(
        value_ = value.value_?.let(DynamicString.ADAPTER::redact),
        options = value.options?.let(SelectOptions.ADAPTER::redact),
        action = value.action?.let(Action.ADAPTER::redact),
        modifier = value.modifier?.let(Modifier.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<SelectComponent> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
