// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.ServerHello in moumantai/v1/lifecycle.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Server response confirming the session.
 */
public class ServerHello(
  /**
   * Routing handle for this WebSocket; refreshed on every connect.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "sessionId",
    schemaIndex = 0,
  )
  public val session_id: String = "",
  /**
   * Server-side dev-mode gate (MOUMANTAI_DEV_MODE). The PWA shows dev/draft
   * surfaces only when true AND the client opts in via localStorage.
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    jsonName = "devModeEnabled",
    schemaIndex = 1,
  )
  public val dev_mode_enabled: Boolean? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<ServerHello, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ServerHello) return false
    if (unknownFields != other.unknownFields) return false
    if (session_id != other.session_id) return false
    if (dev_mode_enabled != other.dev_mode_enabled) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + session_id.hashCode()
      result = result * 37 + (dev_mode_enabled?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """session_id=${sanitize(session_id)}"""
    if (dev_mode_enabled != null) result += """dev_mode_enabled=$dev_mode_enabled"""
    return result.joinToString(prefix = "ServerHello{", separator = ", ", postfix = "}")
  }

  public fun copy(
    session_id: String = this.session_id,
    dev_mode_enabled: Boolean? = this.dev_mode_enabled,
    unknownFields: ByteString = this.unknownFields,
  ): ServerHello = ServerHello(session_id, dev_mode_enabled, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ServerHello> = object : ProtoAdapter<ServerHello>(
      FieldEncoding.LENGTH_DELIMITED, 
      ServerHello::class, 
      "type.googleapis.com/moumantai.v1.ServerHello", 
      PROTO_3, 
      null, 
      "moumantai/v1/lifecycle.proto"
    ) {
      override fun encodedSize(`value`: ServerHello): Int {
        var size = value.unknownFields.size
        if (value.session_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.session_id)
        }
        size += ProtoAdapter.BOOL.encodedSizeWithTag(2, value.dev_mode_enabled)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ServerHello) {
        if (value.session_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.session_id)
        }
        ProtoAdapter.BOOL.encodeWithTag(writer, 2, value.dev_mode_enabled)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ServerHello) {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.BOOL.encodeWithTag(writer, 2, value.dev_mode_enabled)
        if (value.session_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.session_id)
        }
      }

      override fun decode(reader: ProtoReader): ServerHello {
        var session_id: String = ""
        var dev_mode_enabled: Boolean? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> session_id = ProtoAdapter.STRING.decode(reader)
            2 -> dev_mode_enabled = ProtoAdapter.BOOL.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ServerHello(
          session_id = session_id,
          dev_mode_enabled = dev_mode_enabled,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ServerHello): ServerHello = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<ServerHello> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
