// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.TextFieldComponent in moumantai/v1/components.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * ---------------------------------------------------------------------------
 * Input
 * ---------------------------------------------------------------------------
 * Text input field.
 */
public class TextFieldComponent(
  /**
   * Current value (path-resolved binding).
   */
  @field:WireField(
    tag = 1,
    adapter = "com.moumantai.protocol.v1.DynamicString#ADAPTER",
    declaredName = "value",
    schemaIndex = 0,
  )
  public val value_: DynamicString? = null,
  /**
   * Floating label.
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 1,
  )
  public val label: String? = null,
  /**
   * Placeholder shown when empty.
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 2,
  )
  public val placeholder: String? = null,
  /**
   * Soft-keyboard hint.
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    jsonName = "keyboardType",
    schemaIndex = 3,
  )
  public val keyboard_type: String? = null,
  /**
   * Multi-line text input. When true, the renderer presents a multi-line
   * textarea-style field (typically with a larger min-height).
   */
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    schemaIndex = 4,
  )
  public val multiline: Boolean? = null,
  @field:WireField(
    tag = 200,
    adapter = "com.moumantai.protocol.v1.Modifier#ADAPTER",
    schemaIndex = 5,
  )
  public val modifier: Modifier? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<TextFieldComponent, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is TextFieldComponent) return false
    if (unknownFields != other.unknownFields) return false
    if (value_ != other.value_) return false
    if (label != other.label) return false
    if (placeholder != other.placeholder) return false
    if (keyboard_type != other.keyboard_type) return false
    if (multiline != other.multiline) return false
    if (modifier != other.modifier) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (value_?.hashCode() ?: 0)
      result = result * 37 + (label?.hashCode() ?: 0)
      result = result * 37 + (placeholder?.hashCode() ?: 0)
      result = result * 37 + (keyboard_type?.hashCode() ?: 0)
      result = result * 37 + (multiline?.hashCode() ?: 0)
      result = result * 37 + (modifier?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (value_ != null) result += """value_=$value_"""
    if (label != null) result += """label=${sanitize(label)}"""
    if (placeholder != null) result += """placeholder=${sanitize(placeholder)}"""
    if (keyboard_type != null) result += """keyboard_type=${sanitize(keyboard_type)}"""
    if (multiline != null) result += """multiline=$multiline"""
    if (modifier != null) result += """modifier=$modifier"""
    return result.joinToString(prefix = "TextFieldComponent{", separator = ", ", postfix = "}")
  }

  public fun copy(
    value_: DynamicString? = this.value_,
    label: String? = this.label,
    placeholder: String? = this.placeholder,
    keyboard_type: String? = this.keyboard_type,
    multiline: Boolean? = this.multiline,
    modifier: Modifier? = this.modifier,
    unknownFields: ByteString = this.unknownFields,
  ): TextFieldComponent = TextFieldComponent(value_, label, placeholder, keyboard_type, multiline,
      modifier, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<TextFieldComponent> = object :
        ProtoAdapter<TextFieldComponent>(
      FieldEncoding.LENGTH_DELIMITED, 
      TextFieldComponent::class, 
      "type.googleapis.com/moumantai.v1.TextFieldComponent", 
      PROTO_3, 
      null, 
      "moumantai/v1/components.proto"
    ) {
      override fun encodedSize(`value`: TextFieldComponent): Int {
        var size = value.unknownFields.size
        size += DynamicString.ADAPTER.encodedSizeWithTag(1, value.value_)
        size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.label)
        size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.placeholder)
        size += ProtoAdapter.STRING.encodedSizeWithTag(4, value.keyboard_type)
        size += ProtoAdapter.BOOL.encodedSizeWithTag(5, value.multiline)
        size += Modifier.ADAPTER.encodedSizeWithTag(200, value.modifier)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: TextFieldComponent) {
        DynamicString.ADAPTER.encodeWithTag(writer, 1, value.value_)
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.label)
        ProtoAdapter.STRING.encodeWithTag(writer, 3, value.placeholder)
        ProtoAdapter.STRING.encodeWithTag(writer, 4, value.keyboard_type)
        ProtoAdapter.BOOL.encodeWithTag(writer, 5, value.multiline)
        Modifier.ADAPTER.encodeWithTag(writer, 200, value.modifier)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: TextFieldComponent) {
        writer.writeBytes(value.unknownFields)
        Modifier.ADAPTER.encodeWithTag(writer, 200, value.modifier)
        ProtoAdapter.BOOL.encodeWithTag(writer, 5, value.multiline)
        ProtoAdapter.STRING.encodeWithTag(writer, 4, value.keyboard_type)
        ProtoAdapter.STRING.encodeWithTag(writer, 3, value.placeholder)
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.label)
        DynamicString.ADAPTER.encodeWithTag(writer, 1, value.value_)
      }

      override fun decode(reader: ProtoReader): TextFieldComponent {
        var value_: DynamicString? = null
        var label: String? = null
        var placeholder: String? = null
        var keyboard_type: String? = null
        var multiline: Boolean? = null
        var modifier: Modifier? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> value_ = DynamicString.ADAPTER.decode(reader)
            2 -> label = ProtoAdapter.STRING.decode(reader)
            3 -> placeholder = ProtoAdapter.STRING.decode(reader)
            4 -> keyboard_type = ProtoAdapter.STRING.decode(reader)
            5 -> multiline = ProtoAdapter.BOOL.decode(reader)
            200 -> modifier = Modifier.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return TextFieldComponent(
          value_ = value_,
          label = label,
          placeholder = placeholder,
          keyboard_type = keyboard_type,
          multiline = multiline,
          modifier = modifier,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: TextFieldComponent): TextFieldComponent = value.copy(
        value_ = value.value_?.let(DynamicString.ADAPTER::redact),
        modifier = value.modifier?.let(Modifier.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<TextFieldComponent> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
