// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.TTSRequest in moumantai/v1/chat.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Server → client request to render pre-generated TTS audio.
 */
public class TTSRequest(
  /**
   * Text to synthesize.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val text: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<TTSRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is TTSRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (text != other.text) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + text.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """text=${sanitize(text)}"""
    return result.joinToString(prefix = "TTSRequest{", separator = ", ", postfix = "}")
  }

  public fun copy(text: String = this.text, unknownFields: ByteString = this.unknownFields):
      TTSRequest = TTSRequest(text, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<TTSRequest> = object : ProtoAdapter<TTSRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      TTSRequest::class, 
      "type.googleapis.com/moumantai.v1.TTSRequest", 
      PROTO_3, 
      null, 
      "moumantai/v1/chat.proto"
    ) {
      override fun encodedSize(`value`: TTSRequest): Int {
        var size = value.unknownFields.size
        if (value.text != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.text)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: TTSRequest) {
        if (value.text != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.text)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: TTSRequest) {
        writer.writeBytes(value.unknownFields)
        if (value.text != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.text)
        }
      }

      override fun decode(reader: ProtoReader): TTSRequest {
        var text: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> text = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return TTSRequest(
          text = text,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: TTSRequest): TTSRequest = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<TTSRequest> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
