// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.VoiceState in moumantai/v1/chat.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * ---------------------------------------------------------------------------
 * Voice + audio
 * ---------------------------------------------------------------------------
 * Current voice pipeline state.
 */
public class VoiceState(
  /**
   * Current state machine value.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.moumantai.protocol.v1.VoiceStateValue#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val state: VoiceStateValue = VoiceStateValue.VOICE_STATE_VALUE_UNSPECIFIED,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<VoiceState, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is VoiceState) return false
    if (unknownFields != other.unknownFields) return false
    if (state != other.state) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + state.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """state=$state"""
    return result.joinToString(prefix = "VoiceState{", separator = ", ", postfix = "}")
  }

  public fun copy(state: VoiceStateValue = this.state, unknownFields: ByteString =
      this.unknownFields): VoiceState = VoiceState(state, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<VoiceState> = object : ProtoAdapter<VoiceState>(
      FieldEncoding.LENGTH_DELIMITED, 
      VoiceState::class, 
      "type.googleapis.com/moumantai.v1.VoiceState", 
      PROTO_3, 
      null, 
      "moumantai/v1/chat.proto"
    ) {
      override fun encodedSize(`value`: VoiceState): Int {
        var size = value.unknownFields.size
        if (value.state !=
            com.moumantai.protocol.v1.VoiceStateValue.VOICE_STATE_VALUE_UNSPECIFIED) {
          size += VoiceStateValue.ADAPTER.encodedSizeWithTag(1, value.state)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: VoiceState) {
        if (value.state !=
            com.moumantai.protocol.v1.VoiceStateValue.VOICE_STATE_VALUE_UNSPECIFIED) {
          VoiceStateValue.ADAPTER.encodeWithTag(writer, 1, value.state)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: VoiceState) {
        writer.writeBytes(value.unknownFields)
        if (value.state !=
            com.moumantai.protocol.v1.VoiceStateValue.VOICE_STATE_VALUE_UNSPECIFIED) {
          VoiceStateValue.ADAPTER.encodeWithTag(writer, 1, value.state)
        }
      }

      override fun decode(reader: ProtoReader): VoiceState {
        var state: VoiceStateValue = VoiceStateValue.VOICE_STATE_VALUE_UNSPECIFIED
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> try {
              state = VoiceStateValue.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            else -> reader.readUnknownField(tag)
          }
        }
        return VoiceState(
          state = state,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: VoiceState): VoiceState = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<VoiceState> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
