#!/usr/bin/env python3
"""Generate language bindings from `shared/protocol/proto/`.

SSOT: `shared/protocol/proto/moumantai/v1/*.proto`. Invokes:
  1. buf generate           — protobuf-es → TypeScript
  2. nanopb_generator       — *.proto → C (.pb.h / .pb.c)
  3. ./gradlew generateProtos — Square Wire → Kotlin (android)
  4. ./gradlew generateProtos — Square Wire → Kotlin (wear-os)

Usage:
  uv run python scripts/build-protocol.py             # write outputs
  uv run python scripts/build-protocol.py --check     # exit 1 if stale
  uv run python scripts/build-protocol.py --skip-wire # TS + C only (no JVM)

Idempotent. TS / C / SDK-options bindings carry the AUTO-GENERATED header
(stamped below). Kotlin bindings keep Wire's own "Code generated by Wire" banner
— Wire and ordinary Gradle builds both emit it, so re-stamping here would make
this script's output diverge from a plain build and churn the committed files
(see run_wire). Run the full script before committing; --skip-wire skips Kotlin.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PROTO_DIR = ROOT / "shared" / "protocol" / "proto"
TS_OUT = ROOT / "shared" / "protocol" / "src" / "generated"
ESP32_OUT = (
    ROOT / "clients" / "esp32" / "components" / "transport" / "generated" / "proto"
)
# Wire honors `option java_package` and emits Kotlin at the matching path.
# Output is committed to git.
ANDROID_OUT = (
    ROOT
    / "clients"
    / "android"
    / "app"
    / "src"
    / "main"
    / "java"
    / "com"
    / "moumantai"
    / "protocol"
    / "v1"
)
WEAR_OUT = (
    ROOT
    / "clients"
    / "wear-os"
    / "app"
    / "src"
    / "main"
    / "java"
    / "com"
    / "moumantai"
    / "protocol"
    / "v1"
)
NANOPB_OPTIONS = PROTO_DIR / "moumantai" / "v1" / "nanopb.options"
SDK_OPTIONS_OUT = (
    ROOT / "server" / "src" / "server" / "protocol" / "components" / "generated"
)

HEADER = "// AUTO-GENERATED from shared/protocol/proto/ — do not hand-edit"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def run(cmd: list[str], cwd: Path | None = None, env: dict | None = None) -> None:
    """Run a subprocess; raise on nonzero exit."""
    label = " ".join(cmd)
    print(f"  $ {label}")
    result = subprocess.run(
        cmd,
        cwd=str(cwd) if cwd else None,
        env={**os.environ, **(env or {})},
        check=False,
    )
    if result.returncode != 0:
        sys.exit(result.returncode)


def hash_tree(root: Path) -> dict[str, str]:
    """Return {relative-path: sha256-of-bytes} for every file under `root`."""
    if not root.exists():
        return {}
    out = {}
    for p in sorted(root.rglob("*")):
        if not p.is_file():
            continue
        rel = p.relative_to(root).as_posix()
        out[rel] = hashlib.sha256(p.read_bytes()).hexdigest()
    return out


def snapshot_for_check(*roots: Path) -> dict[str, dict[str, str]]:
    return {str(r.relative_to(ROOT).as_posix()): hash_tree(r) for r in roots}


def find_buf() -> list[str]:
    """Return the argv prefix that invokes Buf (bypasses Windows shim resolution)."""
    entry = ROOT / "node_modules" / "@bufbuild" / "buf" / "bin" / "buf"
    if entry.exists():
        return ["node", str(entry)]
    # Fallback: shell out to the wrapper if present (works on macOS/Linux).
    wrapper = ROOT / "node_modules" / ".bin" / "buf"
    if wrapper.exists():
        return [str(wrapper)]
    sys.exit("error: @bufbuild/buf not installed. Run `npm install` from repo root.")


def find_nanopb_generator() -> list[str]:
    """Return the argv prefix that invokes `nanopb_generator`."""
    # Prefer the venv-installed exe (Windows) or shim (Unix).
    if os.name == "nt":
        exe = ROOT / ".venv" / "Scripts" / "nanopb_generator.exe"
        if exe.exists():
            return [str(exe)]
    else:
        exe = ROOT / ".venv" / "bin" / "nanopb_generator"
        if exe.exists():
            return [str(exe)]
    # Module-level fallback (works in any uv-managed env).
    return [sys.executable, "-m", "nanopb.generator.nanopb_generator"]


# ---------------------------------------------------------------------------
# Codegen steps
# ---------------------------------------------------------------------------


def run_buf_generate() -> None:
    """Invoke `buf generate`; protoc-gen-es emits TS."""
    print("\n[1/4] buf generate -> TypeScript")
    # Invoked from repo root so buf.gen.yaml plugin paths resolve correctly.
    cmd = find_buf() + [
        "generate",
        "--template",
        str(PROTO_DIR / "buf.gen.yaml"),
        str(PROTO_DIR),
    ]
    run(cmd, cwd=ROOT)
    # Write the package index file so consumers can do
    # `import { ClientHello } from '@moumantai/protocol/generated/moumantai/v1'`.
    write_ts_index()


def write_ts_index() -> None:
    """Emit `index.ts` re-exporting every generated module; stamp the AUTO-GENERATED header."""
    v1_dir = TS_OUT / "moumantai" / "v1"
    if not v1_dir.exists():
        sys.exit(f"error: protobuf-es did not emit {v1_dir}")

    files = sorted(
        p for p in v1_dir.iterdir() if p.is_file() and p.name.endswith("_pb.ts")
    )
    if not files:
        sys.exit(f"error: no _pb.ts files found in {v1_dir}")

    # Stamp every generated TS file with our AUTO-GENERATED header.
    for f in files:
        text = f.read_text(encoding="utf-8")
        if not text.startswith(HEADER):
            f.write_text(f"{HEADER}\n{text}", encoding="utf-8")

    lines = [
        f"{HEADER}",
        "// re-export every generated module",
        "",
    ]
    for f in files:
        stem = f.stem
        lines.append(f'export * from "./{stem}.js"')
    lines.append("")
    (v1_dir / "index.ts").write_text("\n".join(lines), encoding="utf-8")


def run_nanopb() -> None:
    """Invoke nanopb_generator for the ESP32 C target."""
    print("\n[2/4] nanopb_generator -> C")
    ESP32_OUT.mkdir(parents=True, exist_ok=True)

    # nanopb needs google/protobuf/struct.pb.h for our Struct/Value fields,
    # which isn't bundled with the ESP32 nanopb component. Stage struct.proto
    # from grpcio-tools alongside our protos so the build can link struct.pb.{h,c}.
    import tempfile
    import shutil as _shutil

    google_struct_src = _find_google_struct_proto()
    if google_struct_src is None:
        sys.exit(
            "error: google/protobuf/struct.proto not found. Install grpcio-tools "
            "(`uv sync`) or pre-stage well-known proto bindings."
        )

    proto_files = sorted((PROTO_DIR / "moumantai" / "v1").glob("*.proto"))
    if not proto_files:
        sys.exit("error: no .proto files found")

    # Stage layout nanopb expects: moumantai/v1/*.proto + google/protobuf/struct.proto.
    # nanopb is invoked with --proto-path=<stage> so includes resolve.
    with tempfile.TemporaryDirectory(prefix="moumantai-protoc-") as stage_str:
        stage = Path(stage_str)
        # Stage moumantai/v1
        (stage / "moumantai" / "v1").mkdir(parents=True)
        for p in proto_files:
            _shutil.copy2(p, stage / "moumantai" / "v1" / p.name)
        # Stage google/protobuf/struct.proto
        (stage / "google" / "protobuf").mkdir(parents=True)
        _shutil.copy2(google_struct_src, stage / "google" / "protobuf" / "struct.proto")

        rel_paths_moumantai = [p.relative_to(PROTO_DIR).as_posix() for p in proto_files]
        rel_path_struct = "google/protobuf/struct.proto"

        cmd = find_nanopb_generator() + [
            # -q: suppress "patterns did not match" warnings from the shared .options
            # file referencing fields across all .protos (expected, not a real warning).
            "-q",
            f"--proto-path={stage.as_posix()}",
            f"--output-dir={ESP32_OUT.as_posix()}",
            "--options-file",
            NANOPB_OPTIONS.as_posix(),
            rel_path_struct,
            *rel_paths_moumantai,
        ]
        # nanopb_generator prints its own progress lines.
        run(cmd, cwd=stage)

    # Stamp every emitted file with the AUTO-GENERATED header.
    for path in sorted(ESP32_OUT.rglob("*")):
        if path.is_file() and path.suffix in {".h", ".c"}:
            text = path.read_text(encoding="utf-8")
            if not text.startswith(HEADER):
                path.write_text(f"{HEADER}\n{text}", encoding="utf-8")


def _find_google_struct_proto() -> Path | None:
    """Locate google/protobuf/struct.proto bundled with grpcio-tools."""
    try:
        import grpc_tools  # type: ignore
    except ImportError:
        return None
    candidate = (
        Path(grpc_tools.__file__).parent
        / "_proto"
        / "google"
        / "protobuf"
        / "struct.proto"
    )
    return candidate if candidate.exists() else None


def run_sdk_options(check: bool = False) -> None:
    """Invoke the TS SDK option codegen (depends on protobuf-es bindings).

    Emits `{options,factory}.ts` derived from `ComponentDefSchema` — structural
    defense against silent-drop bugs when proto adds a field the SDK options miss.
    """
    print("\n[SDK] build-sdk-options -> TS options + factory")
    script = ROOT / "server" / "scripts" / "build-sdk-options.ts"
    if not script.exists():
        sys.exit(f"error: {script} missing")
    # Use the local tsx; npx ensures Windows + Unix compat.
    npx = "npx.cmd" if os.name == "nt" else "npx"
    cmd = [npx, "tsx", str(script)]
    if check:
        cmd.append("--check")
    run(cmd, cwd=ROOT / "server")


def run_wire(client_dir: Path, kotlin_out: Path, label: str, step: str) -> None:
    """Invoke `./gradlew :app:generateProtos` for a Wire-enabled Android/Wear workspace."""
    print(f"\n[{step}] gradlew :app:generateProtos -> Kotlin ({label})")
    if os.name == "nt":
        gradlew = client_dir / "gradlew.bat"
    else:
        gradlew = client_dir / "gradlew"
    if not gradlew.exists():
        sys.exit(f"error: {gradlew} missing")

    # --no-daemon avoids a long-lived daemon when the script is one-shot.
    cmd = [str(gradlew), ":app:generateProtos", "--no-daemon"]
    run(cmd, cwd=client_dir)

    # Kotlin bindings are deliberately NOT stamped with HEADER. Wire emits its own
    # "// Code generated by Wire … do not edit." banner, and `:app:generateProtos`
    # is a Gradle compile dependency — so every ordinary app build / IDE sync also
    # regenerates these files, header-less. Stamping here would make this script's
    # output differ from a plain build's, the committed files would oscillate, and
    # `--check` would fail after anyone built the app. Wire's banner is canonical.
    if not any(kotlin_out.rglob("*.kt")):
        sys.exit(f"error: Wire emitted no .kt files under {kotlin_out}")


# ---------------------------------------------------------------------------
# Check mode
# ---------------------------------------------------------------------------


def diff_message(
    prev: dict[str, dict[str, str]], curr: dict[str, dict[str, str]]
) -> str | None:
    """Return a human-readable diff string, or None if trees match."""
    if prev == curr:
        return None
    lines: list[str] = []
    for root in sorted(set(prev) | set(curr)):
        before = prev.get(root, {})
        after = curr.get(root, {})
        added = sorted(set(after) - set(before))
        removed = sorted(set(before) - set(after))
        modified = sorted(
            k for k in (set(before) & set(after)) if before[k] != after[k]
        )
        if added or removed or modified:
            lines.append(f"  {root}/")
            for f in added:
                lines.append(f"    + {f}")
            for f in removed:
                lines.append(f"    - {f}")
            for f in modified:
                lines.append(f"    M {f}")
    return "\n".join(lines) if lines else None


def all_output_roots(skip_wire: bool) -> tuple[Path, ...]:
    if skip_wire:
        return (TS_OUT, ESP32_OUT, SDK_OPTIONS_OUT)
    return (TS_OUT, ESP32_OUT, ANDROID_OUT, WEAR_OUT, SDK_OPTIONS_OUT)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(
        description="Generate language bindings from .proto SSOT"
    )
    parser.add_argument(
        "--check", action="store_true", help="Fail (exit 1) if outputs are stale."
    )
    parser.add_argument(
        "--skip-wire",
        action="store_true",
        help="Skip Kotlin (Wire) codegen; useful when iterating without JVM warmup.",
    )
    args = parser.parse_args(argv)

    roots = all_output_roots(args.skip_wire)
    android_dir = ROOT / "clients" / "android"
    wear_dir = ROOT / "clients" / "wear-os"

    if args.check:
        prev = snapshot_for_check(*roots)
        run_buf_generate()
        run_nanopb()
        if not args.skip_wire:
            run_wire(android_dir, ANDROID_OUT, "android", "3/4")
            run_wire(wear_dir, WEAR_OUT, "wear-os", "4/4")
        run_sdk_options()
        curr = snapshot_for_check(*roots)
        diff = diff_message(prev, curr)
        if diff is None:
            print("\nok: generated outputs are up to date")
            return 0
        print(
            "\nerror: generated outputs are stale.\n"
            "  Run: uv run python scripts/build-protocol.py\n"
            "  Drift:\n" + diff,
            file=sys.stderr,
        )
        return 1

    print("Generating protocol bindings from", PROTO_DIR.relative_to(ROOT))
    run_buf_generate()
    run_nanopb()
    if not args.skip_wire:
        run_wire(android_dir, ANDROID_OUT, "android", "3/4")
        run_wire(wear_dir, WEAR_OUT, "wear-os", "4/4")
    else:
        print("\nNote: --skip-wire was passed; Kotlin output not regenerated.")
    run_sdk_options()
    print("\nDone.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
