#!/usr/bin/env python3
"""Generate clients/registry.md from each client's Taskfile.yml vars block.

The Taskfile.yml vars block is the SSOT for client metadata.

Usage:
  python scripts/build-registry.py          # write clients/registry.md
  python scripts/build-registry.py --check  # exit 1 if stale
"""

from __future__ import annotations

import sys
import yaml
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CLIENTS_DIR = ROOT / "clients"
OUT = CLIENTS_DIR / "registry.md"

HEADER = (
    "<!-- AUTO-GENERATED by scripts/build-registry.py — do not hand-edit. -->\n"
    "<!-- Run `python scripts/build-registry.py` after editing any clients/<id>/Taskfile.yml. -->\n"
)

INTRO = (
    "# Moumantai Clients\n\n"
    "Each `clients/<id>/Taskfile.yml` is the SSOT for that client's metadata + tasks. "
    "This table is generated from those manifests; do not edit by hand.\n\n"
    "- `task --list-all` (from repo root) — every task across every workspace.\n"
    "- Conventions (taxonomy, adding a new client, multi-variant guidance) live in [`CLAUDE.md`](../CLAUDE.md).\n"
)


def load_client_vars(taskfile: Path) -> dict:
    with taskfile.open(encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    return data.get("vars") or {}


def discover_clients() -> list[dict]:
    """Find every clients/<id>/Taskfile.yml whose WORKSPACE_TYPE is 'client'."""
    clients = []
    for sub in sorted(CLIENTS_DIR.iterdir()):
        if not sub.is_dir():
            continue
        tf = sub / "Taskfile.yml"
        if not tf.exists():
            continue
        v = load_client_vars(tf)
        if v.get("WORKSPACE_TYPE") != "client":
            continue
        clients.append(
            {
                "id": v.get("WORKSPACE_ID", sub.name),
                "form_factor": v.get("FORM_FACTOR", "—"),
                "platform": v.get("PLATFORM", "—"),
                "name": v.get("WORKSPACE_NAME", ""),
                "stack": v.get("STACK", ""),
                "dir": sub.name,
            }
        )
    return clients


def render(clients: list[dict]) -> str:
    rows = [
        f"| `{c['id']}` | {c['form_factor']} | {c['platform']} | {c['name']} | {c['stack']} |"
        for c in clients
    ]
    table = "\n".join(
        [
            "| ID | Form factor | Platform | Name | Stack |",
            "|----|-------------|----------|------|-------|",
            *rows,
        ]
    )
    return f"{HEADER}\n{INTRO}\n{table}\n"


def main(argv: list[str]) -> int:
    check_only = "--check" in argv

    clients = discover_clients()
    if not clients:
        print(
            "error: no clients found under clients/<id>/Taskfile.yml", file=sys.stderr
        )
        return 2

    new_content = render(clients)

    if check_only:
        existing = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if existing == new_content:
            print(f"ok: {OUT.relative_to(ROOT)} is up to date ({len(clients)} clients)")
            return 0
        print(
            f"error: {OUT.relative_to(ROOT)} is stale.\n"
            f"  Run: python scripts/build-registry.py",
            file=sys.stderr,
        )
        return 1

    OUT.write_text(new_content, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(clients)} clients)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
