// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.AppListMsg in moumantai/v1/apps.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

/**
 * Server sends the full app list at handshake and when apps change.
 */
public class AppListMsg(
  apps: List<AppInfo> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<AppListMsg, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 1,
    adapter = "com.moumantai.protocol.v1.AppInfo#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 0,
  )
  public val apps: List<AppInfo> = immutableCopyOf("apps", apps)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is AppListMsg) return false
    if (unknownFields != other.unknownFields) return false
    if (apps != other.apps) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + apps.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (apps.isNotEmpty()) result += """apps=$apps"""
    return result.joinToString(prefix = "AppListMsg{", separator = ", ", postfix = "}")
  }

  public fun copy(apps: List<AppInfo> = this.apps, unknownFields: ByteString = this.unknownFields):
      AppListMsg = AppListMsg(apps, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<AppListMsg> = object : ProtoAdapter<AppListMsg>(
      FieldEncoding.LENGTH_DELIMITED, 
      AppListMsg::class, 
      "type.googleapis.com/moumantai.v1.AppListMsg", 
      PROTO_3, 
      null, 
      "moumantai/v1/apps.proto"
    ) {
      override fun encodedSize(`value`: AppListMsg): Int {
        var size = value.unknownFields.size
        size += AppInfo.ADAPTER.asRepeated().encodedSizeWithTag(1, value.apps)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: AppListMsg) {
        AppInfo.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.apps)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: AppListMsg) {
        writer.writeBytes(value.unknownFields)
        AppInfo.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.apps)
      }

      override fun decode(reader: ProtoReader): AppListMsg {
        val apps = mutableListOf<AppInfo>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> apps.add(AppInfo.ADAPTER.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return AppListMsg(
          apps = apps,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: AppListMsg): AppListMsg = value.copy(
        apps = value.apps.redactElements(AppInfo.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<AppListMsg> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
