// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.AudioFormat in moumantai/v1/enums.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int
import kotlin.Suppress

/**
 * Audio frame encoding. Spans server→client TTS and client→server voice
 * upload paths.
 */
public enum class AudioFormat(
  override val `value`: Int,
) : WireEnum {
  AUDIO_FORMAT_UNSPECIFIED(0),
  AUDIO_FORMAT_PCM16(1),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<AudioFormat> = object : EnumAdapter<AudioFormat>(
      AudioFormat::class, 
      PROTO_3, 
      AudioFormat.AUDIO_FORMAT_UNSPECIFIED
    ) {
      override fun fromValue(`value`: Int): AudioFormat? = AudioFormat.fromValue(`value`)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): AudioFormat? = when (`value`) {
      0 -> AUDIO_FORMAT_UNSPECIFIED
      1 -> AUDIO_FORMAT_PCM16
      else -> null
    }
  }
}
