// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.AudioChunkHeader in moumantai/v1/chat.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * ---------------------------------------------------------------------------
 * Binary frame headers (proto-encoded inside the binary frame envelope)
 * ---------------------------------------------------------------------------
 * Per-chunk audio metadata. Proto-encoded in the header bytes of an Audio
 * binary frame; PCM16 payload follows immediately after.
 */
public class AudioChunkHeader(
  /**
   * 'home' or 'app:<app_id>'.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val scope: String = "",
  /**
   * Encoding format.
   */
  @field:WireField(
    tag = 2,
    adapter = "com.moumantai.protocol.v1.AudioFormat#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val format: AudioFormat = AudioFormat.AUDIO_FORMAT_UNSPECIFIED,
  /**
   * Sample rate in Hz (typical: 16000 for pcm16).
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "sampleRate",
    schemaIndex = 2,
  )
  public val sample_rate: Int = 0,
  /**
   * True when this is the last chunk in the stream / utterance.
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    declaredName = "final",
    schemaIndex = 3,
  )
  public val final_: Boolean = false,
  /**
   * Client-generated UUID for idempotent retries — set on the final chunk
   * of a client→server upload only.
   */
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    jsonName = "clientMsgId",
    schemaIndex = 4,
  )
  public val client_msg_id: String? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<AudioChunkHeader, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is AudioChunkHeader) return false
    if (unknownFields != other.unknownFields) return false
    if (scope != other.scope) return false
    if (format != other.format) return false
    if (sample_rate != other.sample_rate) return false
    if (final_ != other.final_) return false
    if (client_msg_id != other.client_msg_id) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + scope.hashCode()
      result = result * 37 + format.hashCode()
      result = result * 37 + sample_rate.hashCode()
      result = result * 37 + final_.hashCode()
      result = result * 37 + (client_msg_id?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """scope=${sanitize(scope)}"""
    result += """format=$format"""
    result += """sample_rate=$sample_rate"""
    result += """final_=$final_"""
    if (client_msg_id != null) result += """client_msg_id=${sanitize(client_msg_id)}"""
    return result.joinToString(prefix = "AudioChunkHeader{", separator = ", ", postfix = "}")
  }

  public fun copy(
    scope: String = this.scope,
    format: AudioFormat = this.format,
    sample_rate: Int = this.sample_rate,
    final_: Boolean = this.final_,
    client_msg_id: String? = this.client_msg_id,
    unknownFields: ByteString = this.unknownFields,
  ): AudioChunkHeader = AudioChunkHeader(scope, format, sample_rate, final_, client_msg_id,
      unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<AudioChunkHeader> = object : ProtoAdapter<AudioChunkHeader>(
      FieldEncoding.LENGTH_DELIMITED, 
      AudioChunkHeader::class, 
      "type.googleapis.com/moumantai.v1.AudioChunkHeader", 
      PROTO_3, 
      null, 
      "moumantai/v1/chat.proto"
    ) {
      override fun encodedSize(`value`: AudioChunkHeader): Int {
        var size = value.unknownFields.size
        if (value.scope != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.scope)
        }
        if (value.format != com.moumantai.protocol.v1.AudioFormat.AUDIO_FORMAT_UNSPECIFIED) {
          size += AudioFormat.ADAPTER.encodedSizeWithTag(2, value.format)
        }
        if (value.sample_rate != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(3, value.sample_rate)
        }
        if (value.final_ != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(4, value.final_)
        }
        size += ProtoAdapter.STRING.encodedSizeWithTag(5, value.client_msg_id)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: AudioChunkHeader) {
        if (value.scope != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.scope)
        }
        if (value.format != com.moumantai.protocol.v1.AudioFormat.AUDIO_FORMAT_UNSPECIFIED) {
          AudioFormat.ADAPTER.encodeWithTag(writer, 2, value.format)
        }
        if (value.sample_rate != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.sample_rate)
        }
        if (value.final_ != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 4, value.final_)
        }
        ProtoAdapter.STRING.encodeWithTag(writer, 5, value.client_msg_id)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: AudioChunkHeader) {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.STRING.encodeWithTag(writer, 5, value.client_msg_id)
        if (value.final_ != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 4, value.final_)
        }
        if (value.sample_rate != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.sample_rate)
        }
        if (value.format != com.moumantai.protocol.v1.AudioFormat.AUDIO_FORMAT_UNSPECIFIED) {
          AudioFormat.ADAPTER.encodeWithTag(writer, 2, value.format)
        }
        if (value.scope != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.scope)
        }
      }

      override fun decode(reader: ProtoReader): AudioChunkHeader {
        var scope: String = ""
        var format: AudioFormat = AudioFormat.AUDIO_FORMAT_UNSPECIFIED
        var sample_rate: Int = 0
        var final_: Boolean = false
        var client_msg_id: String? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> scope = ProtoAdapter.STRING.decode(reader)
            2 -> try {
              format = AudioFormat.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            3 -> sample_rate = ProtoAdapter.INT32.decode(reader)
            4 -> final_ = ProtoAdapter.BOOL.decode(reader)
            5 -> client_msg_id = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return AudioChunkHeader(
          scope = scope,
          format = format,
          sample_rate = sample_rate,
          final_ = final_,
          client_msg_id = client_msg_id,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: AudioChunkHeader): AudioChunkHeader = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<AudioChunkHeader> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
