// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.ButtonComponent in moumantai/v1/components.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * ---------------------------------------------------------------------------
 * Actions
 * ---------------------------------------------------------------------------
 * Clickable button.
 *
 * Intent axes:
 *   - `emphasis`: 'primary' (filled primary CTA, one per face) |
 *     'standard' (default, tonal) | 'quiet' (text only).
 *   - `tone`: 'default' | 'accent' | 'warning' | 'error' | 'info'.
 *
 * FAB is NOT a button variant — use FabComponent for floating action buttons.
 */
public class ButtonComponent(
  /**
   * Button label (may be path-resolved).
   */
  @field:WireField(
    tag = 1,
    adapter = "com.moumantai.protocol.v1.DynamicString#ADAPTER",
    schemaIndex = 0,
  )
  public val text: DynamicString? = null,
  /**
   * Leading icon name (Material Symbols, or 'fa:<name>').
   */
  @field:WireField(
    tag = 3,
    adapter = "com.moumantai.protocol.v1.DynamicString#ADAPTER",
    schemaIndex = 1,
  )
  public val icon: DynamicString? = null,
  /**
   * Disabled gate.
   */
  @field:WireField(
    tag = 4,
    adapter = "com.moumantai.protocol.v1.DynamicBool#ADAPTER",
    schemaIndex = 2,
  )
  public val enabled: DynamicBool? = null,
  /**
   * Click action.
   */
  @field:WireField(
    tag = 5,
    adapter = "com.moumantai.protocol.v1.Action#ADAPTER",
    schemaIndex = 3,
  )
  public val action: Action? = null,
  /**
   * Visual weight: 'primary' | 'standard' (default) | 'quiet'.
   */
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 4,
  )
  public val emphasis: String? = null,
  /**
   * Semantic color role: 'default' (primary family) | 'accent' | 'warning' |
   * 'error' | 'info'.
   */
  @field:WireField(
    tag = 7,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 5,
  )
  public val tone: String? = null,
  @field:WireField(
    tag = 200,
    adapter = "com.moumantai.protocol.v1.Modifier#ADAPTER",
    schemaIndex = 6,
  )
  public val modifier: Modifier? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<ButtonComponent, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ButtonComponent) return false
    if (unknownFields != other.unknownFields) return false
    if (text != other.text) return false
    if (icon != other.icon) return false
    if (enabled != other.enabled) return false
    if (action != other.action) return false
    if (emphasis != other.emphasis) return false
    if (tone != other.tone) return false
    if (modifier != other.modifier) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (text?.hashCode() ?: 0)
      result = result * 37 + (icon?.hashCode() ?: 0)
      result = result * 37 + (enabled?.hashCode() ?: 0)
      result = result * 37 + (action?.hashCode() ?: 0)
      result = result * 37 + (emphasis?.hashCode() ?: 0)
      result = result * 37 + (tone?.hashCode() ?: 0)
      result = result * 37 + (modifier?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (text != null) result += """text=$text"""
    if (icon != null) result += """icon=$icon"""
    if (enabled != null) result += """enabled=$enabled"""
    if (action != null) result += """action=$action"""
    if (emphasis != null) result += """emphasis=${sanitize(emphasis)}"""
    if (tone != null) result += """tone=${sanitize(tone)}"""
    if (modifier != null) result += """modifier=$modifier"""
    return result.joinToString(prefix = "ButtonComponent{", separator = ", ", postfix = "}")
  }

  public fun copy(
    text: DynamicString? = this.text,
    icon: DynamicString? = this.icon,
    enabled: DynamicBool? = this.enabled,
    action: Action? = this.action,
    emphasis: String? = this.emphasis,
    tone: String? = this.tone,
    modifier: Modifier? = this.modifier,
    unknownFields: ByteString = this.unknownFields,
  ): ButtonComponent = ButtonComponent(text, icon, enabled, action, emphasis, tone, modifier,
      unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ButtonComponent> = object : ProtoAdapter<ButtonComponent>(
      FieldEncoding.LENGTH_DELIMITED, 
      ButtonComponent::class, 
      "type.googleapis.com/moumantai.v1.ButtonComponent", 
      PROTO_3, 
      null, 
      "moumantai/v1/components.proto"
    ) {
      override fun encodedSize(`value`: ButtonComponent): Int {
        var size = value.unknownFields.size
        size += DynamicString.ADAPTER.encodedSizeWithTag(1, value.text)
        size += DynamicString.ADAPTER.encodedSizeWithTag(3, value.icon)
        size += DynamicBool.ADAPTER.encodedSizeWithTag(4, value.enabled)
        size += Action.ADAPTER.encodedSizeWithTag(5, value.action)
        size += ProtoAdapter.STRING.encodedSizeWithTag(6, value.emphasis)
        size += ProtoAdapter.STRING.encodedSizeWithTag(7, value.tone)
        size += Modifier.ADAPTER.encodedSizeWithTag(200, value.modifier)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ButtonComponent) {
        DynamicString.ADAPTER.encodeWithTag(writer, 1, value.text)
        DynamicString.ADAPTER.encodeWithTag(writer, 3, value.icon)
        DynamicBool.ADAPTER.encodeWithTag(writer, 4, value.enabled)
        Action.ADAPTER.encodeWithTag(writer, 5, value.action)
        ProtoAdapter.STRING.encodeWithTag(writer, 6, value.emphasis)
        ProtoAdapter.STRING.encodeWithTag(writer, 7, value.tone)
        Modifier.ADAPTER.encodeWithTag(writer, 200, value.modifier)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ButtonComponent) {
        writer.writeBytes(value.unknownFields)
        Modifier.ADAPTER.encodeWithTag(writer, 200, value.modifier)
        ProtoAdapter.STRING.encodeWithTag(writer, 7, value.tone)
        ProtoAdapter.STRING.encodeWithTag(writer, 6, value.emphasis)
        Action.ADAPTER.encodeWithTag(writer, 5, value.action)
        DynamicBool.ADAPTER.encodeWithTag(writer, 4, value.enabled)
        DynamicString.ADAPTER.encodeWithTag(writer, 3, value.icon)
        DynamicString.ADAPTER.encodeWithTag(writer, 1, value.text)
      }

      override fun decode(reader: ProtoReader): ButtonComponent {
        var text: DynamicString? = null
        var icon: DynamicString? = null
        var enabled: DynamicBool? = null
        var action: Action? = null
        var emphasis: String? = null
        var tone: String? = null
        var modifier: Modifier? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> text = DynamicString.ADAPTER.decode(reader)
            3 -> icon = DynamicString.ADAPTER.decode(reader)
            4 -> enabled = DynamicBool.ADAPTER.decode(reader)
            5 -> action = Action.ADAPTER.decode(reader)
            6 -> emphasis = ProtoAdapter.STRING.decode(reader)
            7 -> tone = ProtoAdapter.STRING.decode(reader)
            200 -> modifier = Modifier.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ButtonComponent(
          text = text,
          icon = icon,
          enabled = enabled,
          action = action,
          emphasis = emphasis,
          tone = tone,
          modifier = modifier,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ButtonComponent): ButtonComponent = value.copy(
        text = value.text?.let(DynamicString.ADAPTER::redact),
        icon = value.icon?.let(DynamicString.ADAPTER::redact),
        enabled = value.enabled?.let(DynamicBool.ADAPTER::redact),
        action = value.action?.let(Action.ADAPTER::redact),
        modifier = value.modifier?.let(Modifier.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<ButtonComponent> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
