// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.ChatHistoryMsg in moumantai/v1/chat.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

/**
 * Server → client paged history response for `FetchOlderMsg`. Disposable.
 * Client prepends entries, deduping by id.
 */
public class ChatHistoryMsg(
  /**
   * 'home' or 'app:<app_id>'.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val scope: String = "",
  /**
   * Conversation UUID of the entries — used to detect mid-pagination resets.
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "conversationId",
    schemaIndex = 1,
  )
  public val conversation_id: String = "",
  entries: List<ChatWindowEntry> = emptyList(),
  /**
   * True when older entries still exist before the oldest returned.
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "hasMore",
    schemaIndex = 3,
  )
  public val has_more: Boolean = false,
  /**
   * Thread kind. Unset == CHAT.
   */
  @field:WireField(
    tag = 5,
    adapter = "com.moumantai.protocol.v1.ChatKind#ADAPTER",
    schemaIndex = 4,
  )
  public val kind: ChatKind? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<ChatHistoryMsg, Nothing>(ADAPTER, unknownFields) {
  /**
   * Older-than-cursor entries, in ascending seq order.
   */
  @field:WireField(
    tag = 3,
    adapter = "com.moumantai.protocol.v1.ChatWindowEntry#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 2,
  )
  public val entries: List<ChatWindowEntry> = immutableCopyOf("entries", entries)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ChatHistoryMsg) return false
    if (unknownFields != other.unknownFields) return false
    if (scope != other.scope) return false
    if (conversation_id != other.conversation_id) return false
    if (entries != other.entries) return false
    if (has_more != other.has_more) return false
    if (kind != other.kind) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + scope.hashCode()
      result = result * 37 + conversation_id.hashCode()
      result = result * 37 + entries.hashCode()
      result = result * 37 + has_more.hashCode()
      result = result * 37 + (kind?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """scope=${sanitize(scope)}"""
    result += """conversation_id=${sanitize(conversation_id)}"""
    if (entries.isNotEmpty()) result += """entries=$entries"""
    result += """has_more=$has_more"""
    if (kind != null) result += """kind=$kind"""
    return result.joinToString(prefix = "ChatHistoryMsg{", separator = ", ", postfix = "}")
  }

  public fun copy(
    scope: String = this.scope,
    conversation_id: String = this.conversation_id,
    entries: List<ChatWindowEntry> = this.entries,
    has_more: Boolean = this.has_more,
    kind: ChatKind? = this.kind,
    unknownFields: ByteString = this.unknownFields,
  ): ChatHistoryMsg = ChatHistoryMsg(scope, conversation_id, entries, has_more, kind, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ChatHistoryMsg> = object : ProtoAdapter<ChatHistoryMsg>(
      FieldEncoding.LENGTH_DELIMITED, 
      ChatHistoryMsg::class, 
      "type.googleapis.com/moumantai.v1.ChatHistoryMsg", 
      PROTO_3, 
      null, 
      "moumantai/v1/chat.proto"
    ) {
      override fun encodedSize(`value`: ChatHistoryMsg): Int {
        var size = value.unknownFields.size
        if (value.scope != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.scope)
        }
        if (value.conversation_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.conversation_id)
        }
        size += ChatWindowEntry.ADAPTER.asRepeated().encodedSizeWithTag(3, value.entries)
        if (value.has_more != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(4, value.has_more)
        }
        size += ChatKind.ADAPTER.encodedSizeWithTag(5, value.kind)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ChatHistoryMsg) {
        if (value.scope != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.scope)
        }
        if (value.conversation_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.conversation_id)
        }
        ChatWindowEntry.ADAPTER.asRepeated().encodeWithTag(writer, 3, value.entries)
        if (value.has_more != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 4, value.has_more)
        }
        ChatKind.ADAPTER.encodeWithTag(writer, 5, value.kind)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ChatHistoryMsg) {
        writer.writeBytes(value.unknownFields)
        ChatKind.ADAPTER.encodeWithTag(writer, 5, value.kind)
        if (value.has_more != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 4, value.has_more)
        }
        ChatWindowEntry.ADAPTER.asRepeated().encodeWithTag(writer, 3, value.entries)
        if (value.conversation_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.conversation_id)
        }
        if (value.scope != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.scope)
        }
      }

      override fun decode(reader: ProtoReader): ChatHistoryMsg {
        var scope: String = ""
        var conversation_id: String = ""
        val entries = mutableListOf<ChatWindowEntry>()
        var has_more: Boolean = false
        var kind: ChatKind? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> scope = ProtoAdapter.STRING.decode(reader)
            2 -> conversation_id = ProtoAdapter.STRING.decode(reader)
            3 -> entries.add(ChatWindowEntry.ADAPTER.decode(reader))
            4 -> has_more = ProtoAdapter.BOOL.decode(reader)
            5 -> try {
              kind = ChatKind.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            else -> reader.readUnknownField(tag)
          }
        }
        return ChatHistoryMsg(
          scope = scope,
          conversation_id = conversation_id,
          entries = entries,
          has_more = has_more,
          kind = kind,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ChatHistoryMsg): ChatHistoryMsg = value.copy(
        entries = value.entries.redactElements(ChatWindowEntry.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<ChatHistoryMsg> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
