// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.ChatTodosUpdate in moumantai/v1/chat.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

/**
 * ---------------------------------------------------------------------------
 * Edit-agent progress (TodoWrite forwarding)
 * ---------------------------------------------------------------------------
 * Server → client echo of the edit-agent's TodoWrite tool call. The adapter
 * detects TodoWrite events and forwards the list; the PWA renders a pinned
 * progress card in the dev chat.
 */
public class ChatTodosUpdate(
  /**
   * 'home' or 'app:<app_id>'.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val scope: String = "",
  /**
   * Owning dev conversation UUID.
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "conversationId",
    schemaIndex = 1,
  )
  public val conversation_id: String = "",
  /**
   * Always CHAT_KIND_DEV in v1.
   */
  @field:WireField(
    tag = 3,
    adapter = "com.moumantai.protocol.v1.ChatKind#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val kind: ChatKind = ChatKind.CHAT_KIND_UNSPECIFIED,
  todos: List<TodoItem> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<ChatTodosUpdate, Nothing>(ADAPTER, unknownFields) {
  /**
   * Current todo list (full snapshot, not a delta).
   */
  @field:WireField(
    tag = 4,
    adapter = "com.moumantai.protocol.v1.TodoItem#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 3,
  )
  public val todos: List<TodoItem> = immutableCopyOf("todos", todos)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ChatTodosUpdate) return false
    if (unknownFields != other.unknownFields) return false
    if (scope != other.scope) return false
    if (conversation_id != other.conversation_id) return false
    if (kind != other.kind) return false
    if (todos != other.todos) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + scope.hashCode()
      result = result * 37 + conversation_id.hashCode()
      result = result * 37 + kind.hashCode()
      result = result * 37 + todos.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """scope=${sanitize(scope)}"""
    result += """conversation_id=${sanitize(conversation_id)}"""
    result += """kind=$kind"""
    if (todos.isNotEmpty()) result += """todos=$todos"""
    return result.joinToString(prefix = "ChatTodosUpdate{", separator = ", ", postfix = "}")
  }

  public fun copy(
    scope: String = this.scope,
    conversation_id: String = this.conversation_id,
    kind: ChatKind = this.kind,
    todos: List<TodoItem> = this.todos,
    unknownFields: ByteString = this.unknownFields,
  ): ChatTodosUpdate = ChatTodosUpdate(scope, conversation_id, kind, todos, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ChatTodosUpdate> = object : ProtoAdapter<ChatTodosUpdate>(
      FieldEncoding.LENGTH_DELIMITED, 
      ChatTodosUpdate::class, 
      "type.googleapis.com/moumantai.v1.ChatTodosUpdate", 
      PROTO_3, 
      null, 
      "moumantai/v1/chat.proto"
    ) {
      override fun encodedSize(`value`: ChatTodosUpdate): Int {
        var size = value.unknownFields.size
        if (value.scope != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.scope)
        }
        if (value.conversation_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.conversation_id)
        }
        if (value.kind != com.moumantai.protocol.v1.ChatKind.CHAT_KIND_UNSPECIFIED) {
          size += ChatKind.ADAPTER.encodedSizeWithTag(3, value.kind)
        }
        size += TodoItem.ADAPTER.asRepeated().encodedSizeWithTag(4, value.todos)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ChatTodosUpdate) {
        if (value.scope != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.scope)
        }
        if (value.conversation_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.conversation_id)
        }
        if (value.kind != com.moumantai.protocol.v1.ChatKind.CHAT_KIND_UNSPECIFIED) {
          ChatKind.ADAPTER.encodeWithTag(writer, 3, value.kind)
        }
        TodoItem.ADAPTER.asRepeated().encodeWithTag(writer, 4, value.todos)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ChatTodosUpdate) {
        writer.writeBytes(value.unknownFields)
        TodoItem.ADAPTER.asRepeated().encodeWithTag(writer, 4, value.todos)
        if (value.kind != com.moumantai.protocol.v1.ChatKind.CHAT_KIND_UNSPECIFIED) {
          ChatKind.ADAPTER.encodeWithTag(writer, 3, value.kind)
        }
        if (value.conversation_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.conversation_id)
        }
        if (value.scope != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.scope)
        }
      }

      override fun decode(reader: ProtoReader): ChatTodosUpdate {
        var scope: String = ""
        var conversation_id: String = ""
        var kind: ChatKind = ChatKind.CHAT_KIND_UNSPECIFIED
        val todos = mutableListOf<TodoItem>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> scope = ProtoAdapter.STRING.decode(reader)
            2 -> conversation_id = ProtoAdapter.STRING.decode(reader)
            3 -> try {
              kind = ChatKind.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            4 -> todos.add(TodoItem.ADAPTER.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return ChatTodosUpdate(
          scope = scope,
          conversation_id = conversation_id,
          kind = kind,
          todos = todos,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ChatTodosUpdate): ChatTodosUpdate = value.copy(
        todos = value.todos.redactElements(TodoItem.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<ChatTodosUpdate> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
