// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.ChatKind in moumantai/v1/chat.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int
import kotlin.Suppress

/**
 * ---------------------------------------------------------------------------
 * Chat thread kind (regular vs. dev/draft-editing)
 * ---------------------------------------------------------------------------
 * Distinguishes the regular user chat from the developer (draft-editing) chat
 * thread. A scope can have one active conversation per kind. Unset == CHAT so
 * existing clients/rows behave unchanged.
 */
public enum class ChatKind(
  override val `value`: Int,
) : WireEnum {
  CHAT_KIND_UNSPECIFIED(0),
  CHAT_KIND_CHAT(1),
  CHAT_KIND_DEV(2),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ChatKind> = object : EnumAdapter<ChatKind>(
      ChatKind::class, 
      PROTO_3, 
      ChatKind.CHAT_KIND_UNSPECIFIED
    ) {
      override fun fromValue(`value`: Int): ChatKind? = ChatKind.fromValue(`value`)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): ChatKind? = when (`value`) {
      0 -> CHAT_KIND_UNSPECIFIED
      1 -> CHAT_KIND_CHAT
      2 -> CHAT_KIND_DEV
      else -> null
    }
  }
}
