// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.ChatUpdateMsg in moumantai/v1/chat.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Server → client incremental status update for an existing user row — sent
 * when a turn transitions state without a new chat row. Broadcast to every
 * socket in the scope for multi-device coherence.
 */
public class ChatUpdateMsg(
  /**
   * 'home' or 'app:<app_id>'.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val scope: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "conversationId",
    schemaIndex = 1,
  )
  public val conversation_id: String = "",
  /**
   * Message row UUID being updated.
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val id: String = "",
  /**
   * New lifecycle status.
   */
  @field:WireField(
    tag = 4,
    adapter = "com.moumantai.protocol.v1.TurnStatus#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val status: TurnStatus = TurnStatus.TURN_STATUS_UNSPECIFIED,
  /**
   * Short failure tag when status is a terminal-failure variant.
   */
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    jsonName = "failureReason",
    schemaIndex = 4,
  )
  public val failure_reason: String? = null,
  /**
   * Echoed from the underlying user row (origin_device_id).
   */
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    jsonName = "originDeviceId",
    schemaIndex = 5,
  )
  public val origin_device_id: String? = null,
  /**
   * Thread kind. Unset == CHAT.
   */
  @field:WireField(
    tag = 7,
    adapter = "com.moumantai.protocol.v1.ChatKind#ADAPTER",
    schemaIndex = 6,
  )
  public val kind: ChatKind? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<ChatUpdateMsg, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ChatUpdateMsg) return false
    if (unknownFields != other.unknownFields) return false
    if (scope != other.scope) return false
    if (conversation_id != other.conversation_id) return false
    if (id != other.id) return false
    if (status != other.status) return false
    if (failure_reason != other.failure_reason) return false
    if (origin_device_id != other.origin_device_id) return false
    if (kind != other.kind) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + scope.hashCode()
      result = result * 37 + conversation_id.hashCode()
      result = result * 37 + id.hashCode()
      result = result * 37 + status.hashCode()
      result = result * 37 + (failure_reason?.hashCode() ?: 0)
      result = result * 37 + (origin_device_id?.hashCode() ?: 0)
      result = result * 37 + (kind?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """scope=${sanitize(scope)}"""
    result += """conversation_id=${sanitize(conversation_id)}"""
    result += """id=${sanitize(id)}"""
    result += """status=$status"""
    if (failure_reason != null) result += """failure_reason=${sanitize(failure_reason)}"""
    if (origin_device_id != null) result += """origin_device_id=${sanitize(origin_device_id)}"""
    if (kind != null) result += """kind=$kind"""
    return result.joinToString(prefix = "ChatUpdateMsg{", separator = ", ", postfix = "}")
  }

  public fun copy(
    scope: String = this.scope,
    conversation_id: String = this.conversation_id,
    id: String = this.id,
    status: TurnStatus = this.status,
    failure_reason: String? = this.failure_reason,
    origin_device_id: String? = this.origin_device_id,
    kind: ChatKind? = this.kind,
    unknownFields: ByteString = this.unknownFields,
  ): ChatUpdateMsg = ChatUpdateMsg(scope, conversation_id, id, status, failure_reason,
      origin_device_id, kind, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ChatUpdateMsg> = object : ProtoAdapter<ChatUpdateMsg>(
      FieldEncoding.LENGTH_DELIMITED, 
      ChatUpdateMsg::class, 
      "type.googleapis.com/moumantai.v1.ChatUpdateMsg", 
      PROTO_3, 
      null, 
      "moumantai/v1/chat.proto"
    ) {
      override fun encodedSize(`value`: ChatUpdateMsg): Int {
        var size = value.unknownFields.size
        if (value.scope != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.scope)
        }
        if (value.conversation_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.conversation_id)
        }
        if (value.id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.id)
        }
        if (value.status != com.moumantai.protocol.v1.TurnStatus.TURN_STATUS_UNSPECIFIED) {
          size += TurnStatus.ADAPTER.encodedSizeWithTag(4, value.status)
        }
        size += ProtoAdapter.STRING.encodedSizeWithTag(5, value.failure_reason)
        size += ProtoAdapter.STRING.encodedSizeWithTag(6, value.origin_device_id)
        size += ChatKind.ADAPTER.encodedSizeWithTag(7, value.kind)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ChatUpdateMsg) {
        if (value.scope != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.scope)
        }
        if (value.conversation_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.conversation_id)
        }
        if (value.id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.id)
        }
        if (value.status != com.moumantai.protocol.v1.TurnStatus.TURN_STATUS_UNSPECIFIED) {
          TurnStatus.ADAPTER.encodeWithTag(writer, 4, value.status)
        }
        ProtoAdapter.STRING.encodeWithTag(writer, 5, value.failure_reason)
        ProtoAdapter.STRING.encodeWithTag(writer, 6, value.origin_device_id)
        ChatKind.ADAPTER.encodeWithTag(writer, 7, value.kind)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ChatUpdateMsg) {
        writer.writeBytes(value.unknownFields)
        ChatKind.ADAPTER.encodeWithTag(writer, 7, value.kind)
        ProtoAdapter.STRING.encodeWithTag(writer, 6, value.origin_device_id)
        ProtoAdapter.STRING.encodeWithTag(writer, 5, value.failure_reason)
        if (value.status != com.moumantai.protocol.v1.TurnStatus.TURN_STATUS_UNSPECIFIED) {
          TurnStatus.ADAPTER.encodeWithTag(writer, 4, value.status)
        }
        if (value.id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.id)
        }
        if (value.conversation_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.conversation_id)
        }
        if (value.scope != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.scope)
        }
      }

      override fun decode(reader: ProtoReader): ChatUpdateMsg {
        var scope: String = ""
        var conversation_id: String = ""
        var id: String = ""
        var status: TurnStatus = TurnStatus.TURN_STATUS_UNSPECIFIED
        var failure_reason: String? = null
        var origin_device_id: String? = null
        var kind: ChatKind? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> scope = ProtoAdapter.STRING.decode(reader)
            2 -> conversation_id = ProtoAdapter.STRING.decode(reader)
            3 -> id = ProtoAdapter.STRING.decode(reader)
            4 -> try {
              status = TurnStatus.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            5 -> failure_reason = ProtoAdapter.STRING.decode(reader)
            6 -> origin_device_id = ProtoAdapter.STRING.decode(reader)
            7 -> try {
              kind = ChatKind.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            else -> reader.readUnknownField(tag)
          }
        }
        return ChatUpdateMsg(
          scope = scope,
          conversation_id = conversation_id,
          id = id,
          status = status,
          failure_reason = failure_reason,
          origin_device_id = origin_device_id,
          kind = kind,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ChatUpdateMsg): ChatUpdateMsg = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<ChatUpdateMsg> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
