// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.CloseCode in moumantai/v1/enums.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int
import kotlin.Suppress

/**
 * WebSocket close codes (4000–4999 private range). Field numbers match the
 * numeric close-code values so an int wire round-trip is faithful.
 */
public enum class CloseCode(
  override val `value`: Int,
) : WireEnum {
  CLOSE_CODE_UNSPECIFIED(0),
  CLOSE_CODE_HANDSHAKE_TIMEOUT(4_001),
  CLOSE_CODE_INVALID_HELLO(4_002),
  CLOSE_CODE_UNKNOWN_SESSION(4_003),
  CLOSE_CODE_SESSION_IN_USE(4_004),
  CLOSE_CODE_AUDIO_OVERFLOW(4_005),
  CLOSE_CODE_RATE_LIMITED(4_006),
  CLOSE_CODE_FRAME_TOO_LARGE(4_007),
  /**
   * Device is not paired (allowlisted) on a server with pairing enabled. The
   * client should surface a "pairing required" state (it can derive a short
   * code from its own deviceId) and keep retrying — approval flips a server
   * flag and the next reconnect succeeds. Not fatal: do not stop reconnecting.
   */
  CLOSE_CODE_PAIRING_REQUIRED(4_008),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<CloseCode> = object : EnumAdapter<CloseCode>(
      CloseCode::class, 
      PROTO_3, 
      CloseCode.CLOSE_CODE_UNSPECIFIED
    ) {
      override fun fromValue(`value`: Int): CloseCode? = CloseCode.fromValue(`value`)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): CloseCode? = when (`value`) {
      0 -> CLOSE_CODE_UNSPECIFIED
      4_001 -> CLOSE_CODE_HANDSHAKE_TIMEOUT
      4_002 -> CLOSE_CODE_INVALID_HELLO
      4_003 -> CLOSE_CODE_UNKNOWN_SESSION
      4_004 -> CLOSE_CODE_SESSION_IN_USE
      4_005 -> CLOSE_CODE_AUDIO_OVERFLOW
      4_006 -> CLOSE_CODE_RATE_LIMITED
      4_007 -> CLOSE_CODE_FRAME_TOO_LARGE
      4_008 -> CLOSE_CODE_PAIRING_REQUIRED
      else -> null
    }
  }
}
