// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.ComponentDef in moumantai/v1/components.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.countNonNull
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * ---------------------------------------------------------------------------
 * Top-level component wrapper
 * ---------------------------------------------------------------------------
 * Flat component definition. `id` is the renderer's stable handle;
 * the `component` oneof carries the variant-specific props.
 */
public class ComponentDef(
  /**
   * Stable component id (must be unique within a face). The root scaffold
   * must use id="root".
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val id: String = "",
  /**
   * atoms
   */
  @field:WireField(
    tag = 10,
    adapter = "com.moumantai.protocol.v1.TextComponent#ADAPTER",
    oneofName = "component",
    schemaIndex = 1,
  )
  public val text: TextComponent? = null,
  @field:WireField(
    tag = 11,
    adapter = "com.moumantai.protocol.v1.IconComponent#ADAPTER",
    oneofName = "component",
    schemaIndex = 2,
  )
  public val icon: IconComponent? = null,
  @field:WireField(
    tag = 12,
    adapter = "com.moumantai.protocol.v1.ImageComponent#ADAPTER",
    oneofName = "component",
    schemaIndex = 3,
  )
  public val image: ImageComponent? = null,
  @field:WireField(
    tag = 13,
    adapter = "com.moumantai.protocol.v1.DividerComponent#ADAPTER",
    oneofName = "component",
    schemaIndex = 4,
  )
  public val divider: DividerComponent? = null,
  /**
   * layout
   */
  @field:WireField(
    tag = 20,
    adapter = "com.moumantai.protocol.v1.ColumnComponent#ADAPTER",
    oneofName = "component",
    schemaIndex = 5,
  )
  public val column: ColumnComponent? = null,
  @field:WireField(
    tag = 21,
    adapter = "com.moumantai.protocol.v1.RowComponent#ADAPTER",
    oneofName = "component",
    schemaIndex = 6,
  )
  public val row: RowComponent? = null,
  @field:WireField(
    tag = 22,
    adapter = "com.moumantai.protocol.v1.CardComponent#ADAPTER",
    oneofName = "component",
    schemaIndex = 7,
  )
  public val card: CardComponent? = null,
  /**
   * chrome
   */
  @field:WireField(
    tag = 30,
    adapter = "com.moumantai.protocol.v1.ScaffoldComponent#ADAPTER",
    oneofName = "component",
    schemaIndex = 8,
  )
  public val scaffold: ScaffoldComponent? = null,
  @field:WireField(
    tag = 31,
    adapter = "com.moumantai.protocol.v1.TopBarComponent#ADAPTER",
    jsonName = "topBar",
    oneofName = "component",
    schemaIndex = 9,
  )
  public val top_bar: TopBarComponent? = null,
  /**
   * actions
   */
  @field:WireField(
    tag = 40,
    adapter = "com.moumantai.protocol.v1.ButtonComponent#ADAPTER",
    oneofName = "component",
    schemaIndex = 10,
  )
  public val button: ButtonComponent? = null,
  @field:WireField(
    tag = 41,
    adapter = "com.moumantai.protocol.v1.ChipComponent#ADAPTER",
    oneofName = "component",
    schemaIndex = 11,
  )
  public val chip: ChipComponent? = null,
  @field:WireField(
    tag = 42,
    adapter = "com.moumantai.protocol.v1.FabComponent#ADAPTER",
    oneofName = "component",
    schemaIndex = 12,
  )
  public val fab: FabComponent? = null,
  /**
   * input
   */
  @field:WireField(
    tag = 50,
    adapter = "com.moumantai.protocol.v1.TextFieldComponent#ADAPTER",
    jsonName = "textField",
    oneofName = "component",
    schemaIndex = 13,
  )
  public val text_field: TextFieldComponent? = null,
  @field:WireField(
    tag = 51,
    adapter = "com.moumantai.protocol.v1.CheckBoxComponent#ADAPTER",
    jsonName = "checkBox",
    oneofName = "component",
    schemaIndex = 14,
  )
  public val check_box: CheckBoxComponent? = null,
  @field:WireField(
    tag = 52,
    adapter = "com.moumantai.protocol.v1.SwitchComponent#ADAPTER",
    jsonName = "switchToggle",
    oneofName = "component",
    schemaIndex = 15,
  )
  public val switch_toggle: SwitchComponent? = null,
  @field:WireField(
    tag = 53,
    adapter = "com.moumantai.protocol.v1.SliderComponent#ADAPTER",
    oneofName = "component",
    schemaIndex = 16,
  )
  public val slider: SliderComponent? = null,
  @field:WireField(
    tag = 54,
    adapter = "com.moumantai.protocol.v1.TabsComponent#ADAPTER",
    oneofName = "component",
    schemaIndex = 17,
  )
  public val tabs: TabsComponent? = null,
  @field:WireField(
    tag = 55,
    adapter = "com.moumantai.protocol.v1.SelectComponent#ADAPTER",
    oneofName = "component",
    schemaIndex = 18,
  )
  public val select: SelectComponent? = null,
  @field:WireField(
    tag = 56,
    adapter = "com.moumantai.protocol.v1.DateTimeInputComponent#ADAPTER",
    jsonName = "dateTimeInput",
    oneofName = "component",
    schemaIndex = 19,
  )
  public val date_time_input: DateTimeInputComponent? = null,
  /**
   * data
   */
  @field:WireField(
    tag = 60,
    adapter = "com.moumantai.protocol.v1.ListComponent#ADAPTER",
    oneofName = "component",
    schemaIndex = 20,
  )
  public val list: ListComponent? = null,
  @field:WireField(
    tag = 61,
    adapter = "com.moumantai.protocol.v1.ListItemComponent#ADAPTER",
    jsonName = "listItem",
    oneofName = "component",
    schemaIndex = 21,
  )
  public val list_item: ListItemComponent? = null,
  /**
   * feedback
   */
  @field:WireField(
    tag = 72,
    adapter = "com.moumantai.protocol.v1.ProgressRingComponent#ADAPTER",
    jsonName = "progressRing",
    oneofName = "component",
    schemaIndex = 22,
  )
  public val progress_ring: ProgressRingComponent? = null,
  @field:WireField(
    tag = 73,
    adapter = "com.moumantai.protocol.v1.ProgressBarComponent#ADAPTER",
    jsonName = "progressBar",
    oneofName = "component",
    schemaIndex = 23,
  )
  public val progress_bar: ProgressBarComponent? = null,
  @field:WireField(
    tag = 71,
    adapter = "com.moumantai.protocol.v1.ModalComponent#ADAPTER",
    oneofName = "component",
    schemaIndex = 24,
  )
  public val modal: ModalComponent? = null,
  /**
   * layout (cont.) — z-stack overlay container.
   */
  @field:WireField(
    tag = 23,
    adapter = "com.moumantai.protocol.v1.BoxComponent#ADAPTER",
    oneofName = "component",
    schemaIndex = 25,
  )
  public val box: BoxComponent? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<ComponentDef, Nothing>(ADAPTER, unknownFields) {
  init {
    require(countNonNull(text, icon, image, divider, column, row, card, scaffold, top_bar, button,
        chip, fab, text_field, check_box, switch_toggle, slider, tabs, select, date_time_input,
        list, list_item, progress_ring, progress_bar, modal, box) <= 1) {
      "At most one of text, icon, image, divider, column, row, card, scaffold, top_bar, button, chip, fab, text_field, check_box, switch_toggle, slider, tabs, select, date_time_input, list, list_item, progress_ring, progress_bar, modal, box may be non-null"
    }
  }

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ComponentDef) return false
    if (unknownFields != other.unknownFields) return false
    if (id != other.id) return false
    if (text != other.text) return false
    if (icon != other.icon) return false
    if (image != other.image) return false
    if (divider != other.divider) return false
    if (column != other.column) return false
    if (row != other.row) return false
    if (card != other.card) return false
    if (scaffold != other.scaffold) return false
    if (top_bar != other.top_bar) return false
    if (button != other.button) return false
    if (chip != other.chip) return false
    if (fab != other.fab) return false
    if (text_field != other.text_field) return false
    if (check_box != other.check_box) return false
    if (switch_toggle != other.switch_toggle) return false
    if (slider != other.slider) return false
    if (tabs != other.tabs) return false
    if (select != other.select) return false
    if (date_time_input != other.date_time_input) return false
    if (list != other.list) return false
    if (list_item != other.list_item) return false
    if (progress_ring != other.progress_ring) return false
    if (progress_bar != other.progress_bar) return false
    if (modal != other.modal) return false
    if (box != other.box) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + id.hashCode()
      result = result * 37 + (text?.hashCode() ?: 0)
      result = result * 37 + (icon?.hashCode() ?: 0)
      result = result * 37 + (image?.hashCode() ?: 0)
      result = result * 37 + (divider?.hashCode() ?: 0)
      result = result * 37 + (column?.hashCode() ?: 0)
      result = result * 37 + (row?.hashCode() ?: 0)
      result = result * 37 + (card?.hashCode() ?: 0)
      result = result * 37 + (scaffold?.hashCode() ?: 0)
      result = result * 37 + (top_bar?.hashCode() ?: 0)
      result = result * 37 + (button?.hashCode() ?: 0)
      result = result * 37 + (chip?.hashCode() ?: 0)
      result = result * 37 + (fab?.hashCode() ?: 0)
      result = result * 37 + (text_field?.hashCode() ?: 0)
      result = result * 37 + (check_box?.hashCode() ?: 0)
      result = result * 37 + (switch_toggle?.hashCode() ?: 0)
      result = result * 37 + (slider?.hashCode() ?: 0)
      result = result * 37 + (tabs?.hashCode() ?: 0)
      result = result * 37 + (select?.hashCode() ?: 0)
      result = result * 37 + (date_time_input?.hashCode() ?: 0)
      result = result * 37 + (list?.hashCode() ?: 0)
      result = result * 37 + (list_item?.hashCode() ?: 0)
      result = result * 37 + (progress_ring?.hashCode() ?: 0)
      result = result * 37 + (progress_bar?.hashCode() ?: 0)
      result = result * 37 + (modal?.hashCode() ?: 0)
      result = result * 37 + (box?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """id=${sanitize(id)}"""
    if (text != null) result += """text=$text"""
    if (icon != null) result += """icon=$icon"""
    if (image != null) result += """image=$image"""
    if (divider != null) result += """divider=$divider"""
    if (column != null) result += """column=$column"""
    if (row != null) result += """row=$row"""
    if (card != null) result += """card=$card"""
    if (scaffold != null) result += """scaffold=$scaffold"""
    if (top_bar != null) result += """top_bar=$top_bar"""
    if (button != null) result += """button=$button"""
    if (chip != null) result += """chip=$chip"""
    if (fab != null) result += """fab=$fab"""
    if (text_field != null) result += """text_field=$text_field"""
    if (check_box != null) result += """check_box=$check_box"""
    if (switch_toggle != null) result += """switch_toggle=$switch_toggle"""
    if (slider != null) result += """slider=$slider"""
    if (tabs != null) result += """tabs=$tabs"""
    if (select != null) result += """select=$select"""
    if (date_time_input != null) result += """date_time_input=$date_time_input"""
    if (list != null) result += """list=$list"""
    if (list_item != null) result += """list_item=$list_item"""
    if (progress_ring != null) result += """progress_ring=$progress_ring"""
    if (progress_bar != null) result += """progress_bar=$progress_bar"""
    if (modal != null) result += """modal=$modal"""
    if (box != null) result += """box=$box"""
    return result.joinToString(prefix = "ComponentDef{", separator = ", ", postfix = "}")
  }

  public fun copy(
    id: String = this.id,
    text: TextComponent? = this.text,
    icon: IconComponent? = this.icon,
    image: ImageComponent? = this.image,
    divider: DividerComponent? = this.divider,
    column: ColumnComponent? = this.column,
    row: RowComponent? = this.row,
    card: CardComponent? = this.card,
    scaffold: ScaffoldComponent? = this.scaffold,
    top_bar: TopBarComponent? = this.top_bar,
    button: ButtonComponent? = this.button,
    chip: ChipComponent? = this.chip,
    fab: FabComponent? = this.fab,
    text_field: TextFieldComponent? = this.text_field,
    check_box: CheckBoxComponent? = this.check_box,
    switch_toggle: SwitchComponent? = this.switch_toggle,
    slider: SliderComponent? = this.slider,
    tabs: TabsComponent? = this.tabs,
    select: SelectComponent? = this.select,
    date_time_input: DateTimeInputComponent? = this.date_time_input,
    list: ListComponent? = this.list,
    list_item: ListItemComponent? = this.list_item,
    progress_ring: ProgressRingComponent? = this.progress_ring,
    progress_bar: ProgressBarComponent? = this.progress_bar,
    modal: ModalComponent? = this.modal,
    box: BoxComponent? = this.box,
    unknownFields: ByteString = this.unknownFields,
  ): ComponentDef = ComponentDef(id, text, icon, image, divider, column, row, card, scaffold,
      top_bar, button, chip, fab, text_field, check_box, switch_toggle, slider, tabs, select,
      date_time_input, list, list_item, progress_ring, progress_bar, modal, box, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ComponentDef> = object : ProtoAdapter<ComponentDef>(
      FieldEncoding.LENGTH_DELIMITED, 
      ComponentDef::class, 
      "type.googleapis.com/moumantai.v1.ComponentDef", 
      PROTO_3, 
      null, 
      "moumantai/v1/components.proto"
    ) {
      override fun encodedSize(`value`: ComponentDef): Int {
        var size = value.unknownFields.size
        if (value.id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.id)
        }
        size += TextComponent.ADAPTER.encodedSizeWithTag(10, value.text)
        size += IconComponent.ADAPTER.encodedSizeWithTag(11, value.icon)
        size += ImageComponent.ADAPTER.encodedSizeWithTag(12, value.image)
        size += DividerComponent.ADAPTER.encodedSizeWithTag(13, value.divider)
        size += ColumnComponent.ADAPTER.encodedSizeWithTag(20, value.column)
        size += RowComponent.ADAPTER.encodedSizeWithTag(21, value.row)
        size += CardComponent.ADAPTER.encodedSizeWithTag(22, value.card)
        size += ScaffoldComponent.ADAPTER.encodedSizeWithTag(30, value.scaffold)
        size += TopBarComponent.ADAPTER.encodedSizeWithTag(31, value.top_bar)
        size += ButtonComponent.ADAPTER.encodedSizeWithTag(40, value.button)
        size += ChipComponent.ADAPTER.encodedSizeWithTag(41, value.chip)
        size += FabComponent.ADAPTER.encodedSizeWithTag(42, value.fab)
        size += TextFieldComponent.ADAPTER.encodedSizeWithTag(50, value.text_field)
        size += CheckBoxComponent.ADAPTER.encodedSizeWithTag(51, value.check_box)
        size += SwitchComponent.ADAPTER.encodedSizeWithTag(52, value.switch_toggle)
        size += SliderComponent.ADAPTER.encodedSizeWithTag(53, value.slider)
        size += TabsComponent.ADAPTER.encodedSizeWithTag(54, value.tabs)
        size += SelectComponent.ADAPTER.encodedSizeWithTag(55, value.select)
        size += DateTimeInputComponent.ADAPTER.encodedSizeWithTag(56, value.date_time_input)
        size += ListComponent.ADAPTER.encodedSizeWithTag(60, value.list)
        size += ListItemComponent.ADAPTER.encodedSizeWithTag(61, value.list_item)
        size += ProgressRingComponent.ADAPTER.encodedSizeWithTag(72, value.progress_ring)
        size += ProgressBarComponent.ADAPTER.encodedSizeWithTag(73, value.progress_bar)
        size += ModalComponent.ADAPTER.encodedSizeWithTag(71, value.modal)
        size += BoxComponent.ADAPTER.encodedSizeWithTag(23, value.box)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ComponentDef) {
        if (value.id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.id)
        }
        TextComponent.ADAPTER.encodeWithTag(writer, 10, value.text)
        IconComponent.ADAPTER.encodeWithTag(writer, 11, value.icon)
        ImageComponent.ADAPTER.encodeWithTag(writer, 12, value.image)
        DividerComponent.ADAPTER.encodeWithTag(writer, 13, value.divider)
        ColumnComponent.ADAPTER.encodeWithTag(writer, 20, value.column)
        RowComponent.ADAPTER.encodeWithTag(writer, 21, value.row)
        CardComponent.ADAPTER.encodeWithTag(writer, 22, value.card)
        ScaffoldComponent.ADAPTER.encodeWithTag(writer, 30, value.scaffold)
        TopBarComponent.ADAPTER.encodeWithTag(writer, 31, value.top_bar)
        ButtonComponent.ADAPTER.encodeWithTag(writer, 40, value.button)
        ChipComponent.ADAPTER.encodeWithTag(writer, 41, value.chip)
        FabComponent.ADAPTER.encodeWithTag(writer, 42, value.fab)
        TextFieldComponent.ADAPTER.encodeWithTag(writer, 50, value.text_field)
        CheckBoxComponent.ADAPTER.encodeWithTag(writer, 51, value.check_box)
        SwitchComponent.ADAPTER.encodeWithTag(writer, 52, value.switch_toggle)
        SliderComponent.ADAPTER.encodeWithTag(writer, 53, value.slider)
        TabsComponent.ADAPTER.encodeWithTag(writer, 54, value.tabs)
        SelectComponent.ADAPTER.encodeWithTag(writer, 55, value.select)
        DateTimeInputComponent.ADAPTER.encodeWithTag(writer, 56, value.date_time_input)
        ListComponent.ADAPTER.encodeWithTag(writer, 60, value.list)
        ListItemComponent.ADAPTER.encodeWithTag(writer, 61, value.list_item)
        ProgressRingComponent.ADAPTER.encodeWithTag(writer, 72, value.progress_ring)
        ProgressBarComponent.ADAPTER.encodeWithTag(writer, 73, value.progress_bar)
        ModalComponent.ADAPTER.encodeWithTag(writer, 71, value.modal)
        BoxComponent.ADAPTER.encodeWithTag(writer, 23, value.box)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ComponentDef) {
        writer.writeBytes(value.unknownFields)
        BoxComponent.ADAPTER.encodeWithTag(writer, 23, value.box)
        ModalComponent.ADAPTER.encodeWithTag(writer, 71, value.modal)
        ProgressBarComponent.ADAPTER.encodeWithTag(writer, 73, value.progress_bar)
        ProgressRingComponent.ADAPTER.encodeWithTag(writer, 72, value.progress_ring)
        ListItemComponent.ADAPTER.encodeWithTag(writer, 61, value.list_item)
        ListComponent.ADAPTER.encodeWithTag(writer, 60, value.list)
        DateTimeInputComponent.ADAPTER.encodeWithTag(writer, 56, value.date_time_input)
        SelectComponent.ADAPTER.encodeWithTag(writer, 55, value.select)
        TabsComponent.ADAPTER.encodeWithTag(writer, 54, value.tabs)
        SliderComponent.ADAPTER.encodeWithTag(writer, 53, value.slider)
        SwitchComponent.ADAPTER.encodeWithTag(writer, 52, value.switch_toggle)
        CheckBoxComponent.ADAPTER.encodeWithTag(writer, 51, value.check_box)
        TextFieldComponent.ADAPTER.encodeWithTag(writer, 50, value.text_field)
        FabComponent.ADAPTER.encodeWithTag(writer, 42, value.fab)
        ChipComponent.ADAPTER.encodeWithTag(writer, 41, value.chip)
        ButtonComponent.ADAPTER.encodeWithTag(writer, 40, value.button)
        TopBarComponent.ADAPTER.encodeWithTag(writer, 31, value.top_bar)
        ScaffoldComponent.ADAPTER.encodeWithTag(writer, 30, value.scaffold)
        CardComponent.ADAPTER.encodeWithTag(writer, 22, value.card)
        RowComponent.ADAPTER.encodeWithTag(writer, 21, value.row)
        ColumnComponent.ADAPTER.encodeWithTag(writer, 20, value.column)
        DividerComponent.ADAPTER.encodeWithTag(writer, 13, value.divider)
        ImageComponent.ADAPTER.encodeWithTag(writer, 12, value.image)
        IconComponent.ADAPTER.encodeWithTag(writer, 11, value.icon)
        TextComponent.ADAPTER.encodeWithTag(writer, 10, value.text)
        if (value.id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.id)
        }
      }

      override fun decode(reader: ProtoReader): ComponentDef {
        var id: String = ""
        var text: TextComponent? = null
        var icon: IconComponent? = null
        var image: ImageComponent? = null
        var divider: DividerComponent? = null
        var column: ColumnComponent? = null
        var row: RowComponent? = null
        var card: CardComponent? = null
        var scaffold: ScaffoldComponent? = null
        var top_bar: TopBarComponent? = null
        var button: ButtonComponent? = null
        var chip: ChipComponent? = null
        var fab: FabComponent? = null
        var text_field: TextFieldComponent? = null
        var check_box: CheckBoxComponent? = null
        var switch_toggle: SwitchComponent? = null
        var slider: SliderComponent? = null
        var tabs: TabsComponent? = null
        var select: SelectComponent? = null
        var date_time_input: DateTimeInputComponent? = null
        var list: ListComponent? = null
        var list_item: ListItemComponent? = null
        var progress_ring: ProgressRingComponent? = null
        var progress_bar: ProgressBarComponent? = null
        var modal: ModalComponent? = null
        var box: BoxComponent? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> id = ProtoAdapter.STRING.decode(reader)
            10 -> text = TextComponent.ADAPTER.decode(reader)
            11 -> icon = IconComponent.ADAPTER.decode(reader)
            12 -> image = ImageComponent.ADAPTER.decode(reader)
            13 -> divider = DividerComponent.ADAPTER.decode(reader)
            20 -> column = ColumnComponent.ADAPTER.decode(reader)
            21 -> row = RowComponent.ADAPTER.decode(reader)
            22 -> card = CardComponent.ADAPTER.decode(reader)
            30 -> scaffold = ScaffoldComponent.ADAPTER.decode(reader)
            31 -> top_bar = TopBarComponent.ADAPTER.decode(reader)
            40 -> button = ButtonComponent.ADAPTER.decode(reader)
            41 -> chip = ChipComponent.ADAPTER.decode(reader)
            42 -> fab = FabComponent.ADAPTER.decode(reader)
            50 -> text_field = TextFieldComponent.ADAPTER.decode(reader)
            51 -> check_box = CheckBoxComponent.ADAPTER.decode(reader)
            52 -> switch_toggle = SwitchComponent.ADAPTER.decode(reader)
            53 -> slider = SliderComponent.ADAPTER.decode(reader)
            54 -> tabs = TabsComponent.ADAPTER.decode(reader)
            55 -> select = SelectComponent.ADAPTER.decode(reader)
            56 -> date_time_input = DateTimeInputComponent.ADAPTER.decode(reader)
            60 -> list = ListComponent.ADAPTER.decode(reader)
            61 -> list_item = ListItemComponent.ADAPTER.decode(reader)
            72 -> progress_ring = ProgressRingComponent.ADAPTER.decode(reader)
            73 -> progress_bar = ProgressBarComponent.ADAPTER.decode(reader)
            71 -> modal = ModalComponent.ADAPTER.decode(reader)
            23 -> box = BoxComponent.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ComponentDef(
          id = id,
          text = text,
          icon = icon,
          image = image,
          divider = divider,
          column = column,
          row = row,
          card = card,
          scaffold = scaffold,
          top_bar = top_bar,
          button = button,
          chip = chip,
          fab = fab,
          text_field = text_field,
          check_box = check_box,
          switch_toggle = switch_toggle,
          slider = slider,
          tabs = tabs,
          select = select,
          date_time_input = date_time_input,
          list = list,
          list_item = list_item,
          progress_ring = progress_ring,
          progress_bar = progress_bar,
          modal = modal,
          box = box,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ComponentDef): ComponentDef = value.copy(
        text = value.text?.let(TextComponent.ADAPTER::redact),
        icon = value.icon?.let(IconComponent.ADAPTER::redact),
        image = value.image?.let(ImageComponent.ADAPTER::redact),
        divider = value.divider?.let(DividerComponent.ADAPTER::redact),
        column = value.column?.let(ColumnComponent.ADAPTER::redact),
        row = value.row?.let(RowComponent.ADAPTER::redact),
        card = value.card?.let(CardComponent.ADAPTER::redact),
        scaffold = value.scaffold?.let(ScaffoldComponent.ADAPTER::redact),
        top_bar = value.top_bar?.let(TopBarComponent.ADAPTER::redact),
        button = value.button?.let(ButtonComponent.ADAPTER::redact),
        chip = value.chip?.let(ChipComponent.ADAPTER::redact),
        fab = value.fab?.let(FabComponent.ADAPTER::redact),
        text_field = value.text_field?.let(TextFieldComponent.ADAPTER::redact),
        check_box = value.check_box?.let(CheckBoxComponent.ADAPTER::redact),
        switch_toggle = value.switch_toggle?.let(SwitchComponent.ADAPTER::redact),
        slider = value.slider?.let(SliderComponent.ADAPTER::redact),
        tabs = value.tabs?.let(TabsComponent.ADAPTER::redact),
        select = value.select?.let(SelectComponent.ADAPTER::redact),
        date_time_input = value.date_time_input?.let(DateTimeInputComponent.ADAPTER::redact),
        list = value.list?.let(ListComponent.ADAPTER::redact),
        list_item = value.list_item?.let(ListItemComponent.ADAPTER::redact),
        progress_ring = value.progress_ring?.let(ProgressRingComponent.ADAPTER::redact),
        progress_bar = value.progress_bar?.let(ProgressBarComponent.ADAPTER::redact),
        modal = value.modal?.let(ModalComponent.ADAPTER::redact),
        box = value.box?.let(BoxComponent.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<ComponentDef> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
