// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.DeviceClass in moumantai/v1/enums.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int
import kotlin.Suppress

/**
 * ---------------------------------------------------------------------------
 * Device descriptors
 * ---------------------------------------------------------------------------
 * Device form-factor classes.
 */
public enum class DeviceClass(
  override val `value`: Int,
) : WireEnum {
  DEVICE_CLASS_UNSPECIFIED(0),
  DEVICE_CLASS_PHONE(1),
  DEVICE_CLASS_WATCH(2),
  DEVICE_CLASS_GLASS(3),
  DEVICE_CLASS_IOT_SMALL(4),
  DEVICE_CLASS_HMI_PANEL(5),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<DeviceClass> = object : EnumAdapter<DeviceClass>(
      DeviceClass::class, 
      PROTO_3, 
      DeviceClass.DEVICE_CLASS_UNSPECIFIED
    ) {
      override fun fromValue(`value`: Int): DeviceClass? = DeviceClass.fromValue(`value`)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): DeviceClass? = when (`value`) {
      0 -> DEVICE_CLASS_UNSPECIFIED
      1 -> DEVICE_CLASS_PHONE
      2 -> DEVICE_CLASS_WATCH
      3 -> DEVICE_CLASS_GLASS
      4 -> DEVICE_CLASS_IOT_SMALL
      5 -> DEVICE_CLASS_HMI_PANEL
      else -> null
    }
  }
}
