// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.DividerComponent in moumantai/v1/components.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Visual separator line.
 */
public class DividerComponent(
  /**
   * Line thickness (dp).
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    schemaIndex = 0,
  )
  public val thickness: Int? = null,
  /**
   * Color token or hex.
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 1,
  )
  public val color: String? = null,
  @field:WireField(
    tag = 200,
    adapter = "com.moumantai.protocol.v1.Modifier#ADAPTER",
    schemaIndex = 2,
  )
  public val modifier: Modifier? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<DividerComponent, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is DividerComponent) return false
    if (unknownFields != other.unknownFields) return false
    if (thickness != other.thickness) return false
    if (color != other.color) return false
    if (modifier != other.modifier) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (thickness?.hashCode() ?: 0)
      result = result * 37 + (color?.hashCode() ?: 0)
      result = result * 37 + (modifier?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (thickness != null) result += """thickness=$thickness"""
    if (color != null) result += """color=${sanitize(color)}"""
    if (modifier != null) result += """modifier=$modifier"""
    return result.joinToString(prefix = "DividerComponent{", separator = ", ", postfix = "}")
  }

  public fun copy(
    thickness: Int? = this.thickness,
    color: String? = this.color,
    modifier: Modifier? = this.modifier,
    unknownFields: ByteString = this.unknownFields,
  ): DividerComponent = DividerComponent(thickness, color, modifier, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<DividerComponent> = object : ProtoAdapter<DividerComponent>(
      FieldEncoding.LENGTH_DELIMITED, 
      DividerComponent::class, 
      "type.googleapis.com/moumantai.v1.DividerComponent", 
      PROTO_3, 
      null, 
      "moumantai/v1/components.proto"
    ) {
      override fun encodedSize(`value`: DividerComponent): Int {
        var size = value.unknownFields.size
        size += ProtoAdapter.INT32.encodedSizeWithTag(1, value.thickness)
        size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.color)
        size += Modifier.ADAPTER.encodedSizeWithTag(200, value.modifier)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: DividerComponent) {
        ProtoAdapter.INT32.encodeWithTag(writer, 1, value.thickness)
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.color)
        Modifier.ADAPTER.encodeWithTag(writer, 200, value.modifier)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: DividerComponent) {
        writer.writeBytes(value.unknownFields)
        Modifier.ADAPTER.encodeWithTag(writer, 200, value.modifier)
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.color)
        ProtoAdapter.INT32.encodeWithTag(writer, 1, value.thickness)
      }

      override fun decode(reader: ProtoReader): DividerComponent {
        var thickness: Int? = null
        var color: String? = null
        var modifier: Modifier? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> thickness = ProtoAdapter.INT32.decode(reader)
            2 -> color = ProtoAdapter.STRING.decode(reader)
            200 -> modifier = Modifier.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return DividerComponent(
          thickness = thickness,
          color = color,
          modifier = modifier,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: DividerComponent): DividerComponent = value.copy(
        modifier = value.modifier?.let(Modifier.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<DividerComponent> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
