// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.DraftStatus in moumantai/v1/drafts.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int
import kotlin.Suppress

/**
 * Lifecycle status carried by `DraftStateChanged`.
 */
public enum class DraftStatus(
  override val `value`: Int,
) : WireEnum {
  DRAFT_STATUS_UNSPECIFIED(0),
  DRAFT_STATUS_CREATED(1),
  DRAFT_STATUS_UPDATED(2),
  DRAFT_STATUS_PROMOTED(3),
  DRAFT_STATUS_DISCARDED(4),
  DRAFT_STATUS_FAILED(5),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<DraftStatus> = object : EnumAdapter<DraftStatus>(
      DraftStatus::class, 
      PROTO_3, 
      DraftStatus.DRAFT_STATUS_UNSPECIFIED
    ) {
      override fun fromValue(`value`: Int): DraftStatus? = DraftStatus.fromValue(`value`)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): DraftStatus? = when (`value`) {
      0 -> DRAFT_STATUS_UNSPECIFIED
      1 -> DRAFT_STATUS_CREATED
      2 -> DRAFT_STATUS_UPDATED
      3 -> DRAFT_STATUS_PROMOTED
      4 -> DRAFT_STATUS_DISCARDED
      5 -> DRAFT_STATUS_FAILED
      else -> null
    }
  }
}
