// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.DynamicBool in moumantai/v1/dynamic.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.countNonNull
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Either a literal bool or a JSON-Pointer path resolved at render time.
 */
public class DynamicBool(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    oneofName = "value",
    schemaIndex = 0,
  )
  public val literal: Boolean? = null,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    oneofName = "value",
    schemaIndex = 1,
  )
  public val path: String? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<DynamicBool, Nothing>(ADAPTER, unknownFields) {
  init {
    require(countNonNull(literal, path) <= 1) {
      "At most one of literal, path may be non-null"
    }
  }

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is DynamicBool) return false
    if (unknownFields != other.unknownFields) return false
    if (literal != other.literal) return false
    if (path != other.path) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (literal?.hashCode() ?: 0)
      result = result * 37 + (path?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (literal != null) result += """literal=$literal"""
    if (path != null) result += """path=${sanitize(path)}"""
    return result.joinToString(prefix = "DynamicBool{", separator = ", ", postfix = "}")
  }

  public fun copy(
    literal: Boolean? = this.literal,
    path: String? = this.path,
    unknownFields: ByteString = this.unknownFields,
  ): DynamicBool = DynamicBool(literal, path, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<DynamicBool> = object : ProtoAdapter<DynamicBool>(
      FieldEncoding.LENGTH_DELIMITED, 
      DynamicBool::class, 
      "type.googleapis.com/moumantai.v1.DynamicBool", 
      PROTO_3, 
      null, 
      "moumantai/v1/dynamic.proto"
    ) {
      override fun encodedSize(`value`: DynamicBool): Int {
        var size = value.unknownFields.size
        size += ProtoAdapter.BOOL.encodedSizeWithTag(1, value.literal)
        size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.path)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: DynamicBool) {
        ProtoAdapter.BOOL.encodeWithTag(writer, 1, value.literal)
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.path)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: DynamicBool) {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.path)
        ProtoAdapter.BOOL.encodeWithTag(writer, 1, value.literal)
      }

      override fun decode(reader: ProtoReader): DynamicBool {
        var literal: Boolean? = null
        var path: String? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> literal = ProtoAdapter.BOOL.decode(reader)
            2 -> path = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return DynamicBool(
          literal = literal,
          path = path,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: DynamicBool): DynamicBool = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<DynamicBool> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
