// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.FaceInfo in moumantai/v1/apps.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * ---------------------------------------------------------------------------
 * Face descriptors
 * ---------------------------------------------------------------------------
 * Describes a face within an app for the vertical pager.
 */
public class FaceInfo(
  /**
   * Face id (lowercase). Unique within the parent app.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "faceId",
    schemaIndex = 0,
  )
  public val face_id: String = "",
  /**
   * Display label.
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val label: String = "",
  /**
   * Pager position (0-indexed).
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val position: Int = 0,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<FaceInfo, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is FaceInfo) return false
    if (unknownFields != other.unknownFields) return false
    if (face_id != other.face_id) return false
    if (label != other.label) return false
    if (position != other.position) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + face_id.hashCode()
      result = result * 37 + label.hashCode()
      result = result * 37 + position.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """face_id=${sanitize(face_id)}"""
    result += """label=${sanitize(label)}"""
    result += """position=$position"""
    return result.joinToString(prefix = "FaceInfo{", separator = ", ", postfix = "}")
  }

  public fun copy(
    face_id: String = this.face_id,
    label: String = this.label,
    position: Int = this.position,
    unknownFields: ByteString = this.unknownFields,
  ): FaceInfo = FaceInfo(face_id, label, position, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<FaceInfo> = object : ProtoAdapter<FaceInfo>(
      FieldEncoding.LENGTH_DELIMITED, 
      FaceInfo::class, 
      "type.googleapis.com/moumantai.v1.FaceInfo", 
      PROTO_3, 
      null, 
      "moumantai/v1/apps.proto"
    ) {
      override fun encodedSize(`value`: FaceInfo): Int {
        var size = value.unknownFields.size
        if (value.face_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.face_id)
        }
        if (value.label != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.label)
        }
        if (value.position != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(3, value.position)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: FaceInfo) {
        if (value.face_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.face_id)
        }
        if (value.label != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.label)
        }
        if (value.position != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.position)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: FaceInfo) {
        writer.writeBytes(value.unknownFields)
        if (value.position != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.position)
        }
        if (value.label != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.label)
        }
        if (value.face_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.face_id)
        }
      }

      override fun decode(reader: ProtoReader): FaceInfo {
        var face_id: String = ""
        var label: String = ""
        var position: Int = 0
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> face_id = ProtoAdapter.STRING.decode(reader)
            2 -> label = ProtoAdapter.STRING.decode(reader)
            3 -> position = ProtoAdapter.INT32.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return FaceInfo(
          face_id = face_id,
          label = label,
          position = position,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: FaceInfo): FaceInfo = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<FaceInfo> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
