// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.IconComponent in moumantai/v1/components.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Material Symbols icon (or 'fa:<name>' fallback).
 */
public class IconComponent(
  /**
   * Icon name (e.g. "check_circle"); 'fa:' prefix selects FontAwesome Free.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.moumantai.protocol.v1.DynamicString#ADAPTER",
    schemaIndex = 0,
  )
  public val name: DynamicString? = null,
  /**
   * Icon size (dp).
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    schemaIndex = 1,
  )
  public val size: Int? = null,
  /**
   * Color token or hex (may be path-resolved).
   */
  @field:WireField(
    tag = 3,
    adapter = "com.moumantai.protocol.v1.DynamicString#ADAPTER",
    schemaIndex = 2,
  )
  public val color: DynamicString? = null,
  /**
   * Optional click action.
   */
  @field:WireField(
    tag = 4,
    adapter = "com.moumantai.protocol.v1.Action#ADAPTER",
    schemaIndex = 3,
  )
  public val action: Action? = null,
  @field:WireField(
    tag = 200,
    adapter = "com.moumantai.protocol.v1.Modifier#ADAPTER",
    schemaIndex = 4,
  )
  public val modifier: Modifier? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<IconComponent, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is IconComponent) return false
    if (unknownFields != other.unknownFields) return false
    if (name != other.name) return false
    if (size != other.size) return false
    if (color != other.color) return false
    if (action != other.action) return false
    if (modifier != other.modifier) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (name?.hashCode() ?: 0)
      result = result * 37 + (size?.hashCode() ?: 0)
      result = result * 37 + (color?.hashCode() ?: 0)
      result = result * 37 + (action?.hashCode() ?: 0)
      result = result * 37 + (modifier?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (name != null) result += """name=$name"""
    if (size != null) result += """size=$size"""
    if (color != null) result += """color=$color"""
    if (action != null) result += """action=$action"""
    if (modifier != null) result += """modifier=$modifier"""
    return result.joinToString(prefix = "IconComponent{", separator = ", ", postfix = "}")
  }

  public fun copy(
    name: DynamicString? = this.name,
    size: Int? = this.size,
    color: DynamicString? = this.color,
    action: Action? = this.action,
    modifier: Modifier? = this.modifier,
    unknownFields: ByteString = this.unknownFields,
  ): IconComponent = IconComponent(name, size, color, action, modifier, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<IconComponent> = object : ProtoAdapter<IconComponent>(
      FieldEncoding.LENGTH_DELIMITED, 
      IconComponent::class, 
      "type.googleapis.com/moumantai.v1.IconComponent", 
      PROTO_3, 
      null, 
      "moumantai/v1/components.proto"
    ) {
      override fun encodedSize(`value`: IconComponent): Int {
        var size_ = value.unknownFields.size
        size_ += DynamicString.ADAPTER.encodedSizeWithTag(1, value.name)
        size_ += ProtoAdapter.INT32.encodedSizeWithTag(2, value.size)
        size_ += DynamicString.ADAPTER.encodedSizeWithTag(3, value.color)
        size_ += Action.ADAPTER.encodedSizeWithTag(4, value.action)
        size_ += Modifier.ADAPTER.encodedSizeWithTag(200, value.modifier)
        return size_
      }

      override fun encode(writer: ProtoWriter, `value`: IconComponent) {
        DynamicString.ADAPTER.encodeWithTag(writer, 1, value.name)
        ProtoAdapter.INT32.encodeWithTag(writer, 2, value.size)
        DynamicString.ADAPTER.encodeWithTag(writer, 3, value.color)
        Action.ADAPTER.encodeWithTag(writer, 4, value.action)
        Modifier.ADAPTER.encodeWithTag(writer, 200, value.modifier)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: IconComponent) {
        writer.writeBytes(value.unknownFields)
        Modifier.ADAPTER.encodeWithTag(writer, 200, value.modifier)
        Action.ADAPTER.encodeWithTag(writer, 4, value.action)
        DynamicString.ADAPTER.encodeWithTag(writer, 3, value.color)
        ProtoAdapter.INT32.encodeWithTag(writer, 2, value.size)
        DynamicString.ADAPTER.encodeWithTag(writer, 1, value.name)
      }

      override fun decode(reader: ProtoReader): IconComponent {
        var name: DynamicString? = null
        var size: Int? = null
        var color: DynamicString? = null
        var action: Action? = null
        var modifier: Modifier? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> name = DynamicString.ADAPTER.decode(reader)
            2 -> size = ProtoAdapter.INT32.decode(reader)
            3 -> color = DynamicString.ADAPTER.decode(reader)
            4 -> action = Action.ADAPTER.decode(reader)
            200 -> modifier = Modifier.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return IconComponent(
          name = name,
          size = size,
          color = color,
          action = action,
          modifier = modifier,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: IconComponent): IconComponent = value.copy(
        name = value.name?.let(DynamicString.ADAPTER::redact),
        color = value.color?.let(DynamicString.ADAPTER::redact),
        action = value.action?.let(Action.ADAPTER::redact),
        modifier = value.modifier?.let(Modifier.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<IconComponent> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
