// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.ImageComponent in moumantai/v1/components.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Image from a URL.
 */
public class ImageComponent(
  /**
   * Image URL (may be path-resolved).
   */
  @field:WireField(
    tag = 1,
    adapter = "com.moumantai.protocol.v1.DynamicString#ADAPTER",
    schemaIndex = 0,
  )
  public val src: DynamicString? = null,
  /**
   * Alt text for accessibility.
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 1,
  )
  public val alt: String? = null,
  /**
   * Object-fit mode.
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 2,
  )
  public val fit: String? = null,
  @field:WireField(
    tag = 200,
    adapter = "com.moumantai.protocol.v1.Modifier#ADAPTER",
    schemaIndex = 3,
  )
  public val modifier: Modifier? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<ImageComponent, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ImageComponent) return false
    if (unknownFields != other.unknownFields) return false
    if (src != other.src) return false
    if (alt != other.alt) return false
    if (fit != other.fit) return false
    if (modifier != other.modifier) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (src?.hashCode() ?: 0)
      result = result * 37 + (alt?.hashCode() ?: 0)
      result = result * 37 + (fit?.hashCode() ?: 0)
      result = result * 37 + (modifier?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (src != null) result += """src=$src"""
    if (alt != null) result += """alt=${sanitize(alt)}"""
    if (fit != null) result += """fit=${sanitize(fit)}"""
    if (modifier != null) result += """modifier=$modifier"""
    return result.joinToString(prefix = "ImageComponent{", separator = ", ", postfix = "}")
  }

  public fun copy(
    src: DynamicString? = this.src,
    alt: String? = this.alt,
    fit: String? = this.fit,
    modifier: Modifier? = this.modifier,
    unknownFields: ByteString = this.unknownFields,
  ): ImageComponent = ImageComponent(src, alt, fit, modifier, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ImageComponent> = object : ProtoAdapter<ImageComponent>(
      FieldEncoding.LENGTH_DELIMITED, 
      ImageComponent::class, 
      "type.googleapis.com/moumantai.v1.ImageComponent", 
      PROTO_3, 
      null, 
      "moumantai/v1/components.proto"
    ) {
      override fun encodedSize(`value`: ImageComponent): Int {
        var size = value.unknownFields.size
        size += DynamicString.ADAPTER.encodedSizeWithTag(1, value.src)
        size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.alt)
        size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.fit)
        size += Modifier.ADAPTER.encodedSizeWithTag(200, value.modifier)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ImageComponent) {
        DynamicString.ADAPTER.encodeWithTag(writer, 1, value.src)
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.alt)
        ProtoAdapter.STRING.encodeWithTag(writer, 3, value.fit)
        Modifier.ADAPTER.encodeWithTag(writer, 200, value.modifier)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ImageComponent) {
        writer.writeBytes(value.unknownFields)
        Modifier.ADAPTER.encodeWithTag(writer, 200, value.modifier)
        ProtoAdapter.STRING.encodeWithTag(writer, 3, value.fit)
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.alt)
        DynamicString.ADAPTER.encodeWithTag(writer, 1, value.src)
      }

      override fun decode(reader: ProtoReader): ImageComponent {
        var src: DynamicString? = null
        var alt: String? = null
        var fit: String? = null
        var modifier: Modifier? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> src = DynamicString.ADAPTER.decode(reader)
            2 -> alt = ProtoAdapter.STRING.decode(reader)
            3 -> fit = ProtoAdapter.STRING.decode(reader)
            200 -> modifier = Modifier.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ImageComponent(
          src = src,
          alt = alt,
          fit = fit,
          modifier = modifier,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ImageComponent): ImageComponent = value.copy(
        src = value.src?.let(DynamicString.ADAPTER::redact),
        modifier = value.modifier?.let(Modifier.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<ImageComponent> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
