// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.Modifier in moumantai/v1/components.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Double
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * ---------------------------------------------------------------------------
 * Modifier — shared across every component variant
 * ---------------------------------------------------------------------------
 * Common modifier props applied to every component (field 200 in every variant).
 */
public class Modifier(
  /**
   * Padding around the component (single value applied to all four edges, or
   * per-edge via PaddingEdges).
   */
  @field:WireField(
    tag = 1,
    adapter = "com.moumantai.protocol.v1.Dimension#ADAPTER",
    schemaIndex = 0,
  )
  public val padding: Dimension? = null,
  /**
   * Explicit width (dp) or auto-sentinel.
   */
  @field:WireField(
    tag = 2,
    adapter = "com.moumantai.protocol.v1.Dimension#ADAPTER",
    schemaIndex = 1,
  )
  public val width: Dimension? = null,
  /**
   * Explicit height (dp) or auto-sentinel.
   */
  @field:WireField(
    tag = 3,
    adapter = "com.moumantai.protocol.v1.Dimension#ADAPTER",
    schemaIndex = 2,
  )
  public val height: Dimension? = null,
  /**
   * Background fill — either a literal CSS color / token or a path-resolved
   * value at render time.
   */
  @field:WireField(
    tag = 4,
    adapter = "com.moumantai.protocol.v1.DynamicString#ADAPTER",
    schemaIndex = 3,
  )
  public val background: DynamicString? = null,
  /**
   * Visibility gate — when present and resolves to false, the component is
   * skipped at render time.
   */
  @field:WireField(
    tag = 5,
    adapter = "com.moumantai.protocol.v1.DynamicBool#ADAPTER",
    schemaIndex = 4,
  )
  public val visible: DynamicBool? = null,
  /**
   * Flex weight inside parent Column / Row (relative ratio).
   */
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#DOUBLE",
    schemaIndex = 5,
  )
  public val weight: Double? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<Modifier, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is Modifier) return false
    if (unknownFields != other.unknownFields) return false
    if (padding != other.padding) return false
    if (width != other.width) return false
    if (height != other.height) return false
    if (background != other.background) return false
    if (visible != other.visible) return false
    if (weight != other.weight) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (padding?.hashCode() ?: 0)
      result = result * 37 + (width?.hashCode() ?: 0)
      result = result * 37 + (height?.hashCode() ?: 0)
      result = result * 37 + (background?.hashCode() ?: 0)
      result = result * 37 + (visible?.hashCode() ?: 0)
      result = result * 37 + (weight?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (padding != null) result += """padding=$padding"""
    if (width != null) result += """width=$width"""
    if (height != null) result += """height=$height"""
    if (background != null) result += """background=$background"""
    if (visible != null) result += """visible=$visible"""
    if (weight != null) result += """weight=$weight"""
    return result.joinToString(prefix = "Modifier{", separator = ", ", postfix = "}")
  }

  public fun copy(
    padding: Dimension? = this.padding,
    width: Dimension? = this.width,
    height: Dimension? = this.height,
    background: DynamicString? = this.background,
    visible: DynamicBool? = this.visible,
    weight: Double? = this.weight,
    unknownFields: ByteString = this.unknownFields,
  ): Modifier = Modifier(padding, width, height, background, visible, weight, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<Modifier> = object : ProtoAdapter<Modifier>(
      FieldEncoding.LENGTH_DELIMITED, 
      Modifier::class, 
      "type.googleapis.com/moumantai.v1.Modifier", 
      PROTO_3, 
      null, 
      "moumantai/v1/components.proto"
    ) {
      override fun encodedSize(`value`: Modifier): Int {
        var size = value.unknownFields.size
        size += Dimension.ADAPTER.encodedSizeWithTag(1, value.padding)
        size += Dimension.ADAPTER.encodedSizeWithTag(2, value.width)
        size += Dimension.ADAPTER.encodedSizeWithTag(3, value.height)
        size += DynamicString.ADAPTER.encodedSizeWithTag(4, value.background)
        size += DynamicBool.ADAPTER.encodedSizeWithTag(5, value.visible)
        size += ProtoAdapter.DOUBLE.encodedSizeWithTag(6, value.weight)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: Modifier) {
        Dimension.ADAPTER.encodeWithTag(writer, 1, value.padding)
        Dimension.ADAPTER.encodeWithTag(writer, 2, value.width)
        Dimension.ADAPTER.encodeWithTag(writer, 3, value.height)
        DynamicString.ADAPTER.encodeWithTag(writer, 4, value.background)
        DynamicBool.ADAPTER.encodeWithTag(writer, 5, value.visible)
        ProtoAdapter.DOUBLE.encodeWithTag(writer, 6, value.weight)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: Modifier) {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.DOUBLE.encodeWithTag(writer, 6, value.weight)
        DynamicBool.ADAPTER.encodeWithTag(writer, 5, value.visible)
        DynamicString.ADAPTER.encodeWithTag(writer, 4, value.background)
        Dimension.ADAPTER.encodeWithTag(writer, 3, value.height)
        Dimension.ADAPTER.encodeWithTag(writer, 2, value.width)
        Dimension.ADAPTER.encodeWithTag(writer, 1, value.padding)
      }

      override fun decode(reader: ProtoReader): Modifier {
        var padding: Dimension? = null
        var width: Dimension? = null
        var height: Dimension? = null
        var background: DynamicString? = null
        var visible: DynamicBool? = null
        var weight: Double? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> padding = Dimension.ADAPTER.decode(reader)
            2 -> width = Dimension.ADAPTER.decode(reader)
            3 -> height = Dimension.ADAPTER.decode(reader)
            4 -> background = DynamicString.ADAPTER.decode(reader)
            5 -> visible = DynamicBool.ADAPTER.decode(reader)
            6 -> weight = ProtoAdapter.DOUBLE.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return Modifier(
          padding = padding,
          width = width,
          height = height,
          background = background,
          visible = visible,
          weight = weight,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: Modifier): Modifier = value.copy(
        padding = value.padding?.let(Dimension.ADAPTER::redact),
        width = value.width?.let(Dimension.ADAPTER::redact),
        height = value.height?.let(Dimension.ADAPTER::redact),
        background = value.background?.let(DynamicString.ADAPTER::redact),
        visible = value.visible?.let(DynamicBool.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<Modifier> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
