// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.PaddingEdges in moumantai/v1/components.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Per-edge padding values (dp).
 */
public class PaddingEdges(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    schemaIndex = 0,
  )
  public val top: Int? = null,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    schemaIndex = 1,
  )
  public val bottom: Int? = null,
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    schemaIndex = 2,
  )
  public val start: Int? = null,
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    schemaIndex = 3,
  )
  public val end: Int? = null,
  /**
   * Shorthand: horizontal → start+end; vertical → top+bottom.
   * Takes precedence over the per-edge fields above when set.
   */
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    schemaIndex = 4,
  )
  public val horizontal: Int? = null,
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    schemaIndex = 5,
  )
  public val vertical: Int? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<PaddingEdges, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is PaddingEdges) return false
    if (unknownFields != other.unknownFields) return false
    if (top != other.top) return false
    if (bottom != other.bottom) return false
    if (start != other.start) return false
    if (end != other.end) return false
    if (horizontal != other.horizontal) return false
    if (vertical != other.vertical) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (top?.hashCode() ?: 0)
      result = result * 37 + (bottom?.hashCode() ?: 0)
      result = result * 37 + (start?.hashCode() ?: 0)
      result = result * 37 + (end?.hashCode() ?: 0)
      result = result * 37 + (horizontal?.hashCode() ?: 0)
      result = result * 37 + (vertical?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (top != null) result += """top=$top"""
    if (bottom != null) result += """bottom=$bottom"""
    if (start != null) result += """start=$start"""
    if (end != null) result += """end=$end"""
    if (horizontal != null) result += """horizontal=$horizontal"""
    if (vertical != null) result += """vertical=$vertical"""
    return result.joinToString(prefix = "PaddingEdges{", separator = ", ", postfix = "}")
  }

  public fun copy(
    top: Int? = this.top,
    bottom: Int? = this.bottom,
    start: Int? = this.start,
    end: Int? = this.end,
    horizontal: Int? = this.horizontal,
    vertical: Int? = this.vertical,
    unknownFields: ByteString = this.unknownFields,
  ): PaddingEdges = PaddingEdges(top, bottom, start, end, horizontal, vertical, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<PaddingEdges> = object : ProtoAdapter<PaddingEdges>(
      FieldEncoding.LENGTH_DELIMITED, 
      PaddingEdges::class, 
      "type.googleapis.com/moumantai.v1.PaddingEdges", 
      PROTO_3, 
      null, 
      "moumantai/v1/components.proto"
    ) {
      override fun encodedSize(`value`: PaddingEdges): Int {
        var size = value.unknownFields.size
        size += ProtoAdapter.INT32.encodedSizeWithTag(1, value.top)
        size += ProtoAdapter.INT32.encodedSizeWithTag(2, value.bottom)
        size += ProtoAdapter.INT32.encodedSizeWithTag(3, value.start)
        size += ProtoAdapter.INT32.encodedSizeWithTag(4, value.end)
        size += ProtoAdapter.INT32.encodedSizeWithTag(5, value.horizontal)
        size += ProtoAdapter.INT32.encodedSizeWithTag(6, value.vertical)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: PaddingEdges) {
        ProtoAdapter.INT32.encodeWithTag(writer, 1, value.top)
        ProtoAdapter.INT32.encodeWithTag(writer, 2, value.bottom)
        ProtoAdapter.INT32.encodeWithTag(writer, 3, value.start)
        ProtoAdapter.INT32.encodeWithTag(writer, 4, value.end)
        ProtoAdapter.INT32.encodeWithTag(writer, 5, value.horizontal)
        ProtoAdapter.INT32.encodeWithTag(writer, 6, value.vertical)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: PaddingEdges) {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.INT32.encodeWithTag(writer, 6, value.vertical)
        ProtoAdapter.INT32.encodeWithTag(writer, 5, value.horizontal)
        ProtoAdapter.INT32.encodeWithTag(writer, 4, value.end)
        ProtoAdapter.INT32.encodeWithTag(writer, 3, value.start)
        ProtoAdapter.INT32.encodeWithTag(writer, 2, value.bottom)
        ProtoAdapter.INT32.encodeWithTag(writer, 1, value.top)
      }

      override fun decode(reader: ProtoReader): PaddingEdges {
        var top: Int? = null
        var bottom: Int? = null
        var start: Int? = null
        var end: Int? = null
        var horizontal: Int? = null
        var vertical: Int? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> top = ProtoAdapter.INT32.decode(reader)
            2 -> bottom = ProtoAdapter.INT32.decode(reader)
            3 -> start = ProtoAdapter.INT32.decode(reader)
            4 -> end = ProtoAdapter.INT32.decode(reader)
            5 -> horizontal = ProtoAdapter.INT32.decode(reader)
            6 -> vertical = ProtoAdapter.INT32.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return PaddingEdges(
          top = top,
          bottom = bottom,
          start = start,
          end = end,
          horizontal = horizontal,
          vertical = vertical,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: PaddingEdges): PaddingEdges = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<PaddingEdges> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
