// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.ProgressBarComponent in moumantai/v1/components.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Double
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Linear progress bar (fill-width, rounded ends).
 * Use ProgressRingComponent for circular indicators.
 */
public class ProgressBarComponent(
  /**
   * Current progress (typically 0..max).
   */
  @field:WireField(
    tag = 1,
    adapter = "com.moumantai.protocol.v1.DynamicDouble#ADAPTER",
    declaredName = "value",
    schemaIndex = 0,
  )
  public val value_: DynamicDouble? = null,
  /**
   * Maximum value (default: 100).
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#DOUBLE",
    schemaIndex = 1,
  )
  public val max: Double? = null,
  /**
   * Optional leading label.
   */
  @field:WireField(
    tag = 3,
    adapter = "com.moumantai.protocol.v1.DynamicString#ADAPTER",
    schemaIndex = 2,
  )
  public val label: DynamicString? = null,
  /**
   * Semantic color role: 'primary' (default) | 'secondary' | 'tertiary' |
   * 'error' | 'warning' | 'info'.
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 3,
  )
  public val color: String? = null,
  @field:WireField(
    tag = 200,
    adapter = "com.moumantai.protocol.v1.Modifier#ADAPTER",
    schemaIndex = 4,
  )
  public val modifier: Modifier? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<ProgressBarComponent, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ProgressBarComponent) return false
    if (unknownFields != other.unknownFields) return false
    if (value_ != other.value_) return false
    if (max != other.max) return false
    if (label != other.label) return false
    if (color != other.color) return false
    if (modifier != other.modifier) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (value_?.hashCode() ?: 0)
      result = result * 37 + (max?.hashCode() ?: 0)
      result = result * 37 + (label?.hashCode() ?: 0)
      result = result * 37 + (color?.hashCode() ?: 0)
      result = result * 37 + (modifier?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (value_ != null) result += """value_=$value_"""
    if (max != null) result += """max=$max"""
    if (label != null) result += """label=$label"""
    if (color != null) result += """color=${sanitize(color)}"""
    if (modifier != null) result += """modifier=$modifier"""
    return result.joinToString(prefix = "ProgressBarComponent{", separator = ", ", postfix = "}")
  }

  public fun copy(
    value_: DynamicDouble? = this.value_,
    max: Double? = this.max,
    label: DynamicString? = this.label,
    color: String? = this.color,
    modifier: Modifier? = this.modifier,
    unknownFields: ByteString = this.unknownFields,
  ): ProgressBarComponent = ProgressBarComponent(value_, max, label, color, modifier, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ProgressBarComponent> = object :
        ProtoAdapter<ProgressBarComponent>(
      FieldEncoding.LENGTH_DELIMITED, 
      ProgressBarComponent::class, 
      "type.googleapis.com/moumantai.v1.ProgressBarComponent", 
      PROTO_3, 
      null, 
      "moumantai/v1/components.proto"
    ) {
      override fun encodedSize(`value`: ProgressBarComponent): Int {
        var size = value.unknownFields.size
        size += DynamicDouble.ADAPTER.encodedSizeWithTag(1, value.value_)
        size += ProtoAdapter.DOUBLE.encodedSizeWithTag(2, value.max)
        size += DynamicString.ADAPTER.encodedSizeWithTag(3, value.label)
        size += ProtoAdapter.STRING.encodedSizeWithTag(4, value.color)
        size += Modifier.ADAPTER.encodedSizeWithTag(200, value.modifier)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ProgressBarComponent) {
        DynamicDouble.ADAPTER.encodeWithTag(writer, 1, value.value_)
        ProtoAdapter.DOUBLE.encodeWithTag(writer, 2, value.max)
        DynamicString.ADAPTER.encodeWithTag(writer, 3, value.label)
        ProtoAdapter.STRING.encodeWithTag(writer, 4, value.color)
        Modifier.ADAPTER.encodeWithTag(writer, 200, value.modifier)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ProgressBarComponent) {
        writer.writeBytes(value.unknownFields)
        Modifier.ADAPTER.encodeWithTag(writer, 200, value.modifier)
        ProtoAdapter.STRING.encodeWithTag(writer, 4, value.color)
        DynamicString.ADAPTER.encodeWithTag(writer, 3, value.label)
        ProtoAdapter.DOUBLE.encodeWithTag(writer, 2, value.max)
        DynamicDouble.ADAPTER.encodeWithTag(writer, 1, value.value_)
      }

      override fun decode(reader: ProtoReader): ProgressBarComponent {
        var value_: DynamicDouble? = null
        var max: Double? = null
        var label: DynamicString? = null
        var color: String? = null
        var modifier: Modifier? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> value_ = DynamicDouble.ADAPTER.decode(reader)
            2 -> max = ProtoAdapter.DOUBLE.decode(reader)
            3 -> label = DynamicString.ADAPTER.decode(reader)
            4 -> color = ProtoAdapter.STRING.decode(reader)
            200 -> modifier = Modifier.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ProgressBarComponent(
          value_ = value_,
          max = max,
          label = label,
          color = color,
          modifier = modifier,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ProgressBarComponent): ProgressBarComponent = value.copy(
        value_ = value.value_?.let(DynamicDouble.ADAPTER::redact),
        label = value.label?.let(DynamicString.ADAPTER::redact),
        modifier = value.modifier?.let(Modifier.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<ProgressBarComponent> =
        AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
