// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.ResetNoticeMsg in moumantai/v1/lifecycle.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Server → client notice broadcast to every socket viewing the scope before
 * its conversation is reset. Clients suppress when
 * `requester_session_id == transport.current_session_id` (only other devices
 * need to surface a banner). Emitted before the empty `chatWindow` so the UI
 * can overlay a banner on the about-to-vanish history.
 */
public class ResetNoticeMsg(
  /**
   * 'home' or 'app:<app_id>' — scope whose conversation was reset.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val scope: String = "",
  /**
   * UUID of the NEW conversation that will follow in `chatWindow`.
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "conversationId",
    schemaIndex = 1,
  )
  public val conversation_id: String = "",
  /**
   * WebSocket session_id of the device that issued the reset.
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "requesterSessionId",
    schemaIndex = 2,
  )
  public val requester_session_id: String = "",
  /**
   * ISO-8601 timestamp of reset.
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val timestamp: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<ResetNoticeMsg, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ResetNoticeMsg) return false
    if (unknownFields != other.unknownFields) return false
    if (scope != other.scope) return false
    if (conversation_id != other.conversation_id) return false
    if (requester_session_id != other.requester_session_id) return false
    if (timestamp != other.timestamp) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + scope.hashCode()
      result = result * 37 + conversation_id.hashCode()
      result = result * 37 + requester_session_id.hashCode()
      result = result * 37 + timestamp.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """scope=${sanitize(scope)}"""
    result += """conversation_id=${sanitize(conversation_id)}"""
    result += """requester_session_id=${sanitize(requester_session_id)}"""
    result += """timestamp=${sanitize(timestamp)}"""
    return result.joinToString(prefix = "ResetNoticeMsg{", separator = ", ", postfix = "}")
  }

  public fun copy(
    scope: String = this.scope,
    conversation_id: String = this.conversation_id,
    requester_session_id: String = this.requester_session_id,
    timestamp: String = this.timestamp,
    unknownFields: ByteString = this.unknownFields,
  ): ResetNoticeMsg = ResetNoticeMsg(scope, conversation_id, requester_session_id, timestamp,
      unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ResetNoticeMsg> = object : ProtoAdapter<ResetNoticeMsg>(
      FieldEncoding.LENGTH_DELIMITED, 
      ResetNoticeMsg::class, 
      "type.googleapis.com/moumantai.v1.ResetNoticeMsg", 
      PROTO_3, 
      null, 
      "moumantai/v1/lifecycle.proto"
    ) {
      override fun encodedSize(`value`: ResetNoticeMsg): Int {
        var size = value.unknownFields.size
        if (value.scope != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.scope)
        }
        if (value.conversation_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.conversation_id)
        }
        if (value.requester_session_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.requester_session_id)
        }
        if (value.timestamp != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(4, value.timestamp)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ResetNoticeMsg) {
        if (value.scope != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.scope)
        }
        if (value.conversation_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.conversation_id)
        }
        if (value.requester_session_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.requester_session_id)
        }
        if (value.timestamp != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.timestamp)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ResetNoticeMsg) {
        writer.writeBytes(value.unknownFields)
        if (value.timestamp != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.timestamp)
        }
        if (value.requester_session_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.requester_session_id)
        }
        if (value.conversation_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.conversation_id)
        }
        if (value.scope != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.scope)
        }
      }

      override fun decode(reader: ProtoReader): ResetNoticeMsg {
        var scope: String = ""
        var conversation_id: String = ""
        var requester_session_id: String = ""
        var timestamp: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> scope = ProtoAdapter.STRING.decode(reader)
            2 -> conversation_id = ProtoAdapter.STRING.decode(reader)
            3 -> requester_session_id = ProtoAdapter.STRING.decode(reader)
            4 -> timestamp = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ResetNoticeMsg(
          scope = scope,
          conversation_id = conversation_id,
          requester_session_id = requester_session_id,
          timestamp = timestamp,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ResetNoticeMsg): ResetNoticeMsg = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<ResetNoticeMsg> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
