// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.ResetConversationMsg in moumantai/v1/lifecycle.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * ---------------------------------------------------------------------------
 * Conversation reset
 * ---------------------------------------------------------------------------
 * Client requests a non-destructive reset of a scope's conversation.
 * Server aborts any in-flight turn, archives the current conversation, and
 * starts a fresh one. Response: `ChatWindowMsg` with empty entries.
 */
public class ResetConversationMsg(
  /**
   * 'home' or 'app:<app_id>'.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val scope: String = "",
  /**
   * Thread to reset. Unset == CHAT_KIND_CHAT. CHAT_KIND_DEV resets the dev
   * conversation only — draft/worktree is preserved. Required because a
   * new-app draft uses scope 'home', identical to home chat.
   */
  @field:WireField(
    tag = 2,
    adapter = "com.moumantai.protocol.v1.ChatKind#ADAPTER",
    schemaIndex = 1,
  )
  public val kind: ChatKind? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<ResetConversationMsg, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ResetConversationMsg) return false
    if (unknownFields != other.unknownFields) return false
    if (scope != other.scope) return false
    if (kind != other.kind) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + scope.hashCode()
      result = result * 37 + (kind?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """scope=${sanitize(scope)}"""
    if (kind != null) result += """kind=$kind"""
    return result.joinToString(prefix = "ResetConversationMsg{", separator = ", ", postfix = "}")
  }

  public fun copy(
    scope: String = this.scope,
    kind: ChatKind? = this.kind,
    unknownFields: ByteString = this.unknownFields,
  ): ResetConversationMsg = ResetConversationMsg(scope, kind, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ResetConversationMsg> = object :
        ProtoAdapter<ResetConversationMsg>(
      FieldEncoding.LENGTH_DELIMITED, 
      ResetConversationMsg::class, 
      "type.googleapis.com/moumantai.v1.ResetConversationMsg", 
      PROTO_3, 
      null, 
      "moumantai/v1/lifecycle.proto"
    ) {
      override fun encodedSize(`value`: ResetConversationMsg): Int {
        var size = value.unknownFields.size
        if (value.scope != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.scope)
        }
        size += ChatKind.ADAPTER.encodedSizeWithTag(2, value.kind)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ResetConversationMsg) {
        if (value.scope != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.scope)
        }
        ChatKind.ADAPTER.encodeWithTag(writer, 2, value.kind)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ResetConversationMsg) {
        writer.writeBytes(value.unknownFields)
        ChatKind.ADAPTER.encodeWithTag(writer, 2, value.kind)
        if (value.scope != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.scope)
        }
      }

      override fun decode(reader: ProtoReader): ResetConversationMsg {
        var scope: String = ""
        var kind: ChatKind? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> scope = ProtoAdapter.STRING.decode(reader)
            2 -> try {
              kind = ChatKind.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            else -> reader.readUnknownField(tag)
          }
        }
        return ResetConversationMsg(
          scope = scope,
          kind = kind,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ResetConversationMsg): ResetConversationMsg = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<ResetConversationMsg> =
        AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
