// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.RowComponent in moumantai/v1/components.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

/**
 * Horizontal flex container.
 */
public class RowComponent(
  children: List<String> = emptyList(),
  /**
   * Inter-child spacing (dp).
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    schemaIndex = 1,
  )
  public val spacing: Int? = null,
  /**
   * Main-axis arrangement.
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    jsonName = "horizontalArrangement",
    schemaIndex = 2,
  )
  public val horizontal_arrangement: String? = null,
  /**
   * Cross-axis alignment for children.
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    jsonName = "verticalAlignment",
    schemaIndex = 3,
  )
  public val vertical_alignment: String? = null,
  @field:WireField(
    tag = 200,
    adapter = "com.moumantai.protocol.v1.Modifier#ADAPTER",
    schemaIndex = 4,
  )
  public val modifier: Modifier? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<RowComponent, Nothing>(ADAPTER, unknownFields) {
  /**
   * Children (component ids in order).
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    schemaIndex = 0,
  )
  public val children: List<String> = immutableCopyOf("children", children)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is RowComponent) return false
    if (unknownFields != other.unknownFields) return false
    if (children != other.children) return false
    if (spacing != other.spacing) return false
    if (horizontal_arrangement != other.horizontal_arrangement) return false
    if (vertical_alignment != other.vertical_alignment) return false
    if (modifier != other.modifier) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + children.hashCode()
      result = result * 37 + (spacing?.hashCode() ?: 0)
      result = result * 37 + (horizontal_arrangement?.hashCode() ?: 0)
      result = result * 37 + (vertical_alignment?.hashCode() ?: 0)
      result = result * 37 + (modifier?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (children.isNotEmpty()) result += """children=${sanitize(children)}"""
    if (spacing != null) result += """spacing=$spacing"""
    if (horizontal_arrangement != null) result +=
        """horizontal_arrangement=${sanitize(horizontal_arrangement)}"""
    if (vertical_alignment != null) result +=
        """vertical_alignment=${sanitize(vertical_alignment)}"""
    if (modifier != null) result += """modifier=$modifier"""
    return result.joinToString(prefix = "RowComponent{", separator = ", ", postfix = "}")
  }

  public fun copy(
    children: List<String> = this.children,
    spacing: Int? = this.spacing,
    horizontal_arrangement: String? = this.horizontal_arrangement,
    vertical_alignment: String? = this.vertical_alignment,
    modifier: Modifier? = this.modifier,
    unknownFields: ByteString = this.unknownFields,
  ): RowComponent = RowComponent(children, spacing, horizontal_arrangement, vertical_alignment,
      modifier, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<RowComponent> = object : ProtoAdapter<RowComponent>(
      FieldEncoding.LENGTH_DELIMITED, 
      RowComponent::class, 
      "type.googleapis.com/moumantai.v1.RowComponent", 
      PROTO_3, 
      null, 
      "moumantai/v1/components.proto"
    ) {
      override fun encodedSize(`value`: RowComponent): Int {
        var size = value.unknownFields.size
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(1, value.children)
        size += ProtoAdapter.INT32.encodedSizeWithTag(2, value.spacing)
        size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.horizontal_arrangement)
        size += ProtoAdapter.STRING.encodedSizeWithTag(4, value.vertical_alignment)
        size += Modifier.ADAPTER.encodedSizeWithTag(200, value.modifier)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: RowComponent) {
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 1, value.children)
        ProtoAdapter.INT32.encodeWithTag(writer, 2, value.spacing)
        ProtoAdapter.STRING.encodeWithTag(writer, 3, value.horizontal_arrangement)
        ProtoAdapter.STRING.encodeWithTag(writer, 4, value.vertical_alignment)
        Modifier.ADAPTER.encodeWithTag(writer, 200, value.modifier)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: RowComponent) {
        writer.writeBytes(value.unknownFields)
        Modifier.ADAPTER.encodeWithTag(writer, 200, value.modifier)
        ProtoAdapter.STRING.encodeWithTag(writer, 4, value.vertical_alignment)
        ProtoAdapter.STRING.encodeWithTag(writer, 3, value.horizontal_arrangement)
        ProtoAdapter.INT32.encodeWithTag(writer, 2, value.spacing)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 1, value.children)
      }

      override fun decode(reader: ProtoReader): RowComponent {
        val children = mutableListOf<String>()
        var spacing: Int? = null
        var horizontal_arrangement: String? = null
        var vertical_alignment: String? = null
        var modifier: Modifier? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> children.add(ProtoAdapter.STRING.decode(reader))
            2 -> spacing = ProtoAdapter.INT32.decode(reader)
            3 -> horizontal_arrangement = ProtoAdapter.STRING.decode(reader)
            4 -> vertical_alignment = ProtoAdapter.STRING.decode(reader)
            200 -> modifier = Modifier.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return RowComponent(
          children = children,
          spacing = spacing,
          horizontal_arrangement = horizontal_arrangement,
          vertical_alignment = vertical_alignment,
          modifier = modifier,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: RowComponent): RowComponent = value.copy(
        modifier = value.modifier?.let(Modifier.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<RowComponent> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
