// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.ScaffoldComponent in moumantai/v1/components.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * ---------------------------------------------------------------------------
 * Chrome
 * ---------------------------------------------------------------------------
 * Top-level screen container with top bar, body, and FAB slots.
 * Exactly one Scaffold per face with id="root" — the implicit render entry point.
 * `body_kind` is LIST (scrollable, default) or CANVAS (bounded, no scroll).
 */
public class ScaffoldComponent(
  /**
   * Component id of the TopBar (or other chrome) rendered above the body.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    jsonName = "topBar",
    schemaIndex = 0,
  )
  public val top_bar: String? = null,
  /**
   * Component id of the main body content.
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 1,
  )
  public val body: String? = null,
  /**
   * Component id of the floating-action button.
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 2,
  )
  public val fab: String? = null,
  /**
   * Body layout kind — LIST (default, scrolling) or CANVAS (glance frame).
   */
  @field:WireField(
    tag = 4,
    adapter = "com.moumantai.protocol.v1.BodyKind#ADAPTER",
    jsonName = "bodyKind",
    schemaIndex = 3,
  )
  public val body_kind: BodyKind? = null,
  @field:WireField(
    tag = 200,
    adapter = "com.moumantai.protocol.v1.Modifier#ADAPTER",
    schemaIndex = 4,
  )
  public val modifier: Modifier? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<ScaffoldComponent, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ScaffoldComponent) return false
    if (unknownFields != other.unknownFields) return false
    if (top_bar != other.top_bar) return false
    if (body != other.body) return false
    if (fab != other.fab) return false
    if (body_kind != other.body_kind) return false
    if (modifier != other.modifier) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (top_bar?.hashCode() ?: 0)
      result = result * 37 + (body?.hashCode() ?: 0)
      result = result * 37 + (fab?.hashCode() ?: 0)
      result = result * 37 + (body_kind?.hashCode() ?: 0)
      result = result * 37 + (modifier?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (top_bar != null) result += """top_bar=${sanitize(top_bar)}"""
    if (body != null) result += """body=${sanitize(body)}"""
    if (fab != null) result += """fab=${sanitize(fab)}"""
    if (body_kind != null) result += """body_kind=$body_kind"""
    if (modifier != null) result += """modifier=$modifier"""
    return result.joinToString(prefix = "ScaffoldComponent{", separator = ", ", postfix = "}")
  }

  public fun copy(
    top_bar: String? = this.top_bar,
    body: String? = this.body,
    fab: String? = this.fab,
    body_kind: BodyKind? = this.body_kind,
    modifier: Modifier? = this.modifier,
    unknownFields: ByteString = this.unknownFields,
  ): ScaffoldComponent = ScaffoldComponent(top_bar, body, fab, body_kind, modifier, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ScaffoldComponent> = object : ProtoAdapter<ScaffoldComponent>(
      FieldEncoding.LENGTH_DELIMITED, 
      ScaffoldComponent::class, 
      "type.googleapis.com/moumantai.v1.ScaffoldComponent", 
      PROTO_3, 
      null, 
      "moumantai/v1/components.proto"
    ) {
      override fun encodedSize(`value`: ScaffoldComponent): Int {
        var size = value.unknownFields.size
        size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.top_bar)
        size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.body)
        size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.fab)
        size += BodyKind.ADAPTER.encodedSizeWithTag(4, value.body_kind)
        size += Modifier.ADAPTER.encodedSizeWithTag(200, value.modifier)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ScaffoldComponent) {
        ProtoAdapter.STRING.encodeWithTag(writer, 1, value.top_bar)
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.body)
        ProtoAdapter.STRING.encodeWithTag(writer, 3, value.fab)
        BodyKind.ADAPTER.encodeWithTag(writer, 4, value.body_kind)
        Modifier.ADAPTER.encodeWithTag(writer, 200, value.modifier)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ScaffoldComponent) {
        writer.writeBytes(value.unknownFields)
        Modifier.ADAPTER.encodeWithTag(writer, 200, value.modifier)
        BodyKind.ADAPTER.encodeWithTag(writer, 4, value.body_kind)
        ProtoAdapter.STRING.encodeWithTag(writer, 3, value.fab)
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.body)
        ProtoAdapter.STRING.encodeWithTag(writer, 1, value.top_bar)
      }

      override fun decode(reader: ProtoReader): ScaffoldComponent {
        var top_bar: String? = null
        var body: String? = null
        var fab: String? = null
        var body_kind: BodyKind? = null
        var modifier: Modifier? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> top_bar = ProtoAdapter.STRING.decode(reader)
            2 -> body = ProtoAdapter.STRING.decode(reader)
            3 -> fab = ProtoAdapter.STRING.decode(reader)
            4 -> try {
              body_kind = BodyKind.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            200 -> modifier = Modifier.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ScaffoldComponent(
          top_bar = top_bar,
          body = body,
          fab = fab,
          body_kind = body_kind,
          modifier = modifier,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ScaffoldComponent): ScaffoldComponent = value.copy(
        modifier = value.modifier?.let(Modifier.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<ScaffoldComponent> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
