// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.SliderComponent in moumantai/v1/components.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Double
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Numeric range slider.
 */
public class SliderComponent(
  /**
   * Current value.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.moumantai.protocol.v1.DynamicDouble#ADAPTER",
    declaredName = "value",
    schemaIndex = 0,
  )
  public val value_: DynamicDouble? = null,
  /**
   * Minimum allowed value.
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#DOUBLE",
    schemaIndex = 1,
  )
  public val min: Double? = null,
  /**
   * Maximum allowed value.
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#DOUBLE",
    schemaIndex = 2,
  )
  public val max: Double? = null,
  /**
   * Step size (defaults to platform-native granularity when unset).
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#DOUBLE",
    schemaIndex = 3,
  )
  public val step: Double? = null,
  /**
   * Slider label.
   */
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 4,
  )
  public val label: String? = null,
  /**
   * Change action.
   */
  @field:WireField(
    tag = 6,
    adapter = "com.moumantai.protocol.v1.Action#ADAPTER",
    schemaIndex = 5,
  )
  public val action: Action? = null,
  @field:WireField(
    tag = 200,
    adapter = "com.moumantai.protocol.v1.Modifier#ADAPTER",
    schemaIndex = 6,
  )
  public val modifier: Modifier? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<SliderComponent, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is SliderComponent) return false
    if (unknownFields != other.unknownFields) return false
    if (value_ != other.value_) return false
    if (min != other.min) return false
    if (max != other.max) return false
    if (step != other.step) return false
    if (label != other.label) return false
    if (action != other.action) return false
    if (modifier != other.modifier) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (value_?.hashCode() ?: 0)
      result = result * 37 + (min?.hashCode() ?: 0)
      result = result * 37 + (max?.hashCode() ?: 0)
      result = result * 37 + (step?.hashCode() ?: 0)
      result = result * 37 + (label?.hashCode() ?: 0)
      result = result * 37 + (action?.hashCode() ?: 0)
      result = result * 37 + (modifier?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (value_ != null) result += """value_=$value_"""
    if (min != null) result += """min=$min"""
    if (max != null) result += """max=$max"""
    if (step != null) result += """step=$step"""
    if (label != null) result += """label=${sanitize(label)}"""
    if (action != null) result += """action=$action"""
    if (modifier != null) result += """modifier=$modifier"""
    return result.joinToString(prefix = "SliderComponent{", separator = ", ", postfix = "}")
  }

  public fun copy(
    value_: DynamicDouble? = this.value_,
    min: Double? = this.min,
    max: Double? = this.max,
    step: Double? = this.step,
    label: String? = this.label,
    action: Action? = this.action,
    modifier: Modifier? = this.modifier,
    unknownFields: ByteString = this.unknownFields,
  ): SliderComponent = SliderComponent(value_, min, max, step, label, action, modifier,
      unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<SliderComponent> = object : ProtoAdapter<SliderComponent>(
      FieldEncoding.LENGTH_DELIMITED, 
      SliderComponent::class, 
      "type.googleapis.com/moumantai.v1.SliderComponent", 
      PROTO_3, 
      null, 
      "moumantai/v1/components.proto"
    ) {
      override fun encodedSize(`value`: SliderComponent): Int {
        var size = value.unknownFields.size
        size += DynamicDouble.ADAPTER.encodedSizeWithTag(1, value.value_)
        size += ProtoAdapter.DOUBLE.encodedSizeWithTag(2, value.min)
        size += ProtoAdapter.DOUBLE.encodedSizeWithTag(3, value.max)
        size += ProtoAdapter.DOUBLE.encodedSizeWithTag(4, value.step)
        size += ProtoAdapter.STRING.encodedSizeWithTag(5, value.label)
        size += Action.ADAPTER.encodedSizeWithTag(6, value.action)
        size += Modifier.ADAPTER.encodedSizeWithTag(200, value.modifier)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: SliderComponent) {
        DynamicDouble.ADAPTER.encodeWithTag(writer, 1, value.value_)
        ProtoAdapter.DOUBLE.encodeWithTag(writer, 2, value.min)
        ProtoAdapter.DOUBLE.encodeWithTag(writer, 3, value.max)
        ProtoAdapter.DOUBLE.encodeWithTag(writer, 4, value.step)
        ProtoAdapter.STRING.encodeWithTag(writer, 5, value.label)
        Action.ADAPTER.encodeWithTag(writer, 6, value.action)
        Modifier.ADAPTER.encodeWithTag(writer, 200, value.modifier)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: SliderComponent) {
        writer.writeBytes(value.unknownFields)
        Modifier.ADAPTER.encodeWithTag(writer, 200, value.modifier)
        Action.ADAPTER.encodeWithTag(writer, 6, value.action)
        ProtoAdapter.STRING.encodeWithTag(writer, 5, value.label)
        ProtoAdapter.DOUBLE.encodeWithTag(writer, 4, value.step)
        ProtoAdapter.DOUBLE.encodeWithTag(writer, 3, value.max)
        ProtoAdapter.DOUBLE.encodeWithTag(writer, 2, value.min)
        DynamicDouble.ADAPTER.encodeWithTag(writer, 1, value.value_)
      }

      override fun decode(reader: ProtoReader): SliderComponent {
        var value_: DynamicDouble? = null
        var min: Double? = null
        var max: Double? = null
        var step: Double? = null
        var label: String? = null
        var action: Action? = null
        var modifier: Modifier? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> value_ = DynamicDouble.ADAPTER.decode(reader)
            2 -> min = ProtoAdapter.DOUBLE.decode(reader)
            3 -> max = ProtoAdapter.DOUBLE.decode(reader)
            4 -> step = ProtoAdapter.DOUBLE.decode(reader)
            5 -> label = ProtoAdapter.STRING.decode(reader)
            6 -> action = Action.ADAPTER.decode(reader)
            200 -> modifier = Modifier.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return SliderComponent(
          value_ = value_,
          min = min,
          max = max,
          step = step,
          label = label,
          action = action,
          modifier = modifier,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: SliderComponent): SliderComponent = value.copy(
        value_ = value.value_?.let(DynamicDouble.ADAPTER::redact),
        action = value.action?.let(Action.ADAPTER::redact),
        modifier = value.modifier?.let(Modifier.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<SliderComponent> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
