// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.TextComponent in moumantai/v1/components.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * ---------------------------------------------------------------------------
 * Atoms
 * ---------------------------------------------------------------------------
 * Display text with typography styling.
 */
public class TextComponent(
  /**
   * Text content.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.moumantai.protocol.v1.DynamicString#ADAPTER",
    schemaIndex = 0,
  )
  public val text: DynamicString? = null,
  /**
   * Material 3 typography role.
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 1,
  )
  public val typography: String? = null,
  /**
   * CSS-compatible color token or hex value.
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 2,
  )
  public val color: String? = null,
  /**
   * Font weight bucket.
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    jsonName = "fontWeight",
    schemaIndex = 3,
  )
  public val font_weight: String? = null,
  /**
   * Text alignment.
   */
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    jsonName = "textAlign",
    schemaIndex = 4,
  )
  public val text_align: String? = null,
  /**
   * Modifier (shared shape).
   */
  @field:WireField(
    tag = 200,
    adapter = "com.moumantai.protocol.v1.Modifier#ADAPTER",
    schemaIndex = 5,
  )
  public val modifier: Modifier? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<TextComponent, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is TextComponent) return false
    if (unknownFields != other.unknownFields) return false
    if (text != other.text) return false
    if (typography != other.typography) return false
    if (color != other.color) return false
    if (font_weight != other.font_weight) return false
    if (text_align != other.text_align) return false
    if (modifier != other.modifier) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (text?.hashCode() ?: 0)
      result = result * 37 + (typography?.hashCode() ?: 0)
      result = result * 37 + (color?.hashCode() ?: 0)
      result = result * 37 + (font_weight?.hashCode() ?: 0)
      result = result * 37 + (text_align?.hashCode() ?: 0)
      result = result * 37 + (modifier?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (text != null) result += """text=$text"""
    if (typography != null) result += """typography=${sanitize(typography)}"""
    if (color != null) result += """color=${sanitize(color)}"""
    if (font_weight != null) result += """font_weight=${sanitize(font_weight)}"""
    if (text_align != null) result += """text_align=${sanitize(text_align)}"""
    if (modifier != null) result += """modifier=$modifier"""
    return result.joinToString(prefix = "TextComponent{", separator = ", ", postfix = "}")
  }

  public fun copy(
    text: DynamicString? = this.text,
    typography: String? = this.typography,
    color: String? = this.color,
    font_weight: String? = this.font_weight,
    text_align: String? = this.text_align,
    modifier: Modifier? = this.modifier,
    unknownFields: ByteString = this.unknownFields,
  ): TextComponent = TextComponent(text, typography, color, font_weight, text_align, modifier,
      unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<TextComponent> = object : ProtoAdapter<TextComponent>(
      FieldEncoding.LENGTH_DELIMITED, 
      TextComponent::class, 
      "type.googleapis.com/moumantai.v1.TextComponent", 
      PROTO_3, 
      null, 
      "moumantai/v1/components.proto"
    ) {
      override fun encodedSize(`value`: TextComponent): Int {
        var size = value.unknownFields.size
        size += DynamicString.ADAPTER.encodedSizeWithTag(1, value.text)
        size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.typography)
        size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.color)
        size += ProtoAdapter.STRING.encodedSizeWithTag(4, value.font_weight)
        size += ProtoAdapter.STRING.encodedSizeWithTag(5, value.text_align)
        size += Modifier.ADAPTER.encodedSizeWithTag(200, value.modifier)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: TextComponent) {
        DynamicString.ADAPTER.encodeWithTag(writer, 1, value.text)
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.typography)
        ProtoAdapter.STRING.encodeWithTag(writer, 3, value.color)
        ProtoAdapter.STRING.encodeWithTag(writer, 4, value.font_weight)
        ProtoAdapter.STRING.encodeWithTag(writer, 5, value.text_align)
        Modifier.ADAPTER.encodeWithTag(writer, 200, value.modifier)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: TextComponent) {
        writer.writeBytes(value.unknownFields)
        Modifier.ADAPTER.encodeWithTag(writer, 200, value.modifier)
        ProtoAdapter.STRING.encodeWithTag(writer, 5, value.text_align)
        ProtoAdapter.STRING.encodeWithTag(writer, 4, value.font_weight)
        ProtoAdapter.STRING.encodeWithTag(writer, 3, value.color)
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.typography)
        DynamicString.ADAPTER.encodeWithTag(writer, 1, value.text)
      }

      override fun decode(reader: ProtoReader): TextComponent {
        var text: DynamicString? = null
        var typography: String? = null
        var color: String? = null
        var font_weight: String? = null
        var text_align: String? = null
        var modifier: Modifier? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> text = DynamicString.ADAPTER.decode(reader)
            2 -> typography = ProtoAdapter.STRING.decode(reader)
            3 -> color = ProtoAdapter.STRING.decode(reader)
            4 -> font_weight = ProtoAdapter.STRING.decode(reader)
            5 -> text_align = ProtoAdapter.STRING.decode(reader)
            200 -> modifier = Modifier.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return TextComponent(
          text = text,
          typography = typography,
          color = color,
          font_weight = font_weight,
          text_align = text_align,
          modifier = modifier,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: TextComponent): TextComponent = value.copy(
        text = value.text?.let(DynamicString.ADAPTER::redact),
        modifier = value.modifier?.let(Modifier.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<TextComponent> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
