// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.TodoStatus in moumantai/v1/chat.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int
import kotlin.Suppress

/**
 * Status of a single item in the edit-agent's TodoWrite list. Used only by
 * ChatTodosUpdate.
 */
public enum class TodoStatus(
  override val `value`: Int,
) : WireEnum {
  TODO_STATUS_UNSPECIFIED(0),
  TODO_STATUS_PENDING(1),
  TODO_STATUS_IN_PROGRESS(2),
  TODO_STATUS_COMPLETED(3),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<TodoStatus> = object : EnumAdapter<TodoStatus>(
      TodoStatus::class, 
      PROTO_3, 
      TodoStatus.TODO_STATUS_UNSPECIFIED
    ) {
      override fun fromValue(`value`: Int): TodoStatus? = TodoStatus.fromValue(`value`)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): TodoStatus? = when (`value`) {
      0 -> TODO_STATUS_UNSPECIFIED
      1 -> TODO_STATUS_PENDING
      2 -> TODO_STATUS_IN_PROGRESS
      3 -> TODO_STATUS_COMPLETED
      else -> null
    }
  }
}
