// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.TopBarComponent in moumantai/v1/components.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

/**
 * App bar with title and navigation / action affordances.
 */
public class TopBarComponent(
  /**
   * Title text (may be path-resolved).
   */
  @field:WireField(
    tag = 1,
    adapter = "com.moumantai.protocol.v1.DynamicString#ADAPTER",
    schemaIndex = 0,
  )
  public val title: DynamicString? = null,
  /**
   * Optional navigation icon action (typically a back / hamburger button).
   */
  @field:WireField(
    tag = 2,
    adapter = "com.moumantai.protocol.v1.Action#ADAPTER",
    jsonName = "navigationAction",
    schemaIndex = 1,
  )
  public val navigation_action: Action? = null,
  actions: List<String> = emptyList(),
  @field:WireField(
    tag = 200,
    adapter = "com.moumantai.protocol.v1.Modifier#ADAPTER",
    schemaIndex = 3,
  )
  public val modifier: Modifier? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<TopBarComponent, Nothing>(ADAPTER, unknownFields) {
  /**
   * Trailing action component ids (typically a row of icon buttons).
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    schemaIndex = 2,
  )
  public val actions: List<String> = immutableCopyOf("actions", actions)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is TopBarComponent) return false
    if (unknownFields != other.unknownFields) return false
    if (title != other.title) return false
    if (navigation_action != other.navigation_action) return false
    if (actions != other.actions) return false
    if (modifier != other.modifier) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (title?.hashCode() ?: 0)
      result = result * 37 + (navigation_action?.hashCode() ?: 0)
      result = result * 37 + actions.hashCode()
      result = result * 37 + (modifier?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (title != null) result += """title=$title"""
    if (navigation_action != null) result += """navigation_action=$navigation_action"""
    if (actions.isNotEmpty()) result += """actions=${sanitize(actions)}"""
    if (modifier != null) result += """modifier=$modifier"""
    return result.joinToString(prefix = "TopBarComponent{", separator = ", ", postfix = "}")
  }

  public fun copy(
    title: DynamicString? = this.title,
    navigation_action: Action? = this.navigation_action,
    actions: List<String> = this.actions,
    modifier: Modifier? = this.modifier,
    unknownFields: ByteString = this.unknownFields,
  ): TopBarComponent = TopBarComponent(title, navigation_action, actions, modifier, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<TopBarComponent> = object : ProtoAdapter<TopBarComponent>(
      FieldEncoding.LENGTH_DELIMITED, 
      TopBarComponent::class, 
      "type.googleapis.com/moumantai.v1.TopBarComponent", 
      PROTO_3, 
      null, 
      "moumantai/v1/components.proto"
    ) {
      override fun encodedSize(`value`: TopBarComponent): Int {
        var size = value.unknownFields.size
        size += DynamicString.ADAPTER.encodedSizeWithTag(1, value.title)
        size += Action.ADAPTER.encodedSizeWithTag(2, value.navigation_action)
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(3, value.actions)
        size += Modifier.ADAPTER.encodedSizeWithTag(200, value.modifier)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: TopBarComponent) {
        DynamicString.ADAPTER.encodeWithTag(writer, 1, value.title)
        Action.ADAPTER.encodeWithTag(writer, 2, value.navigation_action)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 3, value.actions)
        Modifier.ADAPTER.encodeWithTag(writer, 200, value.modifier)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: TopBarComponent) {
        writer.writeBytes(value.unknownFields)
        Modifier.ADAPTER.encodeWithTag(writer, 200, value.modifier)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 3, value.actions)
        Action.ADAPTER.encodeWithTag(writer, 2, value.navigation_action)
        DynamicString.ADAPTER.encodeWithTag(writer, 1, value.title)
      }

      override fun decode(reader: ProtoReader): TopBarComponent {
        var title: DynamicString? = null
        var navigation_action: Action? = null
        val actions = mutableListOf<String>()
        var modifier: Modifier? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> title = DynamicString.ADAPTER.decode(reader)
            2 -> navigation_action = Action.ADAPTER.decode(reader)
            3 -> actions.add(ProtoAdapter.STRING.decode(reader))
            200 -> modifier = Modifier.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return TopBarComponent(
          title = title,
          navigation_action = navigation_action,
          actions = actions,
          modifier = modifier,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: TopBarComponent): TopBarComponent = value.copy(
        title = value.title?.let(DynamicString.ADAPTER::redact),
        navigation_action = value.navigation_action?.let(Action.ADAPTER::redact),
        modifier = value.modifier?.let(Modifier.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<TopBarComponent> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
