// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.TurnStatus in moumantai/v1/enums.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int
import kotlin.Suppress

/**
 * ---------------------------------------------------------------------------
 * Chat + voice + lifecycle
 * ---------------------------------------------------------------------------
 * User-message lifecycle status. Only meaningful on user rows; assistant /
 * system rows are always TURN_STATUS_COMPLETED.
 */
public enum class TurnStatus(
  override val `value`: Int,
) : WireEnum {
  TURN_STATUS_UNSPECIFIED(0),
  TURN_STATUS_PENDING(1),
  TURN_STATUS_RUNNING(2),
  TURN_STATUS_COMPLETED(3),
  TURN_STATUS_FAILED(4),
  TURN_STATUS_TIMED_OUT(5),
  TURN_STATUS_ABORTED(6),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<TurnStatus> = object : EnumAdapter<TurnStatus>(
      TurnStatus::class, 
      PROTO_3, 
      TurnStatus.TURN_STATUS_UNSPECIFIED
    ) {
      override fun fromValue(`value`: Int): TurnStatus? = TurnStatus.fromValue(`value`)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): TurnStatus? = when (`value`) {
      0 -> TURN_STATUS_UNSPECIFIED
      1 -> TURN_STATUS_PENDING
      2 -> TURN_STATUS_RUNNING
      3 -> TURN_STATUS_COMPLETED
      4 -> TURN_STATUS_FAILED
      5 -> TURN_STATUS_TIMED_OUT
      6 -> TURN_STATUS_ABORTED
      else -> null
    }
  }
}
