// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.UiActionEscalated in moumantai/v1/apps.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import android.os.Parcelable
import com.squareup.wire.AndroidMessage
import com.squareup.wire.FieldEncoding
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * ---------------------------------------------------------------------------
 * UI action escalation hint
 * ---------------------------------------------------------------------------
 * Server hint to the originating client that a UI tap escalated to a chat
 * dialog — purely a UX cue to focus the chat surface. Disposable: not durable,
 * not replayed on reconnect (auto-showing chat after a reconnect is intentionally
 * avoided).
 */
public class UiActionEscalated(
  /**
   * Scope of the originating tap. Renderers no-op if not their active scope.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val scope: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : AndroidMessage<UiActionEscalated, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is UiActionEscalated) return false
    if (unknownFields != other.unknownFields) return false
    if (scope != other.scope) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + scope.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """scope=${sanitize(scope)}"""
    return result.joinToString(prefix = "UiActionEscalated{", separator = ", ", postfix = "}")
  }

  public fun copy(scope: String = this.scope, unknownFields: ByteString = this.unknownFields):
      UiActionEscalated = UiActionEscalated(scope, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<UiActionEscalated> = object : ProtoAdapter<UiActionEscalated>(
      FieldEncoding.LENGTH_DELIMITED, 
      UiActionEscalated::class, 
      "type.googleapis.com/moumantai.v1.UiActionEscalated", 
      PROTO_3, 
      null, 
      "moumantai/v1/apps.proto"
    ) {
      override fun encodedSize(`value`: UiActionEscalated): Int {
        var size = value.unknownFields.size
        if (value.scope != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.scope)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: UiActionEscalated) {
        if (value.scope != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.scope)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: UiActionEscalated) {
        writer.writeBytes(value.unknownFields)
        if (value.scope != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.scope)
        }
      }

      override fun decode(reader: ProtoReader): UiActionEscalated {
        var scope: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> scope = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return UiActionEscalated(
          scope = scope,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: UiActionEscalated): UiActionEscalated = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    @JvmField
    public val CREATOR: Parcelable.Creator<UiActionEscalated> = AndroidMessage.newCreator(ADAPTER)

    private const val serialVersionUID: Long = 0L
  }
}
