// Code generated by Wire protocol buffer compiler, do not edit.
// Source: moumantai.v1.VoiceStateValue in moumantai/v1/enums.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.moumantai.protocol.v1

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int
import kotlin.Suppress

/**
 * Voice-pipeline state machine. Carried in `VoiceState`.
 */
public enum class VoiceStateValue(
  override val `value`: Int,
) : WireEnum {
  VOICE_STATE_VALUE_UNSPECIFIED(0),
  VOICE_STATE_VALUE_IDLE(1),
  VOICE_STATE_VALUE_LISTENING(2),
  VOICE_STATE_VALUE_THINKING(3),
  VOICE_STATE_VALUE_SPEAKING(4),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<VoiceStateValue> = object : EnumAdapter<VoiceStateValue>(
      VoiceStateValue::class, 
      PROTO_3, 
      VoiceStateValue.VOICE_STATE_VALUE_UNSPECIFIED
    ) {
      override fun fromValue(`value`: Int): VoiceStateValue? = VoiceStateValue.fromValue(`value`)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): VoiceStateValue? = when (`value`) {
      0 -> VOICE_STATE_VALUE_UNSPECIFIED
      1 -> VOICE_STATE_VALUE_IDLE
      2 -> VOICE_STATE_VALUE_LISTENING
      3 -> VOICE_STATE_VALUE_THINKING
      4 -> VOICE_STATE_VALUE_SPEAKING
      else -> null
    }
  }
}
